s3fs-fuse/s3fs-fuse

- src/s3fs.cpp
Function "bool directory_empty()" downloads full directory listing to find out whether the directory is empty or not. This requires both a larger download from S3, and possibly multiple round trips to S3 (S3 API returns at most 1,000 entries per call). For directories with many thousands of entries, this comes with a significant performance penalty.
The modified version of the function checks for at most one entry to make a decision whether the directory is empty or not.
> Optimized function "bool directory_empty()"

- src/s3fs.cpp
- test/integration-test-common.sh
- test/passwd-s3fs
- test/s3proxy.conf
- test/small-integration-test.sh
> Use S3Proxy to run integration tests

- src/fdcache.cpp
Fixed a bug about #141 
This bug was made at #138 commit.
> Fixed a bug no use_cache case about fixed #138 - issue#141

- src/s3fs.cpp
s3fs does not have a handler for fsync until now.
It makes #145 bug after fixing use_cache bug(#138).
This pr is fixing #145.
> Fixed a bug not handling fsync - #145

- src/curl.cpp
Fixed a bug which is reported on google groups by Ben Ashmead.
https://groups.google.com/forum/#!topic/s3fs-devel/y9tAvF2gLa4
> Fixed a bug: unable to mount bucket subdirectory

- src/curl.cpp
Fixed issue #126.
Because the libcurl supported SSL session sharing at 7.23.0, the libcurl older then 7.23.0 always gets CURLSHE_BAD_OPTION in initializing curl function if s3fs runs without nosscache option.
After this patch, even though s3fs runs with under 7.23.0 libcurl when nosscache option is not specified, s3fs continue to start without SSL session sharing.(In other words, s3fs ignore a error about bad option about ssl session sharing.)
> Fixed a bug about ssl session sharing with libcurl older 7.23.0 - issue#126

- test/integration-test-common.sh
Release notes:
https://github.com/andrewgaul/s3proxy/releases/tag/s3proxy-1.4.0
> Upgrade to S3Proxy 1.4.0

- src/curl.cpp
> send the correct Host header when using -o url

- src/curl.cpp
- src/curl.h
> Auth v4 refactor

- src/s3fs.cpp
> switch to use region specific endpoints to compute correct v4 signature

- .travis.yml
- src/curl.cpp
Reviewed and fixed about printing the HTTP response code in curl.cpp.
For Issue #157.
> Reviewed and fixed response codes print in curl.cpp - #157

- configure.ac
- src/s3fs.cpp
Builds and operates on OSX Yosemite using MacPorts osxfuse
> configure.ac: detect target, if target is darwin (OSX), then

- src/s3fs.cpp
This pull request fixed following:
- fallback to sigv2 when creating bucket  
Modified "fallback to sigv2 on bucket create"(#180) by kahing  
- fixed fallback sigv2 logic for GCS.  
Modified "fix v4 fallback to work correctly for GCS"(#181) by kahing  
Fixed #179  
- do fail by timeout when connecting bucket
> fixed fallback to sigv2 for bucket create and GCS

- src/s3fs.cpp
These system calls take an extra 'position' parameter on OS X. A
non-zero position value is only valid for resource forks (the Darwin
VFS layer will reject anything else with EINVAL); this patch simply
adds and ignores the parameter on Apple platforms.
Allows building against OSXFUSE.
> Specialize {set,get}xattr for OS X

- doc/man/s3fs.1
- src/curl.cpp
- src/curl.h
- src/fdcache.cpp
- src/fdcache.h
- src/s3fs.cpp
Just cleaning up a few spelling mistakes that I noticed while evaluating this project. Thanks!
> Fixed a few small spelling issues.

- ChangeLog
- configure.ac
This is a change for the v1.79 release.
> Updated ChangeLog and configure.ac for v1.79

- src/cache.cpp
We could further improve this code by holding `stat_cache_lock` before
calls to `DelStat` instead of unlocking then relocking it.
> Always hold stat_cache_lock when using stat_cache

- src/curl.cpp
- src/string_util.cpp
- src/string_util.h
- src/test_string_util.cpp
`str` duplicates this functionality.  Also add unit test.
> Remove IntToStr

- test/integration-test-main.sh
Update test_append_file to keep file open during tests
Update remote_nonepty_directory to prevent passing test from causing exit
> Fix integration tests

- test/integration-test-main.sh
Missed some cleanup from the code review.  Sorry!
> Cleanup from PR #265

- doc/man/s3fs.1
After merging #271, added about storage_class option in man page.
> Modified man page for storage_class option(#271)

- configure.ac
- src/fdcache.cpp
This is additional modification for PR #307
Added the logic for checking pthread mutex attr in configure.ac.
> Check pthread prtability in configure as additional change for #307

- test/integration-test-main.sh
Fixed two bugs in test script.
> Update integration-test-main.sh as additional change for #300

- src/curl.cpp
* provide correct path
* sign query string
* URL encode query string
> Correct multiple issues with GET and v4 signing

- README.md
I've make a modify to allow s3fs start on boot with fstab (tested on Ubuntu 14)
> update REAME.md for fstab

- README.md
Changed example about fstab for adding another format, it is probably needed on ubuntu.
> Updated README.md for fstab example.

- src/fdcache.cpp
- src/s3fs.cpp
Added checking cache directory and it's attributes in parsing parameter function at s3fs starting.
> Check cache dirctory path and attributes - #347

- src/cache.cpp
There is a problem with the #355, it has been modified again :-(
> Fixed codes about clock_gettime for osx(3)

- src/s3fs_util.cpp
https://github.com/s3fs-fuse/s3fs-fuse/issues/358
> Issue 358: Remove optional parameter from Content-Type header

- src/s3fs_util.cpp
For #363, Changed checking "Content-Type" by no case-sensitivity(but it is simple four testing)
> Checked content-type by no case-sensitivity - #363

- src/cache.cpp
- src/cache.h
- A bug about etag comparison for stats cache is fixed.
- Chnaged about constructor(destructor) in cache.h
> Fixed a bug about etag comparison in stats cache, etc.

- src/fdcache.cpp
Fixed for writing sparsed file.
Please see detail in #375 issue comments.
> Fixed a bug about writing sparsed file - #375

- test/integration-test-main.sh
This is a test to demonstrate Issue #375
> Test for writing after an lseek past end of file

- src/curl.cpp
as simple as the title say...
:)
> fix typo in curl.cpp: s/returing/returning/

- src/fdcache.cpp
Reverts s3fs-fuse/s3fs-fuse#379
For #15 and other issue, this commit merge is broken cache file.
So I revert this.
> Revert "Fixed a bug about writing sparsed file - #375"

- src/fdcache.cpp
Fixed #375 
This PR is a recommit #379 has been revert by #394 , then this patched #379.
#379 will have a problem breaking the cache of objects, that is reported by #15, etc.
> Fixed writing sparsed file - #375,#379,#394

- src/curl.cpp
- src/curl.h
Currently s3fs creates a new tcp connection for each request to s3. Together with the fact that curl(or HTTP) defaults to use 'Connection:keep-alive', the client may ends with lots of 'TIME_WAIT' connections:
```
ubuntu@ip-172-31-29-108:~/s3fs-fuse$ for i in $(seq 100); do ls /tmp/s3fs > /dev/null; done
ubuntu@ip-172-31-29-108:~/s3fs-fuse$ sudo ss -tan | grep TIME | wc -l
101
```
This patches enables reusing curl handlers and thus utilizes HTTP keep-alive, which has the effects:
1. boost performance
2. largely reduce TIME_WAIT connections
> Add curl handler pool to reuse connections

- src/s3fs.cpp
> Fixed 'load_sse_c' option not working - #388

- src/curl.cpp
- src/s3fs.cpp
Patches for several issues:
https://github.com/s3fs-fuse/s3fs-fuse/issues/419
https://github.com/s3fs-fuse/s3fs-fuse/issues/421
> Fixes for iam_role=auto

- README.md
Added travis CI badge in README.md.
> Added travis CI badge in README.md

- ChangeLog
- configure.ac
Updates ChangeLog and configure.ac for release 1.80.
After this merge we tagging for new release.
> Updated ChangeLog and configure.ac for release 1.80

- src/s3fs.cpp
This allows creating buckets in non-default regions.  Also improve
`do_create_bucket` error handling.
> Include location constraint when creating bucket

- README.md
added fuse package for mounting via /etc/fstab, fixes #417
> added fuse package for mounting via /etc/fstab, fixes #417

- src/fdcache.cpp
- src/fdcache.h
- src/s3fs.cpp
- src/s3fs_util.cpp
- src/s3fs_util.h
Fixes an issue with "mount -a" failing for an already-mounted s3fs file system, on linux.
> Accept mount options compatible with mtab

- README.md
> Correct path in README

- src/curl.cpp
When `-ocurldbg` is on you get some weird messy output like:
```
> GET / HTTP/1.1#015#012User-Agent: s3fs/1.80 (commit hash unknown; OpenSSL)#015#012Accept: */*#015#012Authorization: AWS4-HMAC-SHA256 Credential=xxx, SignedHeaders=host;x-amz-ontent-sha256;x-amz-date, Signature=xxx#015#012host: xxx.s3.amazonaws.com#015#012x-amz-content-sha256: xxx#015#012x-amz-date: xxx#015#012#015
```
This PR changes it so it looks like this:
```
> GET / HTTP/1.1
> User-Agent: s3fs/1.80 (commit hash unknown; OpenSSL)
> Accept: */*
> Authorization: AWS4-HMAC-SHA256 Credential=xxx, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=xxx
> host: xxx.s3.amazonaws.com
> x-amz-content-sha256: xxx
> x-amz-date: xxx
> 
```
It might also be a bit faster as it doesn't require any allocation.
> Split header debugging onto multiple lines for easier reading

- src/fdcache.cpp
> Fixed issue#435 branch codes for remaining bugs(2)

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
I prepared a template for Issue and PullRequest.
The template of Issue has diverted the contents used from old s3fs Googlecode.
> Added issue and PR templates.

- doc/man/s3fs.1
> Update s3fs.1 - removed duplicated word

- README.md
#515
Added a URL link to S3 consistency FAQ document in README.md.
> Added links for eventual consistency in README.md - #515

- src/curl.cpp
This avoids calculating the MD5 locally and enables use with object
stores which do not use MD5 as ETag.
> Use server-provided ETag during complete upload

- src/s3fs_util.cpp
#545
Fixed because I forgot to update option explanation in help display.
> Updated stat_cache_expire option description - #545

- src/s3fs.cpp
n/a
The get_object_attribute function had become code with unnecessary structure due to many modifications.
So I refactored this function.
**Note**  
The "check_object_access function" words of the commit message before merging is a mistook and it is correctly "get_object_attribute function".
> Refactored the get_object_attribute function

- src/curl.cpp
#584 #486
In the case of SSE_C and SSE_KMS, the problem of file(object) upload/rename failed was fixed.
One cause is that the ETAG of the response is not MD5 when s3fs run with SSE_C and SSE_KMS parameter. Please see following document:
Http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html
Http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingKMSEncryption.html
@driskell pointed out this problem at #486 PR.
The cause of the malfunction of rename was that SSE_KMS header was added, despite the object was SSE_C before rename.
These bugs have been fixed.
NOTE:
@driskell, thanks for your kindness and I'm sorry for late fixing.
> Fixed failure to upload/copy with SSE_C and SSE_KMS

- doc/man/s3fs.1
#567 
We need to update man page about default_acl option like #567.
Thanks @andrewgaul
> Updated man page for default_acl option - #567

- ChangeLog
- configure.ac
#586 
It is the final modification of version 1.81.
The version number in ChangeLog and configure.ac has been incremented.
> Updated ChangeLog and configure.ac for release 1.81

- ChangeLog
- configure.ac
#596 #593 https://github.com/s3fs-fuse/s3fs-fuse/commit/465c15ef405a9e45f4ebc8dd6aea919f419242fc
Release 1.82, it is an urgent version up for 1.81 problem.
> Updated ChangeLog and configure.ac for release 1.82

- .travis.yml
- Makefile.am
- src/test_util.h
- test/integration-test-common.sh
- test/integration-test-main.sh
- test/test-utils.sh
#601
OSX can be supported by TravisCI's multiple OS build, merge the macosx branch to master and delete it.
> Merged macosx branch into master branch #601

- README.md
> Add blurb about non-Amazon S3 implementations

- README.md
These moved to homebrew-core:
https://github.com/Homebrew/homebrew-core/pull/11283
> Update Homebrew instructions

- src/curl.cpp
- src/curl.h
- src/s3fs.cpp
#633
I created a static method in S3fsCurl to create a User Agent string.
And this class method was called only once from s3fs.cpp before creating threads.
> Fixed potential atomic violation in S3fsCurl::AddUserAgent - #633

- src/curl.cpp
#643
Unnecessary equal character was deleted.
> Fixed with unnecessary equal in POST uploads url argment - #643

- src/s3fs.cpp
base of #658 PR for issue #625
This is PR based on @tlevi - #658.
It is a code that also corresponded to other related processing related to the bug found @tlevi.
For details, see #658.
> Do not fail updating directory when removing old-style object(ref #658)

- src/fdcache.cpp
> Lock FdEntity when mutating orgmeta

- src/curl.cpp
#665
Fixed a bug:
Originally, it searches libcurl for the CA file path corresponding to each OS, but if it still becomes the error CURLE_SSL_CACERT, it should have done the operation to set the environment variable.
This process was corrected because there was a problem, another value was to be set again after the CA path of the environment variable was set.
> Fixed a bug in S3fsCurl::LocateBundle

- README.md
#672
#672 PR based on the contents of PR.(Additional lines are as same as #672)
We also change the debugging options.
> README.md Addition

- src/curl.cpp
- src/string_util.cpp
- src/string_util.h
Also clean up some `char *` to `std::string` conversions.
> Move str definition from header to implementation

- src/s3fs.cpp
#669
It is a fix for # 669 PR.
Refactored functions on loading passwd file.
I gathered duplicate logic.
> Changed functions about reading passwd file

- .travis.yml
- configure.ac
- src/curl.cpp
#685 
Reverting the use of jsoncpp - introduced recently in #671.
> remove use of jsoncpp

- src/fdcache.cpp
#678
Changed to use rand instead of tmpnam to generate a temporary file name.
> Improved use of temporary files - #678

- doc/man/s3fs.1
#671
Added option ecs description to man page.
> Added option ecs description to man page

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
n/a
Updating .github/*.md template files for Issue and PullRequest.
> Updated template md files for issue and pr

- src/common.h
- src/s3fs.cpp
- src/s3fs_util.cpp
Fixes to get v1.83 building on FreeBSD 10 and 11 i386/amd86.
> FreeBSD build fixes

- README.md
Also reorganize installation vs. compilation.
> Simplify installation for Ubuntu 16.04

- README.md
> Remove s3fs-python

- .github/ISSUE_TEMPLATE.md
Now that we have binary packages for Debian, Ubuntu, Fedora and RHEL/CentOS, we can improve the template for issues a little. Details on in-line comments.
> Improve template for issues

- .travis.yml
> Multi-arch support for ppc64le

- src/cache.cpp
- src/common.h
- src/curl.cpp
- src/fdcache.cpp
- src/nss_auth.cpp
- src/s3fs.cpp
Lifetime, shadowing, and unused variables.  Found via the Travis macOS
builder.
> Address cppcheck 1.86 errors

- src/s3fs.cpp
> Check arguments and environment before .aws/creds

- README.md
Also correctly format Stack Overflow.
> Add Server Fault to FAQs

- src/addhead.cpp
> Plug memory leaks

- src/s3fs.cpp
- src/s3fs_util.cpp
- src/string_util.cpp
The former can be faster.  Found via clang-tidy.
> Prefer find(char) over find(const char *)

- README.md
- doc/man/s3fs.1
- src/curl.cpp
- src/s3fs.cpp
- src/s3fs_util.cpp
Fix a few stale links as well.
> Prefer HTTPS links where possible

- src/s3fs_util.cpp
Nextcloud Compatibility in directory mime-types
Compatibility with nextcloud directory mimetypes
Access Nextcloud used buckets with s3fs
> Update s3fs_util.cpp for correspondence of Nextcloud contype

- .gitattributes
- .gitignore
- .travis.yml
n/a
Added missing file extension to .gitignore, and reviewed the contents and summarized it.
Other than that, I added headers etc. to .gitattributes and .travis.yml file.
> Added a missing extension to .gitignore, and formatted dot files

- src/s3fs.cpp
#908 #911 #807 
In the case of the default region us-east-1, when AuthorizationHeaderMalformed error occurred, automatic switching to the correct region was made.
However, when a region was specified with the endpoint option, this automatic switching was not executed.
With this new code, even if you specify a region with the endpoint option, try reconnecting to the correct region.
> Automatic region change made possible other than us-east-1(default)

- src/s3fs.cpp
#916 #912 (refixed this pr)
#908 #911 #807 
I reviewed contents of PR of #912.
Stops automatic region change processing in case of inconsistent region specification and outputs a message.
However, if endpoint is not specified and the default us-east-1 is used, the region is automatically changed.
> Reverted automatic region change and changed messages

- src/addhead.cpp
- src/curl.cpp
- src/fdcache.cpp
- src/s3fs.cpp
Found and fixed via clang-tidy.
> Prefer empty over size checks

- src/cache.cpp
- src/curl.cpp
This simplifies the code and fixes an issue with unlocked access.
Also use a recursive lock for `StatCache` to avoid races between
lock..unlock..lock sequences.
> Prefer AutoLock for synchronization

- src/fdcache.cpp
> Remove mirror path when deleting cache

- ChangeLog
- doc/man/s3fs.1
- src/fdcache.cpp
- src/psemaphore.h
- src/s3fs_util.cpp
- test/integration-test-common.sh
- test/mergedir.sh
n/a
I checked the spelling of all code using aspell.
> Checked and corrected all typo

- src/addhead.cpp
- src/curl.cpp
- src/fdcache.cpp
- src/s3fs_util.cpp
- src/string_util.cpp
These better communicate intent and are slightly more efficient.
> Prefer specific [io]stringstream where possible

- src/curl.cpp
- src/s3fs.cpp
This deinitialized `S3fsCurl` twice and incorrectly calculated V4
signatures.
> Repair utility mode

- src/curl.cpp
Amazon returns `SlowDown` when overloaded.  Also return `ENOTSUP` for 501
and immediately return `EIO` for 500 instead of retrying.  Fixes #603.
> Implement exponential backoff for 503

- src/cache.cpp
- src/curl.cpp
- src/s3fs.cpp
This has O(n) runtime instead of O(n log n).
> Clear containers instead of individual erases

- README.md
> Document lack of inotify support

- src/gnutls_auth.cpp
- src/s3fs_util.cpp
Follows on to eeb839242ba826707205b0b776c042203226d01b.
> Work around cppcheck warnings

- src/curl.cpp
- src/curl.h
#935 
Improvement of renegotiation of SSL sessions in s3fs multipart request.
s3fs is pooling curl handles inside it.
This pool behaves like a LIFO.
In the multipart request of HEAD, PUT, POST, and GET, SSL re-negotiation has occurred even though s3fs uses the curl handle of pool.
The session has been disconnected from the S3 server in about 5-10 seconds.
In the case of a HEAD request, s3fs may send a request with a 400/404 error in order to confirm the existence of the file.
This normally CURL closes the session.
The solution is to set the CURLOPT_KEEP_SENDING_ON_ERROR option to the CURL handle.
Also, since the S3 server does not use ALPN, you should also use the CURLOPT_SSL_ENABLE_ALPN option.
However, the curl version of OS on TravisCI used by s3fs is low, and these options are not …
> Improvement of curl session pool for multipart

- doc/man/s3fs.1
#960 
Changed use_wtf8 option order in man page options.
> Changed the description order of man page options

- src/fdcache.cpp
#967 
Apart from the fix in #967 , there was a part requiring subtraction of ref-count.
If an error occurs in Open processing, it is incremented before the error, so it is decremented.
> Fixed ref-count when error occurred.

- AUTHORS
- ChangeLog
- configure.ac
#976 
It is the final modification of version 1.85.
The version number in ChangeLog and configure.ac has been incremented.
And added new s3fs-fuse member @gaul.
> Updated ChangeLog and configure.ac etc for release 1.85

- src/s3fs.cpp
> Simplify string comparison

- src/s3fs.cpp
#730 
When updating directory stats, directory objects were always re-created.
A directory object that s3fs recognizes and creates as a directory is an object of `dir/` path.
If there are other directory object (`dir`) or `no directory object` in the bucket, s3fs can recognize them as directories.
When updating directory statistics (metadata), s3fs will delete and recreate directory objects other than `dir/` types.
(This is able to convert other directory object type to a `dir/` object)
However, there was a bug in determining the type of this directory object, and the directory object was always recreated.
In this PR, it has been modified to make the right decision.
> Fixed a bug about overwrite metadata at updating directory stats

- test/sample_delcache.sh
• Simplified the stat generation line (single exec, using only stat)
• Quote variables so that the cache directory can also include spaces
• while/read loop to handle spaces in cached files
(IFS was causing problems when all the files were saved into a single variable)
• Replace erroneous exit -1 with exit 1
• Prints current cache size if below supplied maximum
> Work with filenames that include spaces

- src/s3fs.cpp
- src/string_util.cpp
Found via clang-tidy.  Also fix errant indentation.
> Add missing braces

- README.md
Sort Linux distributions and simplify/standardize grammar.
> Standardize installation section

- doc/man/s3fs.1
Also fix typo in AWS credentials.
> Add environment variables to man page

- doc/man/s3fs.1
Follows on to c5ebf5d32867b7262e88da32704d76c8430ac0e0.
> Fix singlepart_copy_limit default

- src/fdcache.cpp
- src/fdcache.h
This simplifies memory management.
> Make fdpage a value type in fdpage_list_t

- .clang-tidy
- src/Makefile.am
- src/curl.cpp
- src/s3fs.cpp
- src/string_util.cpp
> Configure clang-tidy target

- src/curl.cpp
- src/curl.h
- src/s3fs.cpp
- src/s3fs_util.cpp
- src/s3fs_util.h
Also simplify `check_region_error`.
> Add simple XML parsing wrapper

- src/curl.cpp
> Fix mismatched new[]/free

- src/fdcache.cpp
Also lock before log statements which touch member variables.
> Add a missing lock to SetCtime

- src/addhead.cpp
- src/cache.cpp
- src/common_auth.cpp
- src/curl.cpp
- src/fdcache.cpp
- src/openssl_auth.cpp
- src/s3fs.cpp
- src/s3fs_util.cpp
- src/string_util.cpp
Found and fixed via clang-tidy.
> Prefer modern C headers

- src/curl.cpp
> Fix multipart upload not setting curl options

- src/string_util.cpp
- src/string_util.h
- src/test_string_util.cpp
This tightens error checking and aligns s3fs with known good behavior.
> Implement s3fs_strtoofft via strtoll

- src/fdcache.cpp
Create copies to avoid thread races.  Found via ThreadSanitizer.
Follows on to ecf13a8cb9d08406af454f318b8a2b1eb7f37995.
> Access FdEntity metadata while holding fdent_lock

- test/integration-test-main.sh
- test/test-utils.sh
> Add test to read an externally created object

- .travis.yml
This is the latest version supported by macOS 10.12.
> Upgrade to Xcode 9.2

- src/s3fs_util.cpp
- src/s3fs_util.h
> Remove unused field

- src/s3fs.cpp
> Consume return value from FdEntity::Flush

- src/curl.cpp
#1128 
In S3fsMultiCurl::MultiRead() processing, I found a possibility of a problem, so I will correct it again.
> Strict processing of MultiRead method

- test/integration-test-main.sh
> Fixed typo in #1129

- src/curl.cpp
- src/s3fs.cpp
> Fix a few bool types

- src/addhead.cpp
- src/cache.cpp
- src/cache.h
- src/curl.cpp
- src/curl.h
- src/s3fs.cpp
- src/s3fs_util.cpp
#1157 
Fixed an error that occurred in cppcheck 1.89.
Since it has an impact on PR and merge work, we are responding quickly.
> Fixed build error by cppcheck 1.89

- test/integration-test-main.sh
- test/write_multiple_offsets.py
> Add test for writing to multiple offsets

- README.md
Gentoo has the package as well, see https://packages.gentoo.org/packages/net-fs/s3fs.
> Add Gentoo install instructions

- src/curl.cpp
- src/curl.h
- src/s3fs.cpp
- src/s3fs_util.cpp
Resolves Issue #1219
Issue #1219 
This pull request adds the intelligent tiering storage class for storing files in S3
> Add intelligent tiering as option for storage class

- test/integration-test-main.sh
n/a
A test case was forgotten to delete the test file, so it was added.
> Fixed removing test file in integration-test-main.sh

- test/integration-test-main.sh
> Test that s3fs automatically detects Content-Type

- ChangeLog
- configure.ac
> Update ChangeLog and configure.ac for 1.86

- README.md
Add install instructions for Arch Linux
> Add install instructions for Arch Linux

- src/fdcache.cpp
#1245 #1191 
When serializing the page information file(stat) of the cache file, the file was not truncated.
s3fs_strtoofft function was throwing an exception, but PageList::Serialize method did not catch it.
Therefore, an intermediate wrap_strtoofft function was added that catches this exception and is called from PageList::Serialize to wrap the s3fs_strtoofft function.
> Fixed the truncation bug of stat file for cache file

- test/integration-test-main.sh
- test/write_multiple_offsets.py
References #1220.  References #1277.
> Add test for out-of-order writes

- test/integration-test-main.sh
#1277 
We needed to test the cache file and its stat file(fdcache.cpp), it was requested in #1277.
I added a test to check the contents of the cache file stat(file).
Notes: In this test, the size of the downloaded area may differ depending on the minimum upload unit, etc., so the total size of the cache file is checked.
> Add test for cache file stat content

- src/s3fs_util.cpp
- src/s3fs_util.h
- test/integration-test-main.sh
This allows s3fs to interpret objects created by gsutil.
> Support Google Cloud Storage headers

- src/cache.cpp
- src/curl.cpp
- src/fdcache.cpp
- src/openssl_auth.cpp
- src/s3fs_util.cpp
Also remove some unnecessary exception handling.
> Check results from pthread mutex calls

- src/fdcache.cpp
- src/s3fs.cpp
> Fix renames of open files with nocopyapi option

- doc/man/s3fs.1
- src/curl.cpp
- src/curl.h
- src/s3fs.cpp
- src/s3fs_util.cpp
Just a copy of what have been done in PR #271.
issue #1315
Add glacier for allowed values for storage_class.
> Add support for glacier storage class.

- src/curl.cpp
> Fix NULL pointer deference

- README.md
> `s3fs#bucketname ... fuse` -> `bucketname ... fuse.s3fs` (#1321)

- src/fdcache.cpp
- src/fdcache.h
n/a 
Since the same process was repeated, I summarized it in a method.
(This is the method you will need for the subsequent PR.)
> Put similar processing together into method GetCacheFileStatTopDir

- test/integration-test-common.sh
- test/integration-test-main.sh
> Test creating a directory with external program

- test/integration-test-main.sh
- test/test-utils.sh
> Add portability wrapper for stat(1)

- src/fdcache.cpp
Only a single thread uses this directory stream.  Further, modern
implementations are thread-safe by default and deprecated this call:
https://man7.org/linux/man-pages/man3/readdir_r.3.html
> Call readdir instead of readdir_r

- test/integration-test-common.sh
- test/run_tests_using_sanitizers.sh
These currently show several kinds of errors.
> Add script to run tests using sanitizers

- src/curl.cpp
- src/curl.h
> Consistently lock curl_times and curl_progress

- test/integration-test-main.sh
#1360 #1349
Added a test case to mv below the mount point for files outside the mount point.
The test is done with insufficient disk space.
(It is the same even when there is not insufficient disk space, but the operation of multipart upload is slightly different, so I am testing it under severe conditions)
> Added mv file test when disk space is insufficient

- src/cache.cpp
- src/cache.h
> Add const where possible

- src/gnutls_auth.cpp
- src/nss_auth.cpp
- src/openssl_auth.cpp
Also use constant for array lengths.
> Remove unneeded memset calls

- test/Makefile.am
- test/filter-suite-log.sh
- test/integration-test-common.sh
- test/integration-test-main.sh
- test/mergedir.sh
- test/require-root.sh
- test/run_tests_using_sanitizers.sh
- test/sample_delcache.sh
- test/small-integration-test.sh
- test/test-utils.sh
- test/ut_test.py
- test/write_multiple_offsets.py
> Fix expandtab settings for tests

- src/cache.h
- src/curl.cpp
- src/curl.h
- src/curl_util.h
- src/string_util.cpp
- src/string_util.h
This hints to callers on usage.
> Use const std::string& where possible

- src/s3fs_util.cpp
> Allow relative path with use_path

- test/integration-test-main.sh
#1454
The `atime` test may fail.
It happens because FUSE does not call the `s3fs_utimens` entry function.
The cause of this has not been clarified yet, but it seems that it depends on the options and stats when mounting.
It seems to be options such as relatime/noatime.
With the exception of ubuntu:xenial, the test seems to fail if the relatime/noatime option is given.
Therefore, to avoid test failures, bypass the `touch -a` command test if the relatime/noatime option is set.
> Added a condition to the atime test

- README.md
n/a
AWS promise read-after-write consistency now ([announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-s3-now-delivers-strong-read-after-write-consistency-automatically-for-all-applications/)), but presumably non-AWS S3-compatible services are still eventually consistent.
> Update README note on eventual consistency

- src/curl_util.cpp
- src/test_curl_util.cpp
Some good taste from Linus:
https://github.com/mkirchner/linked-list-good-taste
Also avoid an allocation when replacing a value and tighten up tests.
> Simply curl_slist_sort_insert

- ChangeLog
> Updated ChangeLog for release 1.88

- src/s3fs.cpp
Follows on to 4d833a4fb9ffc70cf5ba399e08390417423901ae.
References #1523.
> Propagate errno from get_local_fent

- src/addhead.cpp
- src/cache.cpp
- src/curl.cpp
- src/curl_util.cpp
- src/metaheader.cpp
- src/s3fs.cpp
- src/s3objlist.cpp
- src/string_util.cpp
This avoids creating a new `std::string`.
> Simplify substr manipulations with erase

- src/curl.cpp
> Parse more specific AWS error codes

- src/s3fs_logger.cpp
- src/s3fs_logger.h
> Increase buffer size to avoid warning

- src/s3fs.cpp
> Allow -1 value to disable max_dirty_data

- src/curl.cpp
Previously mixupload failed with larger objects due to the AWS
constraint on part sizes.  This symptom was seen more frequently due
to periodic flushing of dirty data.  Fixes #1547.
> Copy at most 5 GB per multipart copy part request

- src/s3fs_logger.h
#1540 
Using gettimeofday for log output will reduce performance.
It will be especially clear when the debug level produces a lot of output, such as INFO.
Instead, call clock_gettime with CLOCK_MONOTONIC_COARSE.
In some cases such as OSX, CLOCK_MONOTONIC_COARSE is not supported. In that case, use CLOCK_MONOTONIC.
> Use clock_gettime instead of gettimeofday

- src/s3fs.cpp
- test/small-integration-test.sh
This is documented to be in MB not KB.
> Correct singlepart_copy_limit unit

- test/integration-test-main.sh
n/a
In some test cases, I forgot to delete the used test files and directories, so I fixed it.
> Fixed forgetting to clean up test files

- test/integration-test-common.sh
- test/test-utils.sh
This PR contains a correction of a typo in an error message and allows changing the temporary directory used for tests.
> Minor improvements for tests

- src/s3fs.cpp
> Update ctime when truncating file

- src/addhead.cpp
- src/curl.cpp
n/a
Fixed errors in cppchek 2.4.1(currently MacOS only).
> Fixed codes for cppcheck 2.4.1

- src/s3fs.cpp
> Update ctime and mtime when opening with O_TRUNC

- src/cache.cpp
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/metaheader.cpp
- src/metaheader.h
- src/s3fs.cpp
- src/string_util.cpp
Found via pjdfstests.  References #897.  References #1589.
> Preserve sub-second time precision

- doc/man/s3fs.1
- src/s3fs.cpp
- src/s3fs_help.cpp
NA
IBM IAM endpoint is changed and this PR is to make relevant update in the code base.
New endpoint: https://iam.cloud.ibm.com
https://cloud.ibm.com/apidocs/iam-identity-token-api#endpoints
> Change in ibm iam endpoint

- src/s3fs.cpp
Previously s3fs allowed mounting but all operations returned `EIO`.
References #693.
> Fail CheckBucket when S3 returns PermanentRedirect

- src/fdcache.cpp
- test/integration-test-main.sh
- test/ut_test.py
Regression introduced in f5bf41cf117e6dfc0d510348cdc1cc11817662ed.
Fixes #1575.
> Allow truncation of open and modified files

- src/curl.cpp
- src/curl.h
S3 can emit these in unusual situations.  Fixes #1317.
> Consider S3 errors in HTTP PUT 200 responses

- doc/man/s3fs.1
References s3fs-fuse#1591.
References s3fs-fuse#1595.
> Add section about storage consumption to manpage

- src/cache.cpp
This avoids a duplicate lookups.
> Prefer std::map::insert over find and operator[]

- src/fdcache_entity.cpp
n/a
I found a bug in the FdEntity::RowFlush method and fixed it.
It was forgot to start multipart upload in the process when it detected that the disk space was insufficient.
The current test was unable to detect this bug because it had to detect out of disk space just when flushing.
The test case for this will be difficult, though we need to think about it in the future.
> Fixed a bug when the disk capacity was insufficient in RowFlush

- src/fdcache.cpp
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/s3fs.cpp
Found via Threadsanitizer.  Fixes #1471.
> Fix data races caused by incorrect locking

- src/addhead.cpp
- src/curl.cpp
- src/curl.h
- src/curl_util.cpp
- src/s3fs.cpp
- src/s3fs_xml.cpp
- src/s3objlist.cpp
> Prefer std::string::empty over length == 0

- .github/workflows/linux-ci-helper.sh
- test/test-utils.sh
This allows tests to pass using the S3Proxy filesystem provider.
References #1665.
> Set LC_ALL=en_US.UTF-8 in tests

- .github/workflows/ci.yml
- test/small-integration-test.sh
This allows CI to run the full set of tests while making local
development faster.
> Add flag to run all tests

- src/curl.cpp
- src/mvnode.cpp
This slightly simplifies memory management.
> Address cppcheck 2.5 warnings

- src/curl.cpp
- src/curl_util.cpp
- src/s3fs.cpp
- src/string_util.cpp
- src/string_util.h
This removes some global constructors.  Also use a consistent `ALL_CAPS`
style.
> Make string constants read-only const

- ChangeLog
- configure.ac
> Update ChangeLog and configure.ac for 1.90

- src/curl.cpp
> Consume return value from curl_easy_setopt

- src/curl.cpp
AWS IMDSv2 support was added in #1462, but the implementation did not
cover the addional IMDS access that occurs with the iam_role=auto
configuration.  This change implements IMDSv2 support for the IMDS
call to determine the instance's role name.
See also
https://stackoverflow.com/questions/69031023/how-to-make-s3fs-use-imds-v2-when-mounting-s3-buckets-from-ec2-instance
> fix IAM role retrieval from IMDSv2

- test/integration-test-main.sh
s3fs can also do this via `utimensat` but tests should not trust this.
Also break tests into individual functions.  This further reduces test
run-time 8 seconds per flag.
> Use AWS CLI to create explicit times in the past

- .github/workflows/linux-ci-helper.sh
This reduces the dependencies installed.
> Install default-jdk-headless instead of default-jdk

- .github/workflows/linux-ci-helper.sh
- test/integration-test-common.sh
The former is lighter-weight and libcurl is already a dependency for
s3fs.
> Prefer curl over wget for fetching dependencies

- src/s3fs.cpp
- test/integration-test-common.sh
- test/small-integration-test.sh
- test/test-utils.sh
AWS CLI can do this.  Fixes #1840.
> Remove createbucket option

- src/cache.cpp
- src/s3fs.cpp
- src/s3fs_util.h
FUSE 3 will require this behavior.  References #1159.
> Handle UTIME_NOW and UTIME_OMIT special values

- .github/workflows/linux-ci-helper.sh
- src/s3fs_xml.cpp
n/a
Fixed some Github Actions errors.
- Fix knownConditionTrueFalse cppcheck(2.7) error on MacOS
- Fixed package installing failure of appstream download on centos8
> Fixed some Github Actions errors.

- src/s3fs_cred.cpp
#1878 
I found a bug and fixed it.
> Fixed a bug in S3fsCred::InitialS3fsCredentials

- doc/man/s3fs.1
Add a new section about performance considerations to the manpage and align the description of notsup_compat_dir.
Closes #1892
> Add "Performance considerations" to manpage

- test/integration-test-main.sh
This is portable between Linux and macOS.
> Filter mountpoints via mount -t

- test/integration-test-common.sh
> Use custom CA bundle instead of ignoring errors

- ChangeLog
- configure.ac
> Update ChangeLog and configure.ac for 1.91

- doc/man/s3fs.1.in
- src/s3fs_help.cpp
Announcement:
https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-s3-glacier-instant-retrieval-storage-class/
This does not require code changes due to
bbcccd6e9816ebb16ca33d2003d563b24625a053.
> Document glacier_ir storage class

- .github/workflows/ci.yml
- .github/workflows/linux-ci-helper.sh
- test/test-utils.sh
#1932 
Change AWS CLI version1 to version2.
> Replace awscli version 1 to 2

- src/curl_util.cpp
- src/test_curl_util.cpp
Also backfill tests.  Fixes #1948.
> Fix double-iteration in curl_slist_remove

- src/metaheader.cpp
> Avoid extended initializer lists in C++03

- test/run_tests_using_sanitizers.sh
Theoretically msan can do this but practically it requires a custom
libc++.
> Add Valgrind to sanitizer script

- src/s3fs.cpp
> Consume return code from get_object_attribute

- src/curl.cpp
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/s3fs.cpp
- src/s3fs_xml.cpp
> Remove more uses of `const_cast`

- .clang-tidy
- src/curl_multi.cpp
- src/fdcache_fdinfo.cpp
- src/s3fs_xml.cpp
- src/threadpoolman.cpp
Prefer more precise C++-style casts.
> Avoid C-style casts

- src/fdcache_fdinfo.cpp
#2017
Sorry for this is an additional fix for #2017.
> Strictly reviewed the exclusive control of PseudoFdInfo class(additional change)

- src/fdcache_page.cpp
#2019 #2027
The following issues were reported.
- High CPU load when running s3fs (#2027)
- Extremely poor performance in `fio` test with multi number of job (#2019)
Both of these seem to be caused by the processing by the `page list` of `fdcache` operation in the `PageList` class.
There was a problem with `page list` compress and data extraction logic, resulting in poor performance.
Below are the values when measured with `gprof`:
```
%   cumulative   self              self     total
time   seconds   seconds    calls  us/call  us/call  name
71.51      1.33     1.33    49576    26.83    26.83  raw_compress_fdpage_list(std::__cxx11::list<fdpage, std::allocator<fdpage> > const&, bool, bool, bool, bool) [clone .constprop.56]
13.44      1.58     0.25    12672    19.73    19.73 …
```
> Improved fdcache_page performance

- test/sample_delcache.sh
> fix: handle file names with ':' in them

- src/curl.cpp
These functions already use `pread` and keep track of an explicit offset
for the SHA-256 calculations.
> Remove unnecessary calls to dup

- src/curl.cpp
#1827 
I have chnaged the comment and added it as a note.
> Updated comments in curl.cpp (related to #1827)

- doc/man/s3fs.1.in
> Fix man page inaccuracies

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
n/a
Fixed template markdown for Issues/Pull Requests on Github.
I just changed it to hide comments such as samples.
> Updated issue and pull request github templates

- src/cache.cpp
- src/cache.h
- src/curl.cpp
- src/curl.h
- src/curl_multi.h
- src/curl_util.h
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
- src/fdcache_untreated.cpp
- src/fdcache_untreated.h
- src/s3fs.cpp
- src/s3fs_cred.cpp
- src/s3fs_cred.h
- src/threadpoolman.cpp
- src/threadpoolman.h
This requires making some locks mutable.
> Make some methods and parameters const

- src/curl.cpp
#2085 #1816
In the multipart upload logic with SSE, there was a bug that could not be processed correctly except for copy processing.
This PR is fixed these.
> Fixed a bug about multipart upload with SSE

- src/s3fs_cred.cpp
https://github.com/s3fs-fuse/s3fs-fuse/issues/1778#issuecomment-1407172269
Fixed some incorrect judgments when specifying an external credential authentication library(specified by `credlib` option).
This is a bug reported by @artificial-aidan.
Thanks @artificial-aidan for great help.
> Fixed token update process using ext-cred library

- src/s3fs.cpp
https://github.com/s3fs-fuse/s3fs-fuse/issues/1460#issuecomment-1425279454 #1728 #2087
We fixed some mount point checking by #1728 and #2087.
But when specifying `<bucket>/<directory>(/...)` as the mount point, and if that mount point directory does not exist, it is not an error.
This bug was reported by @ValentinNikin.
If this error does not occur, a directory that does not exist will be mounted as a mount point, and directories/files can be manipulated under that directory.
Therefore, this case has been corrected to be an error.
(This fix is same behavior as v1.91 and below)
_Even if the directory object as mount point does not exist, an error will not occur if an object containing that path exists._
_For example, if `<bucket>/<directory>/<file>` is created with a CLI tool, …
> Fixed to fail when the mount point directory is not existed

- README.md
#2109 
Based on #2109, the configuration was reexamined and corrected.
(I'm sorry for posting new PR, because #2109 has a lot of overlap with existing text, so I made a separate PR)
Thanks to @ryanufl.
> Updated README.md(feat #2109)

- src/fdcache_page.cpp
> Fix an error to calculate no data page bytes

- src/s3fs.cpp
#2149
This PR is additional logic against #2149.
#2149 has reported that `s3fs_release` is called without calling  `s3fs_flush` hook when the mount directory exporting via NFS.
To accommodate this, when `s3fs_release` is called, s3fs intentionally upload the file if it is still in a modified state.
No file uploads are performed in case of `s3fs_flush` hook is called, so this additional processing has no impact outside of NFS(for now).
Not only NFS, but if this case occurs in the future, this countermeasure will be effective.
There are no additional test cases as the tests for this issue cannot be implemented with test cases.
Instead, I tried not calling the `s3fs_flush` function and it worked. (results were fine)
> Corresponded to upload in case of calling release without flush

- src/s3fs.cpp
#2153
(Related: #2151 #2063 #1728 #1687 #1460 )
If user specifies a directory path for the mount point and user doesn't have access to the bucket top, the check is done in two steps(the bucket top and the directory).
(This is that @adamqqqplay pointed out by https://github.com/s3fs-fuse/s3fs-fuse/pull/2087#issuecomment-1537834762.)
Instead of this unnecessary two-step check, only the directory is checked when a directory path is specified.
I also reviewed and simplified the logic of the modified functions accordingly.
Changed to output the recommended option when an error(warning) occurs in the mount point check.
> Directly and simplify requests in mount point checks

- src/s3fs.cpp
#2159
Found mount point stat flags(`has_mp_stat` in `src/s3fs.cpp`) raced between threads.
Changed that flag to `class` so that access can be controlled exclusively.
> Fixed mount point stat flag to be thread safe

- ChangeLog
- configure.ac
> Update ChangeLog and configure.ac for 1.92

- test/integration-test-common.sh
n/a
For testing on macOS, we need to change two test settings:
`echo -e` should be changed to printf considering the case where macOS `echo` is different
The parameter `yes` is not accepted unless it is `y`.
The exact reason is still unknown, but since verifying of the SSL certificate resulted in an error, we will prepare a means to bypass this. (Specify `NO_CHECK_CERT=1` when executing `make check`)
> Fixed test setting for macOS

- .github/workflows/ci.yml
- Makefile.am
- src/addhead.cpp
- src/fdcache.cpp
> Address cppcheck 2.10 warnings

- src/fdcache_entity.cpp
- src/fdcache_entity.h
> Protect FdEntity::physical_fd with fdent_lock

- .github/workflows/linux-ci-helper.sh
Newer distros package this but some older ones do not.  Also remove stale Ubuntu 16.04 configuration.
> Upgrade to JDK 17

- .github/workflows/linux-ci-helper.sh
Also remove stale 18.04 configuration.
> Use JDK 17 for Ubuntu CI

- src/s3fs.cpp
#2203  #2188 
fuse_main will do fork to daemonize. if ThreadPool is created before this, worker thread will not be placed in child process.
Move ThreadPool Init to s3fs_init and destory to s3fs_destory.
#2188  may be also related to this.  When umount s3fs, ThreadPool::Destroy() will dereference some stale handler.
> fix streamuplod not working

- src/s3fs.cpp
Follows on to e650d8c55cc86d2bbaf2ff060761785e46e7a406.
> Guard filler calls with filled check

- ChangeLog
- configure.ac
> Update ChangeLog and configure.ac for 1.93

- src/curl.cpp
- src/fdcache_entity.cpp
- src/s3fs.cpp
- src/s3fs_util.cpp
- src/string_util.cpp
- src/string_util.h
- src/test_string_util.cpp
Remaining ones handle `timespec`.
> Convert most str callers to C++11 std::to_string

- .clang-tidy
- src/fdcache_fdinfo.cpp
- src/fdcache_untreated.cpp
This is more concise and sometimes more efficient.
> Use C++11 emplace where possible

- src/cache.cpp
- src/curl.cpp
- src/curl.h
- src/curl_util.h
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/fdcache_page.cpp
- src/fdcache_page.h
- src/mpu_util.cpp
- src/mpu_util.h
- src/s3fs.cpp
- src/s3fs_util.cpp
- src/s3fs_util.h
- src/test_page_list.cpp
- src/types.h
> Use C++ enum class for most enums

- src/s3fs.cpp
This removes many manual memory deallocations.
> Wrap `ps3fscred` with `std::unique_ptr`

- src/curl_util.cpp
- src/gnutls_auth.cpp
- src/nss_auth.cpp
- src/openssl_auth.cpp
- src/s3fs_auth.h
> Calculate MD5 without using a temporary file

- src/curl.cpp
- src/fdcache.cpp
- src/fdcache_entity.cpp
- test/cr_filename.cc
- test/mknod_test.cc
- test/truncate_read_file.cc
n/a
Fixed a build warning on some platforms.
However, the warning about `_FORTIFY_SOURCE` of `Rocky Linux 8/9` is not fixed.(leave as is)
> Fixed a warning for compiling C/C++ codes

- src/s3fs.cpp
This ensures that each option is only handled once.
> Tighten up CLI argument handling

- .github/workflows/ci.yml
- src/curl.cpp
- src/curl.h
- src/curl_multi.cpp
- src/curl_multi.h
- src/s3fs.cpp
> Return `std::unique_ptr` from `S3fsCurl` callbacks

- src/curl.cpp
- src/gnutls_auth.cpp
- src/nss_auth.cpp
- src/openssl_auth.cpp
- src/s3fs_auth.h
> Use `unique_ptr` in SSL functions

- src/addhead.cpp
- src/addhead.h
> Own values in `add_header`

- src/fdcache_entity.cpp
This reclaims storage after a failed MPU which caused OutOfMemory issues in #2291.
> Abort after failed MPU

- src/s3fs.cpp
When situations such as out of memory (OOM) occur, s3fs may receive a SIGKILL signal and exit before cleaning up the mountpoint. At this time, a stale mount point will be left, causing an error to be reported the next time s3fs is mounted: Transport endpoint is not connected.
This patch adds a feature: before s3fs mount, check if the stat information of the mountpoint returns ENOTCONN error, if so, it will execute the umount operation to unmount the stale mountpoint.
> s3fs: print unmounting hint when the mount point is stale 

- src/s3fs.cpp
- test/integration-test-main.sh
n/a
I noticed that the results of the `df` command are strange.
In macos, all block sizes and free block sizes were zero.
Also, the values seemed strange on Linux(using a 64-bit block size).
Revised the `statvfs` setting function(`s3fs_statvfs`) and fixed it so that if the `block_size` option is not specified, the maximum size is used.
> Fixed a bug with setting the statvfs value

- .github/workflows/ci.yml
- test/integration-test-main.sh
- test/test-utils.sh
This is a workaround for CI failures.
> Do not cache `stat` attributes

- src/s3fs.cpp
- src/s3fs_xml.cpp
- src/s3fs_xml.h
> Use `std::unique_ptr` in libxml functions

- src/curl.cpp
- src/fdcache.cpp
- src/fdcache_entity.cpp
- src/s3fs_util.cpp
- src/s3fs_util.h
> Use `std::unique_ptr` for fclose

- test/integration-test-main.sh
This reveals a situation where s3fs triggers an unexpected `EntityTooSmall` error.
> Add error checking to test_concurrent_writes

- src/fdcache.cpp
- src/fdcache_fdinfo.cpp
- src/fdcache_stat.cpp
- src/s3fs_util.h
References #2261.  Suggested by:
https://stackoverflow.com/questions/10270328/the-simplest-and-neatest-c11-scopeguard
> Add scope_guard for ad-hoc resource management

- src/fdcache_entity.cpp
- src/fdcache_entity.h
#2324 
Fixed ThreadSanitizer error reported in #2324.
Exclusive control of the pagelist member variable of the FdEntity class was insufficient.
> Fixed a bug in exclusive control of pagelist in FdEntity class

- test/integration-test-main.sh
#2320 
In the test code that was pointed out in #2320, there was still a problem with the `test_multipart_mix` test on macos12.
For macos, I was forcing the test file size to zero at the beginning of the `test_multipart_mix`, because this was to synchronize the free space area.
But it was detected that the free space may not be recovered immediately after deleting a file.
(Free space recovery may not be reflected in the results of the `statvfs` or `df` commands.)
I still don't know why this delay occurs.
The code trying to recover free space on the current disk wasn't good enough.
The `test_multipart_mix test` repeatedly creates files of several tens MB.
In rare cases, you will run out of disk space and the test will fail (on macos12).
To reliably reproduce this, you can run only the …
> Force disk free space recovery in test(for only macos)

- .github/workflows/ci.yml
- .github/workflows/linux-ci-helper.sh
> Upgrade CI to Alpine 3.18

- test/integration-test-main.sh
n/a
Fixed indentation in `integration-test-main.sh`.
(This is a cosmetic modification only)
> Fixed indent in integration-test-main.sh

- src/fdcache.cpp
- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
- src/s3fs.cpp
- src/s3fs_util.cpp
- src/string_util.cpp
- src/string_util.h
- src/test_curl_util.cpp
n/a
Fixed an error reported in the new version cppcheck 2.13.0 (recommended use of const declaration).
This fix will be merged immediately as it affects future fixes.
@gaul 
If you have any problems with the fix, please let me know.
> Fixed errors reported by cppcheck 2.13.0

- src/fdcache_fdinfo.cpp
- src/threadpoolman.cpp
- src/threadpoolman.h
This simplifies memory management.
> Convert `thpoolman_param` to value

- COMPILATION.md
#2421
Supplemented the explanation of the `Compilation on Linux` section of COMPILATION.md.
> Updated COMPILATION.md about compilation on linux

- src/curl.h
- src/fdcache.cpp
- src/fdcache.h
- src/s3fs.cpp
This is more idiomatic than by pointer.
> Pass `const std::string` by reference

- src/curl.cpp
- src/fdcache.cpp
- src/fdcache_entity.cpp
- src/fdcache_fdinfo.cpp
- src/s3fs.cpp
- src/s3fs_cred.cpp
- src/s3objlist.cpp
- src/types.h
- test/write_multiblock.cc
This is somewhat more clear and is declared `noexcept`.
> Prefer `std::string::clear` where possible

- src/curl.h
- src/curl_multi.cpp
- src/curl_multi.h
- src/gnutls_auth.cpp
- src/nss_auth.cpp
- src/openssl_auth.cpp
- src/sighandlers.cpp
- src/sighandlers.h
- src/threadpoolman.cpp
- src/threadpoolman.h
This has better cross-platform support and stronger type-safety.
> Convert `pthread_t` to C++11 `std::thread`

- src/s3fs.cpp
This is unnecessary since we moved from `pthread_mutex_t` to `std::atomic`.
> Simplify `has_mp_stat`

- src/fdcache_entity.cpp
- src/s3fs.cpp
> Fix minor issues when compiling with MSYS

- COMPILATION.md
- src/fdcache_entity.cpp
#2503 
This pull request updates the outdated compilation instructions for Windows + MSYS2 and fixes minor issues that cause compile errors.
> Fix Windows compilation

- test/integration-test-main.sh
#2418 #2205 #2198
Currently, we still unable to pass the tests on MacOS using macos-fuse-t.
After some investigation, I knew again that (as previously pointed out) our test cases were failing to update(or get) attributes such as ctime/mtime/atime.
_We have disabled caching of attributes in macos-fuse-t and the NFS it uses (noattrcache), but we've heard before that this doesn't stop the caching completely._
I tried waiting a few second to try to cache out, but the test pass/fail is not consistent.
In light of this, I have temporarily disabled the following tests on macos.
- test_update_directory_time_set_xattr
- test_update_directory_time_subdir
- test_update_parent_directory_time
Also, since the `test_truncate_cache` test generates an error `ls: fts_read: Input/output error`, I have …
> Modified and bypassed some MacOS tests

- .clang-tidy
- src/s3fs.cpp
- src/s3fs_cred.cpp
- src/s3fs_cred.h
- src/s3fs_xml.cpp
This fixes dangerous uses of `const_cast`.
> Enable cppcoreguidelines-pro-type-const-cast

- src/fdcache.cpp
- src/fdcache.h
- src/s3fs.cpp
( #2538 is weakly related issues )
The value of the `fake_diskfree` option was affected by the values ​​of the `free_space_ratio` and `ensure_diskfree` options, and in some cases it could not be set.
Originally, `fake_diskfree` was an option for debugging s3fs, setting a pseudo amount of free disk space, so it should not have been affected by the results of the check of the amount of free space required when s3fs was started.
If the amount of free space was below the minimum required for multipart uploads, etc., it was unable to be set, but we have changed it so that it can be set without being affected by this condition.
When making this correction, we also found an error in the mutual exclusion control (mutex), so we have corrected that at the same time.
> Fixed fake_diskfree option

- src/curl.cpp
- src/curl.h
`s3fs_sha256_hex_fd` returns an empty string when calculating the hash fails.
> Propoagate error state from `insertV4Headers`

- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
#2493 #2487 #254
This was modified to minimize exclusive control of the `PseudoFdInfo::upload_id` variable.
To achieve this, `IsUploadingHasLock()` is added, which does not hold the `IsUploading()` lock, to streamline the locking process on the caller side.
As a result of this efficiency, it is no longer necessary to lock before calling `ParallelMultipartUpload()`.
Please refer to the code for detailed differences.
> Fixed exclusive control of upload_id in PseudoFdInfo class

- src/addhead.cpp
- src/addhead.h
- src/cache.cpp
- src/curl.cpp
- src/curl_util.cpp
- src/fdcache.cpp
- src/fdcache.h
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
- src/fdcache_page.cpp
- src/fdcache_stat.cpp
- src/metaheader.cpp
- src/mpu_util.cpp
- src/s3fs.cpp
- src/s3fs_cred.cpp
- src/s3objlist.cpp
- src/string_util.cpp
- src/test_util.h
> Add missing string header

- src/curl_multi.cpp
#2535
When listing a directory that contains objects encrypted with KMS, the listing itself fails, and the following message appears:
```
$ ls
ls: reading directory .: Operation not permitted
```
This is because if KMS is not specified as SSE or a different KMS ID is specified, the HEAD request for the target object returns EPERM.
This phenomenon occurs because the fix in #2535 changed it to return a multipart request error code.
The fix itself is not wrong, but the problem was realized because the code before the fix did not handle EPERM exceptions.
The problem has been fixed by this PR.
However, since CI testing of SSE (including KMS) is not currently possible, no test code has been added.
(This needs to be considered in the future, but it may be difficult at the moment. It may be …
> Fixed readdir bug with objects receiving EPERM on HEAD request

- src/curl.cpp
- src/curl.h
- src/fdcache_page.cpp
- src/fdcache_page.h
- src/fdcache_untreated.cpp
- src/fdcache_untreated.h
- src/s3fs_cred.cpp
- src/s3fs_cred.h
- src/s3fs_logger.cpp
- src/s3fs_logger.h
Found via `cppcheck --inconclusive`.
> Make some methods const

- .github/workflows/ci.yml
- .github/workflows/linux-ci-helper.sh
Also specify architecture to allow future ARM64 CI to work.
> Pin AWS CLI to work around S3Proxy limitation

- src/s3fs_threadreqs.cpp
#2600 
Fixed memory leak found by valgrind in the code related to #2600.
> Fixed memory leak found by valgrind

- Makefile.am
- src/s3fs.cpp
- src/s3fs_cred.cpp
- test/map-subscript-read.py
These unintentionally mutate the map.  Script suggested by @danmar.
> Remove unneeded uses of `std::map::operator[]`

- .github/ISSUE_TEMPLATE/support_request.md
None
Since more and more users are using s3fs-fuse with backends other than AWS, it's a good idea to ask them what they are using, as it's not always clear.
We can't provide a whole list of providers (even if we could, tomorrow there could be new one), so I picked some of those I am aware of. Happy to change the list of examples to something else :-)
> Ask for the provider on support requests

- src/s3fs.cpp
#2246 #2304 #2423 #1964
Using S3 compatible providers, it seems that in some cases a HEAD request to a mount point will return a `200` error instead of a `404` error, even though the `"/"` object(path = `"//"`) doesn't exist.
In this case, the expected key name(ex. `x-amz-meta-*`) doesn't exist in the response header, but other keys exist and the response header is not empty.
With the current code, it works under the assumption that a `404` error or an empty response header will be returned, so the file listing commands(ex, `ls`) is failed by the mount point is not a directory.
To avoid this, I have changed the code to handle cases where the expected key name(e.g. `x-amz-meta-*`) doesn't exist in the response header in the same way as a `404` error.
> A case of HEAD response for mp is different on compatible storage

- .clang-tidy
- .github/workflows/ci.yml
- Makefile.am
- configure.ac
- src/Makefile.am
- src/cache.cpp
- src/curl_share.cpp
- src/curl_util.cpp
- src/fdcache_entity.cpp
- src/fdcache_page.cpp
- src/gnutls_auth.cpp
- src/nss_auth.cpp
- src/openssl_auth.cpp
- src/s3fs.cpp
- src/s3fs_cred.cpp
- src/s3fs_logger.cpp
- src/s3fs_util.cpp
- src/s3fs_util.h
- src/sighandlers.cpp
- src/sighandlers.h
- src/string_util.cpp
- src/test_string_util.cpp
- src/threadpoolman.cpp
- src/threadpoolman.h
- src/types.h
- test/Makefile.am
- test/write_multiblock.cc
This only has some minor additions of `std::make_unique`, digits separators, and more flexible `constexpr`.  References #2469.
> Require C++14

- src/fdcache.cpp
#2532
If the path element does not exist in fent, it may be because a cache directory has not been specified, or FdEntity::NoCacheLoadAndPost has already been called.
In these cases, the path element(=ent) has already been registered as a TempPath element from fent, so there is no need to register ent in the except_fent map.
(Processing with UpdateEntityToTempPath should not be performed.)
> Fixed a bug when changing fdentity to a temporary path

- src/curl.cpp
- src/fdcache_entity.cpp
- src/s3fs.cpp
- src/s3fs_threadreqs.cpp
Found via C++17 `[[nodiscard]]`.
> Improve error handling

- src/s3fs.cpp
#2683
In MacOS test, I found that `test_update_time_cp_p` often failed when the `nomultipart` option was specified.
_(This issue has only been confirmed on MacOS so far.)_
The reason for this is that when creating a new file, the pending Meta header information cannot be updated in time by `s3fs_release` processing.
Currently, `s3fs_release` uploads(flushes) the file contents and updates the pending Meta header information immediately afterwards, but there seems to be a case during this short period when file attributes are obtained.
The reason that `s3fs_release` performs Flush and Meta updates is because in the past there have been cases where `s3fs_release` was called without `s3fs_flush` being called. So that this processing needs to continue.
Also, since `fuse` does not wait for the …
> Fixed s3fs_flush to update pending meta for macos and nomultipart mode

- .github/workflows/ci.yml
- .github/workflows/linux-ci-helper.sh
- test/test-utils.sh
> Disable new S3 checksums for S3Proxy compatibility

- src/fdcache.cpp
- src/fdcache_entity.cpp
- src/s3fs.cpp
It's a stupid and small PR. But just got an error that said "no enough disk space" and wanted to fix it
> small spelling fix:  'no' to 'not'

- src/fdcache_entity.cpp
#2709 (#2710)
The CacheFileStatus file(cache file stat information file) used to be updated when the cache file was closed, but we've changed it so that it also updates when the file is flushed.
The cause of bug #2709 appears to be as follows, so this can be worked around.
First, when updating a file, closing it, and reading the file's stat information, s3fs expects flush->relase to be called from FUSE, followed by getattr.
However, as previously(old) discussed, FUSE starts the next process without waiting for release to complete.
Presumably, this is why, in the case of bug #2709, the commands were called in the order flush->getattr->relase.
As a result, we've changed the CacheFileStatus file update, which previously only occurred on release, to now also occur on flush.
> Changed to serialize CacheFileStat after flushing a file

- .github/workflows/ci.yml
- .github/workflows/linux-ci-helper.sh
Also remove outdated version checks.
> Only install binaries in static-checks task

- src/s3fs_util.cpp
#2721
Similar to the fix in #2721, we changed the code that currently uses free() to std::string, which can be replaced with it.
> Replaced the free call with std::string
