s3fs-fuse/s3fs-fuse

- doc/man/s3fs.1
Fixed issue#87.
Although there are descriptions of prefix option in the S3fs man page, this is the old description, description of the features that are not yet implemented.
In the future, because it is a description do not plan to be implemented, it has been deleted.
For more information, please look at the Issue # 87.
> Remove prefix option in s3fs man page - issue#87

- src/Makefile.am
- src/curl.cpp
- src/curl.h
- src/string_util.cpp
- src/string_util.h
- src/test_string_util.cpp
- src/test_util.h
Subsequent commits will use this infrastructure.  Also reparent
prepare_url which relies on unrelated bucket, foreground2, and
pathrequeststyle symbols.
> Add simple unit tests for trim functions

- src/curl.cpp
When initializing CURL handles, the is_dns_cache and is_ssl_session_cache flags were not checked properly. As a result, the handles were not set-up properly for DNS or SSL session caching.
> CURL handles not properly initialized to use DNS or SSL session caching.

- src/curl.h
- src/s3fs.cpp
Missing parameter to SetSignatureV4() call in the fallback code path
results in not actually falling back.
> Fallback to v2 signatures correctly.

- src/curl.cpp
Previously this failed with `SignatureDoesNotMatch` since the headers
included it but the signature did not.  Fixes #125.
> Include Content-Type in complete MPU V2 signature

- src/curl.cpp
Query parameters need a trailing = for V4 signatures.  Send correct
content-sha256 although Amazon does not seem to enforce this for
zero-length bodies.  Finally remove a stale comment.  Fixes #133.
> Correct V4 signature for initiate multipart upload

- test/integration-test-common.sh
- test/small-integration-test.sh
Use S3Proxy pid instead of self pid, ensure correct passwd
permissions, and use fusermount instead of umount so that non-root can
run tests.
> Small fixes to integration tests

- src/fdcache.cpp
- src/fdcache.h
- src/s3fs.cpp
Fixed following two bugs:
- Though use_cache option is off, s3fs try to use local file cache which is already closed.
- Regardless of the specified size, s3fs try to load the contents from specified start position till the end of file or the start position of next  loaded range.
These bugs is reported in issue #97.
> Fixed bugs, not turn use_cache off and ty to load to end - issue#97

- test/integration-test-common.sh
This allows `small-integration-test.sh` to pass.
> Use S3Proxy 1.4.0-SNAPSHOT

- src/string_util.cpp
s3fs could not list/remove a directory name which has ampersand(&), equal(=) on sigv4.
This patch is based by PR: URL-encode ampersand(#149) by @andrewgaul.
> Fixed url-encoding for ampersand etc on sigv4 - Improvement/#149

- src/curl.cpp
- src/s3fs.cpp
Buckets with mixed-case names can't be accessed with the virtual-hosted style API due to DNS limitations.  S3FS has an option for pathrequeststyle which is used for the URL, but it was not applied when building the endpoint passed through the Host header.  Fix this, and relax the validation on bucket names when using this style.
See: http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro
> Support buckets with mixed-case names

- .travis.yml
- test/integration-test-main.sh
Mail from the Travis team:
> Thanks for the email. I have set up s3fs-fuse/s3fs-fuse with our alpha testing stack which may allow you to use FUSE.
>
>To use it, add the following to your .travis.yml:
> dist: trusty
>
> Please keep in mind that the service may become unavailable without notice, and change details. We welcome your feedback as to what works and what does not with this setup.
> Run integration tests via Travis

- .travis.yml
The previous KVM infrastructure supported this but their new VMware
infrastructure does not.
> Disasble integration tests for Travis

- src/common.h
- src/common_auth.cpp
- src/s3fs.cpp
- src/s3fs_auth.h
- src/string_util.cpp
- src/string_util.h
Supports extended attributes(retry PR from #196).
s3fs saves extended attributes to object's header "x-amz-meta-xattr" which is formatted as encoded json.
```
x-amz-meta-xattr: url encoded string({"key":"base64(value)","key":"base64(value)",....})
```
This change solves issues #166 and #169.
> Supported extended attributes(retry)

- src/string_util.cpp
- test/integration-test-main.sh
This also encodes asterisk and tilde correctly when listing a file
with a V4 auth endpoint.  Also add tests for special characters
although s3proxy does not yet support V4 auth.
Fixes #188.  Fixes #194.
> Simplify URL encoding

- src/nss_auth.cpp
- src/openssl_auth.cpp
Destroy sha256ctx on all function returns. Otherwise memory leaks
every time a new file is created.
> Fix mem leak in openssl_auth.cpp:s3fs_sha256hexsum

- test/Makefile.am
During the packaging of s3fs-fuse in Arch Linux I noticed that *make install* installs rename_before_close under /test/rename_before_close. This PR just overrides the test Makefile's install, but I am not sure if this is the correct solution (I'm barely am auto tools expert)
> Override install, so that the make install does not install rename_before_close under /test

- src/curl.cpp
- src/fdcache.cpp
- src/s3fs.cpp
- src/s3fs_util.cpp
Fixed an uninitialized member, misordered NULL check, resource leak,
and unconsumed return value.
> Address Coverity errors

- src/common.h
- src/curl.h
- src/fdcache.h
- src/s3fs_util.h
This prevents implicit conversions.
> Annotate constructors as explicit

- src/s3fs_util.cpp
- src/s3fs_util.h
Previously `AutoLock::Lock` allowed subsequent callers to proceed
without the lock.  Further `is_locked` was not always protected by
`auto_mutex`.  Finally `AutoLock` eagerly released `auto_mutex` when
recursively unlocking.  s3fs does not need recursive locks so we
rewrite and simplify `AutoLock`.  Partially surfaced by Coverity.
> Rewrite AutoLock

- src/common_auth.cpp
- src/curl.cpp
- src/s3fs_auth.h
- src/s3fs_util.cpp
- test/small-integration-test.sh
This allows retries of multi-part uploads instead of discovering a
fatal error during complete multipart upload.  Also enable Content-MD5
for integration tests and refactor hexadecimal code.
> Enable Content-MD5 during multipart upload part

- src/curl.cpp
- src/s3fs.cpp
Also remove use of C++11 `std::map::at`.
> Elide duplicate lookups of std::map via iterators

- src/cache.cpp
Found via Coverity.  Regression from
dfa63345edb496986fecd70fca28ff8aba476f2a.
> Unlock during early return in TruncateCache

- Makefile.am
- autogen.sh
- configure.ac
- src/Makefile.am
- src/common.h
- src/s3fs.cpp
- src/s3fs_util.cpp
Added commit short hash in version string.
autogen.sh puts default_commit_hash in source root directory, and configure.ac makes config.h with it.
Because Makefile which is made by s3fs configure can build tar ball including source codes, it does not have .git directory.
But we should print commit hash base of source files which is made, when developer who has only tar ball builds binary.
So default_commit_hash file is included in tar ball, it can be printed.
> s3fs can print version with short commit hash - #228

- test/integration-test-main.sh
The `attr` package isn't installed by default on many distributions.
> Skip xattr tests if utilities are missing

- src/fdcache.cpp
- src/fdcache.h
- src/s3fs.cpp
- src/s3fs_util.cpp
- src/s3fs_util.h
Added checking cache direcotry's permission at s3fs starting.
Before, if the cache directory does not allow permission when s3fs using cache, s3fs run up but no error.
So this code change fixed it.
s3fs checks cache dir permission and if it is not allowed s3fs stop to start running.
> Added chacking cache dir perms at starting.

- README.md
received "should not have others permissions" when mounting
did chmod 640 and received "should not have group permissions"
used chmod 600 after creating the password file and had no problems
> Update README.md: Bugfix password file permissions errors

- README.md
As a novice Linux user, I didn't know I had to add a line into /etc/fstab for automatic mount upon boot. It took me some minutes to research and notice the right process (at first, I even entered s3fs#mybucket into the command line).
This change will (hopefully) save time to unseasoned users.
> Update README.md to better explain mount upon boot

- test/integration-test-common.sh
- test/small-integration-test.sh
Example command line:
S3FS_CREDENTIALS_FILE=keyfile \
TEST_BUCKET_1=somebucket \
S3PROXY_BINARY="" \
URL="http://s3.amazonaws.com" ./small-integration-test.sh
> Allow integration testing against Amazon S3

- README.md
Although the network device option (_netdev) may not work everywhere, the option likely does no harm on systems where it's not supported. By adding this option to the example, it will inform users of the necessity for post-network activation and how that might be accomplished.
> Added the _netdev option to the fstab example.

- test/small-integration-test.sh
localhost doesn't always resolve to 127.0.0.1 which can bash loop that waits for s3proxy to start will fail.
> Use 127.0.0.1 not localhost in s3proxy wait loop

- doc/man/s3fs.1
- src/cache.cpp
- src/common.h
- src/curl.cpp
- src/curl.h
- src/fdcache.cpp
- src/gnutls_auth.cpp
- src/nss_auth.cpp
- src/openssl_auth.cpp
- src/s3fs.cpp
- src/s3fs_util.cpp
Added new option "dbglevel" for debug message level.
Older version has only on/off for message, thus new one has critical/error/warning/info/debug mode.
The default level is critical.
And added signal handler for SIGUSR2, bumpup the debug level when s3fs catches this signal.
About message puts:
Older version could not put curl debug message and forground's message to syslog.
But new s3fs is able to put those.
If s3fs is run with "-f" option(means forground), all messages puts stdout and no message puts syslog.
The other without "-f"(means background), all messages puts syslog.
Then we can debug s3fs it runs background.(if you need to changeb debug level after starting s3fs, you can send SIGUSR2 to s3fs).
Then I hope this change helps us for debugging s3fs on background and at booting( …
> Changed and cleaned the logic for debug message.

- .travis.yml
This may allow s3fs to run its integration tests which require FUSE:
http://blog.travis-ci.com/2015-08-19-using-docker-on-travis-ci/
> Enable integration tests for Travis

- src/curl.cpp
Fixed a bug about issue #286
In the case of a copy of the object (header request), the contents of the SSE header should be inherited. (However, except for the SSE-C)
> Fixed a bug about head request(copy) for SSE - issue#286

- src/common.h
@ggtakec The new logging macros are very good, thank you!
This PR adds the source file so that logs look like:
```
[INF]       curl.cpp:DeleteRequest(2089): [tpath=/testdir2/]
```
Though maybe you want to keep the log lines as short as possible.
> Print source file in log messages

- src/s3fs.cpp
- test/integration-test-main.sh
Test to repro Issue #290 and a potential fix.
I am not happy with the fix.  O_TRUNC is common, and this adds an extra REST call for every open.
@ggtakec Is there a better way to mark the file as "dirty" so it will be uploaded when FUSE calls flush and release?
> Issue #290: File opened with O_TRUNC is not flushed

- src/curl.cpp
This issue has been mentioned at https://github.com/s3fs-fuse/s3fs-fuse/pull/207, but @jalessio did't pick all them up.
> Fix a small spelling issue.

- src/s3fs.cpp
Fixed for #290 and #291.
The changes is that s3fs calls only RowFlush when the file size is changed.
> File opened with O_TRUNC is not flushed - changed #291

- src/common.h
Without converting from s3fs log levels to syslog levels, the syslog
ends up being LOG_EMERG which can cause a broadcast message to all
users.
> Fix syslog level used by S3FS_PRN_EXIT()

- src/fdcache.cpp
- src/fdcache.h
- src/s3fs.cpp
s3fs had a bug(#299) that was s3fs could not set mtime to the file when the file was created with specifying mtime.
The bug occurred only if you started s3fs without cache files(not specified use_case option).
FUSE calls create/utimens/flush interface for s3fs when the file is created with mtime.
But utimens interface does not have file descriptor.
s3fs should search a fd from file path which is opened local file(cache).
But s3fs did not search it when s3fs was run without use_cache option.
This patch fixed it.
Be careful following:
If a file is created with mtime by some clients at same time on s3fs without use_cache, probably mtime for the file will be undefined.
This result is the same as the file content is undefined, s3fs is not guaranteed.
> Fixed a bug about mtime - #299

- src/fdcache.cpp
When the prefetch size is limited to the multipart size, the entire parallel logic of the read flow does not have an opportunity to use parallel get.
This fix increases the read performance significantly over our own s3 on-premise solution.
> Fix read concurrency to work in parallel count

- src/fdcache.cpp
This is additional modification for PR #306.
We need to change default value for ensure free disk space by that changes.
Then the default value is changed from S3fsCurl::GetMultipartSize() to S3fsCurl::GetMultipartSize() * S3fsCurl::GetMaxParallelCount().
> Changed ensure free disk space as additional change for #306

- src/fdcache.cpp
I compiled s3fs-fuse on my Mac and got the following errors:
fdcache.cpp:622:38: error: use of undeclared identifier 'PTHREAD_MUTEX_RECURSIVE_NP'
pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE_NP);   // recursive mutex
^
This pull request fixes this problem.
> Fix pthread portability problem

- src/s3fs.cpp
This is not an error condition, no need to log it as an error.  For instance, `touch some_empty_file; cat some_empty_file` will cause the log to be emitted.
> Change error log to debug log in s3fs_read()

- src/s3fs.cpp
- test/small-integration-test.sh
There are error conditions that don't get caught until s3fs_init() runs.  Currently, s3fs_init calls exit().  This leaves the mount point behind and results in "Transport endpoint not connected" errors.  
With this change, s3fs_init()  will exit the fuse loop cleanly.   This allows libfuse to close its session with the kernel module.   The mount point will be unmounted.
> Clean up mount point on errors in s3fs_init()

- src/s3fs.cpp
@ggtakec 
My proposed solution to #320 is for `s3fs_fsync` to delete the stat cache entry. Then, any subsequent operations will need to refresh the stat cache with a HEAD request. This will negatively impact performance in that it will cause more round trips. However, this is the simplest way to make `s3fs_fsync` correct. Someone who understands more about how the stat cache works could try to surgically update the stat cache to reflect the new file size in `s3fs_fsync`.
With this change, the test program from the #320 description outputs
```
/vagrant/testmount/testfile
stat size 12
```
> 320: delete stat cache entry in s3fs_fsync so st_size is refreshed

- src/curl.cpp
Previously s3fs omitted the bucket name when using path request style
causing SignatureDoesNotMatch with v4 signatures.
> Fix v4 signature with use_path_request_style

- src/curl.h
- src/s3fs.cpp
Found with:
-Wc++11-extensions
-Wc++11-extra-semi
-Wmissing-variable-declarations
-Wundef
> Address various clang warnings

- src/curl.cpp
This resolves issues when using v4 signing with path-style requests.
> Bucket host should include port and not path

- src/curl.cpp
When the iam_role option is specified and the getting metadata from 169.254.169.254 at booting is failed, s3fs could not retry to connect.
This patch is for fixing this bug.
> Fixed a bug about IAMCRED type could not be retried.

- src/cache.cpp
- src/cache.h
Chaned the cache out logic for stat information for #340.
The logic before the change cached out the stat information which had passed expire time + 1 second.
And s3fs removed only one entry at each cache-out.
s3fs update the time for cache-in when the cache is hit every time.
So if cache datas are continuous access, s3fs did not discard the cache.
This logic was very bad for a case of listing many object at one time.
Thus I changed this logic about that s3fs uses unixtime to struct timespec for cache-in time and removes caches if the cache count is over limit.
As a result of this change, it was able to reduce the amount of memory s3fs to use.
> Changed cache out logic for stat - #340

- src/s3fs.cpp
For ListBucketResult on an empty directory, AWS S3 and S3Proxy 1.4
differ.  AWS will match the directory name, S3Proxy does not.
Changing max-keys=1 to max-keys-2 works for both implementations.
append_objects_from_xml() will swallow the directory key.  The log
level of this message is changed from ERROR to DBG.
Fixes #345
> Fix empty directory check against AWS S3

- test/integration-test-common.sh
- test/integration-test-main.sh
- test/small-integration-test.sh
- test/test-utils.sh
Details in README.md and s3fs-integration-test-common.sh
Factor out s3fs-fuse and s3proxy start/stop.  The plan is to make it easier to
add test suites besides small-integration-test.sh that can test with various
s3fs options.
Each test run starts in a uniquely named at the top of the bucket.  This allows
multiple runs against persistent storage without worrying about cleaning
up in error conditions that leave artifiacts behind.
Tests continues if a test case fails.
Results are summarized at the end of the test run
Environment variable to control debug level of s3fs-fuse
Environment variable to enable public bucket (makes it easier to poke
around with tools like curl)
Environment variable to start s3fs-fuse under valgrind
Environment variable that casues script sets up s3fs-fuse and then …
> Integration test summary, continue on error

- src/fdcache.cpp
- src/fdcache.h
- src/s3fs.cpp
For fixing #337
When del_cache option is specified, s3fs remove file cache directory only.
But this fix is removing stat cache directory.
And changed timing for removing those directories at s3fs_init().
> Remove stat file cache dir if specified del_cache - #337

- configure.ac
- src/cache.cpp
There is not clock_gettime function on OSX.
> Fixed codes about clock_gettime for osx

- src/cache.cpp
There is a problem with the #355, it has been modified again.
> Fixed codes about clock_gettime for osx(2)

- configure.ac
On Debian 7.8, AC_CHECK_FUNCS([glock_gettime]) returns false without adding rt to the search libs.
> Fix clock_gettime autotools detection on Linux

- src/cache.cpp
- src/cache.h
- src/s3fs.cpp
Fixed https://github.com/s3fs-fuse/s3fs-fuse/issues/370.
When copying a file(object), FUSE will call continuously s3fs_write evey 4KB(depending on the OS).
At this time FUSE will confirm the xattr of security.capability, if it is deemed necessary.
As a result, s3fs_getxattr will also be called in 64KB units.
And the HEAD request is sent to the S3 by evey s3fs_getxattr call, when s3fs is gave max_stat_cache_size=0 option or s3fs cached out the stats data for the file.
This causes a decrease in performance.
For solving this problem, s3fs is changed that the stats information for the file is always cached while the file is open.
After closing the file, the cache life depends on the setting of the max_stat_cache_size and it will be cleared.
> Always set stats cache for opened file

- src/curl.cpp
- test/integration-test-main.sh
The following steps report error, which should NOT:
```bash
ubuntu@ip-172-31-29-108:~/s3fs-fuse$ touch /tmp/s3fs/a
ubuntu@ip-172-31-29-108:~/s3fs-fuse$ ll /tmp/s3fs/a
-rw-rw-r-- 1 ubuntu ubuntu 0 Apr 22 06:48 /tmp/s3fs/a
ubuntu@ip-172-31-29-108:~/s3fs-fuse$ truncate /tmp/s3fs/a -s 1024
truncate: failed to truncate ‘/tmp/s3fs/a’ at 1024 bytes: Operation not permitted
```
This patch fixes this bug.
> Fix a bug of truncating empty file

- src/addhead.cpp
Allow duplicate key in the ahbe_conf file.
This makes it possible to describe the multiple HTTP header for one extension.
I have been changed codes, because it is determined that there is a user needs as #386.
> Allow duplicate key in ahbe_conf - #386

- src/cache.cpp
If you specify a stat_cache_expire option, s3fs are compared in CLOCK_MONOTONIC_COARSE and time () function, all has become a cash-out.  
This is a modification of the bug had been reported to the #382.
> Fixed a bug about stat_cache_expire - #382

- src/s3fs.cpp
If user specifies iam_role=auto (or just iam_role), credentials will not
be loaded during early phase, so skip credential checks there.
Bug: https://github.com/s3fs-fuse/s3fs-fuse/issues/419
Signed-off-by: Nathaniel W. Turner <nate@houseofnate.net>
> Skip early credential checks when iam_role=auto

- ChangeLog
Because there was an extra line break
> Updated to correct ChangeLog

- src/curl.cpp
Changed S3fsCurl::RequestPerform() method.  
All error result case returned curl_easy_perform() returns error code instead of process exit.  
Those are CURLE_SSL_CACERT / CURLE_PEER_FAILED_VERIFICATION and unknown(default) cases.  
This changes are a fix for #437.
> Handled all curl error without exiting process - #437

- src/cache.cpp
As discussed in #340 - I've run this for a few days in production, and under an intense test load and it has resolved valgrind reported leaks, allocated from AddStat.
> Fix for leaks during stat cache entry expiry / truncation (#340)

- src/fdcache.cpp
- src/fdcache.h
- src/s3fs_util.cpp
- src/s3fs_util.h
This PR is for #428.
If the cache file is removed during upload/download a object, s3fs uploads/downloads the object which has some null bytes.
This patch changes a logic about upload/download when using cache files.
This new logic uses mirror file which is (hard) linked the cache file, then if the cache file is removed, s3fs can continue to upload/download a object without wrong data.
> Add mirror file logic for removing cache file

- src/s3fs.cpp
- test/integration-test-main.sh
This is a bug fix related to the #460.
If s3fs did not support xattrs, s3fs cound not copy file mode from original file when using "cp -p".
Thus this patch fixed this problem.
But now s3fs supports xattrs, then this patch does not effect to solve issue #460.
> Fixed a bug about could not copy file mode from org file

- configure.ac
- src/common.h
- src/s3fs.cpp
Fixed for #476
Supported the header file for extended attributes on each OS(file type)
> OS-specific correspondence of the extended attribute header

- src/s3fs.cpp
If the original file path has white characters in symbolic link file, s3fs fails read link.
So that, trim original file path at reading/writing from link file.
> Trim symbolic link original path in file.

- src/s3fs_util.cpp
s3fs has changed the Content-Length(and Last-Modified) header to search not case-sensitive.
This change corresponds to the #480.
> Fixed searching Content-Length without case sensitive - #480

- src/common.h
- src/s3fs_util.cpp
The headers_t map has changed to use compare function for nocase string comparing.
This is following up for #488 PR.
> Changed headers_t map using nocase compare function - #488

- src/curl.cpp
Multipart copy is broken it seems and keeps returning invalid signature. I discovered it is due to missing request_url in the `insertV4Headers` call. Once tweaked, it works perfectly.
Here is what I was experiencing before applying this PR:
```
Nov  4 09:09:27 app02 s3fs[29997]: > PUT /path/to.file.gz?partNumber=1&uploadId=UPLOADIDSTRING HTTP/1.1
Nov  4 09:09:27 app02 s3fs[29997]: > User-Agent: s3fs/1.80 (commit hash unknown; OpenSSL)
Nov  4 09:09:27 app02 s3fs[29997]: > Accept: */*
Nov  4 09:09:27 app02 s3fs[29997]: > Authorization: AWS4-HMAC-SHA256 Credential=CREDENTIALSTRING, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-range;x-amz-date, Signature=SIGNATURESTRING
Nov  4 09:09:27 app02 s3fs[29997]: > Content-Type: application/x-gzip
Nov  4 …
```
> Fix invalid V4 signature on multipart copy requests

- src/curl.cpp
- test/integration-test-common.sh
- test/integration-test-main.sh
- test/s3proxy.conf
Enabled previously broken tests and test with default v4 signer.
Release notes:
https://github.com/andrewgaul/s3proxy/releases/tag/s3proxy-1.5.0
https://github.com/andrewgaul/s3proxy/releases/tag/s3proxy-1.5.1
> Upgrade to S3Proxy 1.5.1

- .travis.yml
- src/fdcache.cpp
- test/integration-test-common.sh
When s3fs performs continuous upload, part of the file can not be uploaded normally and some part of the file was written as a NULL code.
(See the issue of #435, and there are other issues related to this bug.)
After fixing this bug to another branch, it seems to be stable, so I try to merge it into the master branch.
> Fixed a bug about uploading NULL to some part of the file contents

- src/cache.cpp
For #468, changed clock_gettime static function name to s3fs_clock_gettime, because this function name is conflicted on homebrew.
Then this function name do not need same name in library, so it should be changed.
> Changed clock_gettime func to s3fs_clock_gettime for homebrew - #468

- doc/man/s3fs.1
- src/cache.cpp
- src/cache.h
- src/s3fs.cpp
#523
s3fs updated the cached time of stat information to the time when it was accessed to that cache.
This effectively reduces the number of requests for continuous cache access.
However, if the bucket is mounted with multiple s3fs, it becomes a problem like #523.
In this renovation, the expiration date specified by "stat_cache_expire" shall be the time since stat information was cached.
And I added an option called "**stat_cache_interval_expire**" to update the cached time when accessed stat information for compatibility.
> Changed base cached time of stat_cache_expire option - #523

- src/s3fs.cpp
n/a
In foreground mode, SSL library initialization function s3fs_init_global_ssl is called twice at startup.
We are deleting useless calls.
> Fixed double initialization of SSL library at foreground

- doc/man/s3fs.1
Ordinary user has no permissions to use umount command, so it is good to add fuse unmount instruction in man file.
> Add umount instruction for unplivileged user.

- doc/man/s3fs.1
- src/fdcache.cpp
- src/fdcache.h
- src/s3fs.cpp
- src/s3fs_util.cpp
- src/s3fs_util.h
#347 #351 #538
About #351 for fixed #347, I changed to check the existence of the cache directory at all times.
However, this causes problems at OS startup like #538
Ultimately, if there is no cache directory as before, s3fs will automatically create it.
And, the check_cache_dir_exist option is added, the cache directory is checked at startup when this option is given.
> Added check_cache_dir_exist option(refixed #347) - #538

- src/cache.cpp
#549
There was a problem with the cache out logic of the stat cache.
This may possibly be the cause of # 549
> Fixed a bug in logic about truncating stat cache

- src/curl.cpp
- src/curl.h
Currently, s3fs uses a multicurl handle to use parallel connections to s3.
The connections are indeed parallel, but are handled by a single CPU thread.
This creates a CPU bottleneck when reaching high throughput with TLS (HTTPS) connections.
To solve this issue, I propose a change to the S3fsMultiCurl class to use foreground pthreads instead of a multicurl handle.
> switch S3fsMultiCurl to use foreground threads

- src/fdcache.cpp
- src/fdcache.h
- src/s3fs_util.cpp
- src/s3fs_util.h
When running out of disk space when using a cache, try to perform a global cache cleanup.
E.g. instead of cleaning up only the cache for the CURRENT file descriptor, go over all cache files an try to clean them up.
This will proof useful when the disk is mostly occupied by big unused cache files.
> cleanup cache directory when running out of disk space

- src/curl.cpp
The AWSv4 signature function signs all request headers, including those with an empty string value.
Those headers with empty value are later discarded by libcurl (i.e. they are not sent to the s3 server).
This lead to a situation of a bad signature.
For example, this invalid request was generated:
POST /ozeri/rand10m5?uploads= HTTP/1.1
host: <...>
User-Agent: s3fs/1.80 (commit hash unknown; OpenSSL)
Authorization: AWS4-HMAC-SHA256 Credential=<...>, SignedHeaders=accept;content-length;content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date;x-amz-meta-gid;x-amz-meta-mode;x-amz-meta-mtime;x-amz-meta-uid, Signature=<...>
Content-Type: application/octet-stream
x-amz-acl: private
x-amz-content-sha256: <...>
x-amz-date: <...>
x-amz-meta-gid: 0
x-amz-meta-mode: 33188
x-amz-meta-mtime: <...> …
> don't sign empty headers (as they are discarded by libcurl)

- src/curl.cpp
- src/curl.h
The multipart upload function which is called when running out of disk space is broken.
The etag for the parts are not stored as necessary to complete the upload.
I refactored the multipart upload success callback to be called on this case as well.
> fix multipart upload handling without cache

- doc/man/s3fs.1
- src/common.h
- src/s3fs.cpp
- src/s3fs_util.cpp
n/a
(This is a request by direct mail.)
If the object in S3 bucket was uploaded directly from the AWS S3 console or another tool incompatible with s3fs, it may not have the x-amz-meta-mode header required by s3fs or it's content type is not application/x-directory.
In this case, the object(file or directory) permission mode is 0, and even reading it can not.
In other words, if the object does not have the minimum necessary header, s3fs makes a strict judgment and the object is not authorized to operate.
However, with many users this mode=0 is confusing, and in the case of directories it is a problem that it can not be judged as a directory in particular.
Even if the x-amz-meta-mode does not exist or it can not be judged strictly as a directory, s3fs can predict that it is a directory and …
> Added option for complementing lack of stat mode

- src/s3fs.cpp
#475
Enhanced bucket/path parameter check, if the parameter has "://" string, it will be error and not start to run s3fs.
If user specify "s3://" prefix for bucket name and it matches "bucketname:/path" format, user can not know the reason that is wrong bucket name, because s3fs reports "do not access your bucket".
So, s3fs checks bucket name and path for finding wrong prefix at first.
> Enhanced bucket/path parameter check

- src/curl.cpp
#535
Added simple response body check when getting 200 OK status by Put Head Request. 
This check is only single request(except multi head request).
> Check errors returned in 200 OK responses for put header request

- doc/man/s3fs.1
#575
The size limit description of the man page remained old, so I updated it.
> Updated limit object size in s3fs man page

- src/addhead.cpp
- src/addhead.h
- src/cache.cpp
- src/cache.h
- src/common.h
- src/common_auth.cpp
- src/curl.cpp
- src/curl.h
- src/fdcache.cpp
- src/fdcache.h
- src/gnutls_auth.cpp
- src/nss_auth.cpp
- src/openssl_auth.cpp
- src/s3fs.cpp
- src/s3fs.h
- src/s3fs_auth.h
- src/s3fs_util.cpp
- src/s3fs_util.h
- src/string_util.cpp
- src/string_util.h
- src/test_string_util.cpp
- src/test_util.h
#423
Fixed the format of the year part of Copyright in the source code pointed out at version 1.80.
> Changed copyright year format for debian pkg

- src/s3fs.cpp
This protects private data when used over the public Internet.  Users
can opt-in to unencrypted HTTP if they need additional performance on
a local network.  Fixes #282.
> Default transport to HTTPS

- src/s3fs_util.cpp
(Same as #605 with different branch)
On some of my systems users cannot access directories, which they have group membership to access.
One if the groups in particular is quite large, with about 50 members, but I've also got ~150 groups and users in total.
I've traced the issue back to the getgrgid_r call within is_uid_include_group failing with ERANGE, indicating the buffer is too small.
The patch in this pull request solves the problem by expanding the buffer and trying again until it works, but there might be a better way.
> Group permission checks sometimes fail with large number of groups

- src/s3fs.cpp
When the s3fs_chown_nocopy function is used, performing chown with only owner or group loses the unspecified parameter.
This PR fills that data in from stbuf, the same as s3fs_chown already does.
I've also experimented with removing the nearby getpwuid/getgrgid calls, because I can't figure out what they're for, it seems like a no-op. If it needs to stay let me know.
> Fix chown_nocopy losing existing uid/gid if unspecified

- src/cache.cpp
#600
Sierra has clock_gettime function, but s3fs code does not convert first argument(cast).
Then it is an error as wrong variable type .
So it is cast to clockid_t.
> Fixed clock_gettime build failure on macOS 10.12 Sierra - #600

- src/fdcache.cpp
- src/fdcache.h
There were multiple problems with the FdManager::GetFreeDiskSpace() function
on macOS:
1) When calling statvfs(), f_frsize should be used instead of f_bsize when converting available blocks to bytes.  This was causing the free space calculation to be incorrect.
2) On macOS, fsblkcnt_t is a 32-bit integer.  Thus, when calculating available disk space, there were frequently overflows.  This caused s3fs to incorrectly determine that the cache location was out of space in the middle of a transfer which caused uploads to fail.  Changing this to a uint64_t resolves the problem.
Resolves issue #634.
> Fix intermittent upload failures on macOS

- test/integration-test-common.sh
Also remove log prefixing since newer S3Proxy versions do this
already.
> Simplify S3Proxy PID handling

- src/s3fs.cpp
none
Seems informative message to me, not critical. Also quite annoying to see it, when reviewing systemd journal.
> Fix s3fs_init message

- src/common.h
- src/s3fs.cpp
#652
I noticed that there was a problem with fixing #652.
s3fs init message was always output when CRIT level.
However, if we changed to the INFO level for this message, it will not be output unless the s3fs log output level specification is less than INFO.
The init message level should be INFO, but it should be outputted independently of the log output level of s3fs.
I fixed this again.
> Refixed s3fs_init message(ref #652)

- .travis.yml
#667
Removed lines about before_install(gpg2 and rvm commands)
> Changed .travis.yml for fixing not found gpg2 on osx

- src/curl.cpp
- src/curl.h
I refactored common authentication code (V2 & V4) to a single function called insertAuthHeaders.
This new function will allow to easily add support for other authentication mechanisms (such as Google Cloud Storage OAuth 2.0, or the IBM IAM Authentication - which I'm planning to add support to, once this PR is merged).
I've tested  this PR using the integration tests, both in V4 & V2 modes - all seem to pass.
> auth headers insertion refactoring

- src/common.h
- src/curl.cpp
- src/curl.h
- src/fdcache.cpp
- src/gnutls_auth.cpp
- src/s3fs.cpp
- src/s3fs.h
- src/string_util.h
This provides type-safety and avoids token expansion side effects.
> Reduce use of preprocessor

- src/curl.cpp
Fixes regression from 0418e53b3c8248f4b03f3b8f47b4b91203e699a5.
> Correct signedness warning

- src/fdcache.cpp
The parallel download request condition needs a small fix.
The parallel upload request condition is correct
(see: https://github.com/s3fs-fuse/s3fs-fuse/blob/566961c7a5db78066bdceefd385acbb964feb1c4/src/fdcache.cpp#L1505)
> fix condition for parallel download

- src/fdcache.cpp
After few hours of intensive use I got a crash. See backtrace below. This is due to the fact that the file descriptor can change between the sanity check and the real use of it.
#0  0x00000035f0c325e5 in raise () from /lib64/libc.so.6
#1  0x00000035f0c33dc5 in abort () from /lib64/libc.so.6
#2  0x00000035f0c704f7 in __libc_message () from /lib64/libc.so.6
#3  0x00000035f0c75f3e in malloc_printerr () from /lib64/libc.so.6
#4  0x00000035f0c78d8d in _int_free () from /lib64/libc.so.6
#5  0x00000035f409d565 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib64/libstdc++.so.6
#6  0x000000000046328f in operator= (this=0x7f2ce8035030) at …
> Fixing race condition in FdEntity::GetStats

- ChangeLog
- configure.ac
#689
It is the final modification of version 1.83.
The version number in ChangeLog and configure.ac has been incremented.
> Updated ChangeLog and configure.ac for release 1.83

- Makefile.am
- src/addhead.cpp
- src/curl.cpp
- src/fdcache.cpp
- src/gnutls_auth.cpp
- src/nss_auth.cpp
- src/s3fs.cpp
- src/string_util.cpp
#713
The version of cppcheck prepared by TravisCI differs between OSX and ubuntu.
OSX was 1.82, and the behavior of unusedFunction was different from 1.63.
On OSX, exitcode = 0 does not become 0 even if suppressing unusedFunction error using suppress option.
Since it can not be helped, I adjust the option so as not to check unusedFunction.
In addition, we modified the code for the variableScope error and deleted it from the suppress option.
> Fixed Travis CI error about cppcheck - #713

- .gitattributes
- configure.ac
Doesn't build on Cygwin
`libfuse` is not available on Windows.
When you try to compile `libfuse` on Windows the result is:
```
Error encountered: libfuse does not support Windows.
Take a look at http://www.secfs.net/winfsp/ instead
```
WinFSP provides an compatibility layer to FUSE using version number `2.8`, this is why I added a specific target configuration for Cygwin to `configure.ac`. Also, to use the non-standard calls used in the `s3fs` code, the `_GNU_SOURCE` flag is required.
Last change is the addition of a `.gitattributes` file. Indeed, `autogen.sh` must be in Unix format to be executed and when using Windows the file is changed to Windows line endings. hence the addition.
Next step is to have a working example for it. I wasn't able to mount a S3 bucket.
I started a discussion …
> Added Cygwin build options

- doc/man/s3fs.1
- src/fdcache.cpp
- src/fdcache.h
- src/s3fs.cpp
- src/s3fs_util.cpp
This PR includes the following changes:
- Atomically reserving disk space instead of calling IsSafeDiskSpace before Load, and freeing reserved disk-space when Load completes. This is to avoid a race where two or more threads think they have enough disk space to download, but they don't account for each other. If not enough space exists on disk to reserve, then two methods are tried to free up disk space: freeing disk space from the current fd, followed by trying other fd's (when using -o use_cache).
- Changed EnsureDiskFree setting to be 0 for default (since we have the disk space reservation, we no longer need to default it to MaxParallelCount * MultipartSize).
- Added some debug printings to cache cleanup methods.
- Changed cache cleanup method to skip opened fd's (i.e. to clean from …
> add disk space reservation

- src/fdcache.cpp
- src/fdcache.h
I found that when using use_cache and opening multiple files in parallel, you get a lock bottleneck on fd_manager_lock.
To improve the performance, I made two changes:
1. Change OpenMirrorFile to use urandom instead of time(), in order to avoid parallel threads creating mirror files of the same name. Additionally, instead of calling time() in a for loop (time changes only every 1 second), just increment the seed.
2. In FdManager::Open, release fd_manager_lock after fdent is found/created.
Prior to this PR, parallel open requests were served sequentially, with a 1s delay between each (because of the mirror file creation loop being stuck).
With this PR, this delays were gone, and parallel open are returning immediately.
> reduce lock contention on file open

- src/curl.cpp
We don't need to return -EIO on MultiRequest when one or more curl threads returns an error.
The error path is handled by MultiRead which uses retries.
> don't fail multirequest on single thread error

- src/s3fs.cpp
#732 
Error message is not very helpful in determining the cause of the error. Improved message by introducing clarity on the problem and what the problem's source is.
> More useful error message for dupe entries in passwd file

- src/curl.cpp
I encountered this re-occurring issue, popping once every few days of running an s3fs mountpoint:
A curl request failed with a readwrite_timeout.
S3fs retries the request -> gets curl error 35 CURLE_SSL_CONNECT_ERROR.
The same request is retried again -> same error CURLE_SSL_CONNECT_ERROR.
While the retries of this request fail, other requests do complete successfully.
This lead me to think that the CURL handle of the retry connection is re-using state (specifically SSL state) from the old (failing) connection.
I made this PR to cleanup the SSL state (or any other state) of the retry handle, by creating a fresh handle, with curl caches disabled (only for the retry request).
I tested with this patch and found that the issue is resolved.
@ggtakec would appreciate your approval.
> cleanup curl handle state on retries

- src/s3fs_util.cpp
I came across the following error:
s3fs[11960]: [/mys3fsmount]fdcache.cpp:MakeCachePath(1876): failed to create dir((null)) by errno(17).
s3fs[11960]: [/mys3fsmount]fdcache.cpp:OpenMirrorFile(752): could not make bup cache directory path or create it.
s3fs[11960]: [/mys3fsmount]fdcache.cpp:Open(890): failed to open mirror file linked cache file(/s3fscache/ozeri/testfile).
I'm guessing it happened because of a race between two threads that tried to create the ".mirror" directory inside the cache.
To fix it, I added a check to ignore the case where the directory already exists.
> don't fail mkdir when directory exists

- src/s3fs.cpp
the original implementation in get_base_exp() depends on the order of xml return from the server.
patriotically, when listing a directory with sub directory(s), the xml document response contains more than 2 <Prefix> nodes(some of them are in <CommonPrefixes> node).
the source code arbitrarily select the first one in the documents (nodes->nodeTab[0]->xmlChildrenNode), which is OK for aws.
however, some s3 compatible service return the list-bucket result in different order, leading the s3fs to a wrong behavior
> fix xpath selector in bucket listing

- src/s3fs.cpp
When the URL is specified without protocol detail like `s3-api.us-geo.objectstorage.softlayer.net`,
the `s3fs` process is silently terminating with exit code zero.
The code change validate the URL and throws error message if `http` / `https` is missing.
> Validate the URL format for http/https

- src/curl.cpp
#748
This is a fix as a precautionary measure for resetting curl handle, it does not change something.
> Added reset curl handle when returning to handle pool

- README.md
- src/cache.cpp
- src/s3fs.cpp
This PR includes 3 changes to default s3fs configuration, in order to boost performance:
1. Change readme to recommened OpenSSL instead of gnuTLS (I tested openssl to be much faster)
2. Increase the stat cache size from 1000 to 100000. This greatly reduces the number of HEAD requests made by s3fs, as many use-cases list buckets of more than 1000 objects.
Each entry in the cache takes upto 0.5KB, so a full cache will take upto 0.5KB*100000 = 50MB of memory.
3. set FUSE sync_read by default (instead of the default async_read).
This can increase performance as async_read causes the creation of background threads that can create a bottleneck when reaching FUSE's max_background. On the other hand, you don't get the benefit when using async_read since s3fs allows only a single thread to read …
> Optimize defaults

- src/curl.cpp
I noticed the following warning message repeatedly on my logs:
`s3fs.cpp:s3fs_destroy(3438): Could not release curl library`
I debugged it, and found that the reason is a failure in `CURLSHE_OK != curl_share_cleanup(S3fsCurl::hCurlShare)` inside `S3fsCurl::DestroyShareCurl`.
The libcurl [documentation](https://linux.die.net/man/3/libcurl-share) of curl shares says that you need to:
```
When you're done using the share, make sure that no easy handle is still using it, and call curl_share_cleanup(3) on the handle.
```
Currently, s3fs clean up curl handles AFTER the share is destroyed.
This PR fixes this problem, by switching the cleanup of curl handles to be BEFORE the cleanup of the curl share.
I verified that after this fix, the error mentioned above disappears.
> cleanup curl handles before curl share

- src/curl.cpp
- src/curl.h
- src/s3fs.cpp
I encountered a few false warning messages (when setting dbglevel=warn):
1. `s3fs.cpp:append_objects_from_xml_ex(2575): contents_xp->nodesetval is empty.
this happens whenever the XML listing does not contain either <Contents> or <CommonPrefixes>, which is very very common.
2. `curl.cpp:MultiRead(3956): failed a request(404: ...` and `curl.cpp:MultiPerform(3928): thread failed - rc(-2)`
These warnings appear whenever we get a 404 response on a HEAD request sent as part of `readdir_multi_head`. This can happen if the object is not yet updated in the bucket listing, or if the object is a CommonPrefix.
This PR removes those false warnings.
> Remove false multihead warnings

- src/curl.cpp
- src/curl.h
- src/gnutls_auth.cpp
- src/nss_auth.cpp
- src/s3fs.cpp
#748 #340
Fixed the memory leak about #748(and #340)
- Reviewed the processing such as destruction related to CurlHandlerPool.
- Changed the initialization processing of the NSS library.
- Changed to execute the CURL library initialization and destruction processing mainly.  
There was a call to CURL for bucket check before calling fuse_main, then initialization/destruction of CURL in s3fs_init/s3fs_destroy was inappropriate.
> Fixed memory leak

- src/curl.cpp
n/a
On OSX, build is failed by following a error by cppcheck, then it has been fixed.
```
[src/curl.cpp:1639] -> [src/curl.cpp:1643]: (warning) Either the condition 'eol!=NULL' is redundant or there is overflow in pointer subtraction.
```
> Fixed an error by cppcheck on OSX

- src/gnutls_auth.cpp
Without this change, the following warning appears in the syslog/journal
during startup:
Libgcrypt warning: missing initialization - please fix the application
From the [documentation][0]:
> The function `gcry_check_version` initializes some subsystems used by
> Libgcrypt and must be invoked before any other function in the
> library.
Fixes #524, which says:
> gnutls is initialized by gnutls_global_init() function and
> gcry_check_version() function for initializing libgcry is called from
> this gnutls_global_init().
I checked the gnutls source and it hasn't contained a call to
gcry_check_version() since the libgcrypt backend was removed in 2011
(commit 8116cdc8f131edd586dad3128ae35dd744cfc32f). In any case, the
gcry_check_version() documentation continues:
> It is important that these …
> gnutls_auth: initialize libgcrypt

- src/curl.cpp
If there are Issues related to this PullRequest, please list it.
Currently S3FS fuse is not logging any message for 4xx and 5xx HTTP response codes.  
The code change enable the logging for 4xx and 5xx  codes.
> Log messages for 5xx and 4xx HTTP response code

- README.md
Request from @gaul at #785.
Add the instructions to install both official packages at SUSE and openSUSE. Advanced instructions are now also available at the [Wiki](https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes#suse-and-opensuse).
Since I am adding a new distribution, I also adjusted tabulation to make the file more readable (see the ```README.md``` file on [view mode](https://github.com/juliogonzalez/s3fs-fuse/blob/96779eb2ebda9d6773bffa4c80e62e19b955d3e0/README.md).
> Instructions for SUSE and openSUSE prebuilt packages

- README.md
this is relevant because Backblaze B2 is fairly popular and thus mentioning it helps s3fs
> add Backblaze B2

- README.md
https://github.com/s3fs-fuse/s3fs-fuse/issues/691
Updated language to eliminate confusion surrounding the credentials to use in the password file.
> #691: Made instructions for creating password file more obvious.

- README.md
- #785
- https://bugzilla.redhat.com/show_bug.cgi?id=1631988#c4
For RPM distributions such as SUSE, openSUSE, CentOS, Red Hat or Fedora, fuse-libs is enough and fuse package is not required neither for building or running.
References:
- Local test for CentOS6 and CentOS7
- https://build.opensuse.org/package/view_file/filesystems/s3fs/s3fs.spec?expand=1
- Dependency checking at my laptop (openSUSE 15.0): 
```$ rpm -q -R s3fs                                                                                                                                                                                                                   
libc.so.6()(64bit) …
```
> For RPM distributions fuse-libs is enough

- doc/man/s3fs.1
- src/curl.cpp
- src/curl.h
- src/s3fs.cpp
- src/s3fs_util.cpp
Adds support for the ONEZONE_IA storage class, which was introduced in AWS in April 2018.
> Add support for storage class ONEZONE_IA.

- src/common_auth.cpp
Addresses GCC 8 warning:
```
common_auth.cpp: In function ‘std::__cxx11::string s3fs_sha256sum(int, off_t, ssize_t)’:
common_auth.cpp:84:12: warning: ‘char* strncat(char*, const char*, size_t)’ output may be truncated copying 2 bytes from a string of length 2 [-Wstringop-truncation]
strncat(sha256, hexbuf, 2);
```
> Simplify hex conversion

- README.md
#785 
Since I submitted s3fs-fuse for Fedora 27, Fedora 28, Fedora 29 and EPEL7, I am adding the instructions about how to install, and removing the compilation details for CentOS7.
Compilation details for Fedora and CentOS are still available at https://github.com/s3fs-fuse/s3fs-fuse/wiki/Installation-Notes#fedora--centos
> New installation instructions for Fedora >= 27 and CentOS7

- README.md
#883
Make the compilation instructions generic for *nix, as discussed at #883
Check https://github.com/juliogonzalez/s3fs-fuse/blob/b2e2189aba94ea01083e446999089290dde022a5/README.md to see how the result looks like.
> Make the compilation instructions generic

- .github/ISSUE_TEMPLATE.md
- INSTALL
- README.md
- configure.ac
#835
Apple changed "Mac OS X" and "OS X" to the new name "macOS" since 10.12 Sierra.
See:
- https://en.wikipedia.org/wiki/MacOS#macOS
- https://www.businessinsider.com/wwdc-2016-os-x-becomes-macos-2016-6?IR=T
So this PR replaces all the mentions to old names with macOS.
Things that were not changed:
- `config.guess` is just a symbolic link to a file belonging to automake package (part of the system).
- `.travis.yml`, as Travis still uses the name `OS X` and similar. See https://docs.travis-ci.com/user/reference/osx/
> Replace all mentions to MacOS X to macOS

- README.md
- doc/man/s3fs.1
- src/s3fs.cpp
This matches the configuration from popular tools like AWS CLI and
allows multiple profile names via `-o profile=name`.  The existing
credential mechanisms continue to work.  Fixes #822.
> Allow credentials from ${HOME}/.aws/credentials

- README.md
Several of these do not work since the shell does not replace ~ in the
middle of a token, e.g., -o passwd=~/.passwd .  Replace all of them
for consistency.  Fixes #836.
> Replace ~ with ${HOME} in examples

- src/curl.cpp
This PR fixes the condition for checking 404 responses on MultiHead requests.
The check should be for -ENOENT, instead of ENOENT.
> fix multihead warning check

- src/s3fs.cpp
These fail SSL certificate checks due to the *.s3.amazon.com wildcard.
Fixes #284.
> Emit more friendly error for buckets with dots

- src/s3fs_util.cpp
This addresses a common use case when interacting with objects from
both s3fs and other S3 tools.  Fixes #890.
> Default uid/gid/mode when object lacks permissions

- src/s3fs.cpp
- test/integration-test-main.sh
Previously s3fs could copy the zero-byte stub object without including
any pending writes.  Fixes #145.
> Flush file before renaming

- src/curl.cpp
Previously s3fs considered 3xx codes as successful.  When writing an
object to a misconfigured region, s3fs did not propagate the 301 as a
write error to the client.  References #693.
> Tighten up HTTP response code check

- src/curl.cpp
Previously this appended to an empty list, zeroed the list, then
appended to the list.  Instead zero the list first and then append.
This also enables sending Content-MD5 which can eagerly detect
transmission errors.  Found via Valgrind.
> Plug memory leak

- src/cache.cpp
- src/cache.h
- src/s3fs_util.cpp
- src/s3fs_util.h
This requires unnecessary `memcpy`.  Found via clang-tidy.
> Avoid pass-by-value when not necessary

- src/cache.cpp
- src/curl.cpp
> Remove unnecessary calls to std::string::c_str

- src/string_util.cpp
- src/string_util.h
- src/test_string_util.cpp
Also backfill unit tests.  Document limitations.  Found via
clang-tidy.
> Fix comparison in s3fs_strtoofft

- src/curl.cpp
#899 ( #693 )
Added message for HTTP 301 status code error.
Since it is one of the reasons that the region of the bucket is mainly different, it displays its contents in case of this error.
> Added an error message when HTTP 301 status

- src/s3fs_util.cpp
#897 
rcloud sets ns(or 10ns) of unixtime using floating point in x-amz-meta-mtime, depending on the conditions such as OS.
Thus, there is a possibility that a numerical value with a decimal point is set in the S3 object's x-amz-meta-mtime.
Therefore, in s3fs, if the value of x-amz-meta-mtime contains a decimal point, s3fs ignore number after the decimal point.
> Ignore after period character of floating point in x-amz-meta-mtime

- src/curl.cpp
#908 #807
If you receive a "307 Temporary Redirect" error on a request with endpoint specified, you must also specify the url option.
In this case, s3fs outputs as additinal error message about it.
However, automatic region change is not supported yet.
> Added detail error message when HTTP 301/307 status

- src/addhead.cpp
- src/cache.cpp
- src/curl.cpp
- src/fdcache.cpp
The compiler can remove the latter when compiled with `NDEBUG` which may
cause unintended control flow.
> Prefer abort over assert(false)

- src/curl.cpp
- src/curl.h
- src/psemaphore.h
- src/s3fs.cpp
Previously s3fs would issue a batch of HEAD requests and wait for all
to succeed before issuing the next batch.  Now it issues the first
batch and only waits for a single call to succeed before issuing the
next call.  This can improve performance when one call lags due to
network errors.  I measured 25% improvement with the same level of
parallelism.  This commit also reparents parallelism knobs for
consistency.  Follows on to 88cd8feb053980c808d67771d63a84ca25f6db8a.
Fixes #223.
> Issue readdir HEAD requests without batching

- src/fdcache.cpp
- test/integration-test-main.sh
Previously s3fs experienced data loss when writing to the middle of a
file.  Corrupt files would have the expected data from 0..offset+size
but unexpected NUL bytes from offset+size..EOF.  References #808.
> Load tail range during overwrite

- src/curl.cpp
- src/string_util.cpp
> Remove unnecessary string copies

- src/addhead.cpp
- src/curl.cpp
- src/fdcache.cpp
- src/s3fs.cpp
- src/s3fs_util.cpp
Found and fixed via clang-tidy.
> Remove redundant string initializations

- src/cache.cpp
- src/s3fs.cpp
> Remove redundant null checks before delete

- src/s3fs.h
This avoids walking the entire heap multiple times for complex
operations like `readdir`.  This does not entirely eliminate the
observed performance regression but does dramatically reduce s3fs CPU
usage.  References #935.  Fixes #936.
> Disable malloc_trim

- src/addhead.cpp
- src/cache.cpp
- src/curl.cpp
- src/fdcache.cpp
- src/gnutls_auth.cpp
- src/nss_auth.cpp
- src/openssl_auth.cpp
- src/s3fs.cpp
- src/s3fs_util.cpp
This is implicit in C++.  Found and fixed via clang-tidy.
> Remove unneeded void parameter

- src/s3fs.cpp
This is more correct than permission denied.
> Return not supported when hard linking

- src/curl.cpp
- src/curl.h
- src/s3fs.cpp
Workers now notify the master thread when they complete, unifying the
Linux and macOS code paths.  This also avoids excessive
`pthread_tryjoin_np` calls.  Follows on to
88cd8feb053980c808d67771d63a84ca25f6db8a.
> Simplify async request completion code

- src/fdcache.cpp
> Add logging for too many parts

- src/curl.cpp
This can avoid dangling parts.  However, many transfers fail due to
network errors so we still need other mechanisms to handle these
parts.
> Automatically abort failed multipart requests

- Makefile.am
- src/curl.cpp
- src/gnutls_auth.cpp
- src/s3fs.cpp
- src/s3fs_util.cpp
- src/string_util.cpp
n/a
With the upgrade of cppcheck used by OSX on TravisCI, cppcheck error appeared.
I corrected these errors.
Since the version of cppcheck depends on the build OS, the code for handling it complicates.
Therefore, inline cppcheck-suppress prevented it(Even if it is unnecessary code, I want to keep it).
Added --suppress=unmatchedSuppression and --xml(to show error id) in cppcheck options.
> Fixed code for latest cppcheck error on OSX

- src/s3fs.cpp
This addresses failures with `test_rename_before_close` when using
`nocopyapi`.  Note that `test_update_time` still fails.
> Remove from file from stat cache during rename

- src/fdcache.cpp
- src/fdcache.h
- src/s3fs.cpp
- test/integration-test-main.sh
Previously s3fs had a race condition where one client could delete
`FdEntity` that another client was using.  Add a simple concurrent test
which previously failed but now succeeds.  Fixes #964.
> Increase FdEntity reference count when returning

- configure.ac
#979 
- Fixed the issue in configure.ac as shown in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923581
- As multi-byte characters were mixed in configure.ac, it was corrected.
> Fixed configure.ac about abuses AC_CHECK_FILE

- configure.ac
- src/curl.cpp
- src/curl.h
#976 #935 
Maintaining an SSL session with CURL will improve performance, and s3fs should use the CURLOPT_TCP_KEEPALIVE, CURLOPT_KEEP_SENDING_ON_ERROR and CURLOPT_SSL_ENABLE_ALPN CURLoptions for curl_easy_setopt().
However, the version of libcurl you use when building may not support these options.
This PR can create s3fs regardless of the version of libcurl used in the build.
That is, if these options are not defined in curl.h, these options will be defined in the s3fs header file and used.
Certainly, defining option values ​​in curl.h to be present in s3fs may not be good, but we expect that libcurl will not change the defined values ​​and assign a fixed value.
So far, this PR allows you to build s3fs without reliance on the libcurl version.
When you start configure, the following …
> Support undefined CURLoption in libcurl library used in build

- doc/man/s3fs.1
#989 
Added `SEE ALSO` section to man page and described fuse(8), mount(8), fusermount(1) and fstab(5).
Users are sometimes confused about options that s3fs does not provide, such as the `nonempty` option provided by fuse and basic usage.
We will not describe option descriptions not provided by s3fs on the s3fs man page, but these will be added to the man page as `SEE ALSO` instead of it.
> Added see also section to man page

- ChangeLog
- test/integration-test-common.sh
- test/s3proxy.conf
This also corrects a test URL which was HTTPS in practice.
> Prefer HTTPS links in documentation where possible

- src/common.h
- src/common_auth.cpp
- src/curl.cpp
- src/fdcache.cpp
- src/gnutls_auth.cpp
- src/nss_auth.cpp
- src/openssl_auth.cpp
- src/s3fs.cpp
- src/s3fs_util.cpp
- src/string_util.cpp
The former cannot return NULL and will allow use of scoped pointers.
> Prefer new over malloc

- COMPILATION.md
- README.md
Most users should use distribution packages and expert users can
consult this file.  References #991.
> Move compilation instructions to separate file

- src/s3fs.cpp
#996 
This PR is a fix for the #996 Issue.
The _netdev option has been corrected to be ignored by s3fs.
Refer to the code of sshfs(sshfs.c) and ignore auto/noauto/user/nouser/users options as well.
> Modified to discard _netdev option etc

- src/curl.cpp
Previously s3fs calculated the strlen of a binary input instead of
using the stored length.  This yielded IO errors when interacting with
SSE-encrypted objects.  Fixes #696.
> Correctly calculate MD5 hash for SSE-C keys

- src/common.h
- src/curl.cpp
- src/s3fs.h
This prohibits missing semicolons.
> Prefer simple over compound statements in macros

- src/s3fs.cpp
This provides compatibility with C++03 and removes duplicate lookups.
> Remove uses of std::map::at

- src/curl.cpp
- src/curl.h
- src/s3fs.cpp
I fixed one issue that I discovered recently related to AWS session token support: when credentials are provided by ~/.aws/credentials file and session token is present, session token is not to request. I decided to remove set_is_session_token_use function from public interface of curl.cpp file. Instead of this I set the flag to true inside method SetAccessKeyWithSessionToken.
I hope code is cleaner right now and works fine. Sorry for introducing a bug in last PR.
> fix issue with aws session token provided inside ~/.aws/credentials file

- src/fdcache.cpp
- src/fdcache.h
- src/s3fs.cpp
Follows on to 2c43b1e12b14fcbdc80bc45ff71733be05548cd7.  Fixes #971.
> Update ctime during nocopyapi operations

- .travis.yml
This takes 5 minutes to run and can cause Travis timeouts.
References #1035.
> Do not update Homebrew in macOS builder

- src/curl.cpp
- src/curl.h
- src/fdcache.cpp
- src/fdcache.h
- src/s3fs.cpp
The latter is 64-bits on 32-bit platforms when specifying
`-D_FILE_OFFSET_BITS=64`.  This allows early Raspberry Pis to use files
larger than 2 GB.  It also cleans up some ugly casting.  Fixes #620.
Fixes #656.
> Convert file offsets from size_t to off_t

- test/integration-test-common.sh
Previously `errexit` could prevent this from succeeding.
> Correct macOS integration test umount

- src/curl.cpp
This makes Travis logs actually readable.
> Emit older curl warnings only once

- .travis.yml
- src/fdcache.cpp
- test/integration-test-main.sh
Check the modification times to determine whether an object has
updated.  This relies on low clock skew between s3fs and the S3
server; a more robust approach could use the ETag.  Fixes #1047.
> Remove cache file when object time differs

- src/cache.cpp
- src/cache.h
- src/s3fs.cpp
- test/integration-test-main.sh
Previously when s3fs had dirty local data and an application opened a
second fd it would remove the stat cache entry, query S3 for the size
which was still zero, then reinitialize `FdEntry` with this incorrect
size.  Instead flush local data to S3 so this query works.  It is
possible that a more involved patch could do this with a less
heavyweight approach but this requires changing open.  This does not
completely fix `git clone` but allows it to proceed further.  Also make
some cache methods `const`-correct.  References #839.
> Flush file when opening second fd

- src/s3fs.cpp
- test/integration-test-common.sh
- test/s3proxy.conf
- test/small-integration-test.sh
Remove unneeded comments; single part limits ensure that the tests
exercise multipart code paths even with smaller files.
References #971.
> Individually test multiple s3fs flags

- .travis.yml
- test/integration-test-common.sh
- test/integration-test-main.sh
- test/test-utils.sh
This requires fewer developer customizations to work on macOS.
Requires some GNU workarounds.
> Use system sed on macOS

- configure.ac
This can catch some classes of buffer overflows.
> Compile with FORTIFY_SOURCE

- src/openssl_auth.cpp
OpenSSL 1.1.0 removed these and generates warnings with newer
versions.
> Annotate OpenSSL locking functions as unused

- src/fdcache.cpp
Previously s3fs issued multipart uploads when the object size was
twice the part size.  Conjoining this with the part size was confusing
and s3fs should add a separate tunable for this if needed, similar to
`singlepart_copy_limit`.  Fixes #1058.
> Issue multipart when object size exceeds part size

- src/fdcache.cpp
> Avoid shadowing variable in FdEntity::Open

- src/fdcache.cpp
- src/fdcache.h
Previously long-running data operations like `RowFlush` would block
metadata operations like `GetStats` and thus user `readdir`.  Fixes #928.
> Break FdEntity locks into data and metadata

- .travis.yml
- src/cache.cpp
- src/cache.h
- src/fdcache.cpp
- src/fdcache.h
- src/s3fs_util.cpp
- src/s3fs_util.h
Recursive locking is frowned upon and is incompatible with
`PTHREAD_MUTEX_ERRORCHECK`.  Also clean up `pthread_mutex_lock` error
checking.
> Remove recursive locking

- .clang-tidy
- src/addhead.cpp
- src/addhead.h
> Avoid misplaced const via removing unneeded typedef

- src/s3fs.cpp
> Avoid null dereference

- src/fdcache.cpp
https://github.com/s3fs-fuse/s3fs-fuse/issues/1091
FdManager::Open function should hold FdManager::fd_manager_lock until the function execute finished.
In the current master version of s3fs，FdManager::Open hold FdManager::fd_manager_lock in a pair of bracket, and call FdEntity::Open without FdManager::fd_manager_lock  lock, this will cause coredump in multithreading, details are as follows:
1. thread A call FdManager::Open and create a FdEntity
2. thread B call FdManager::Open and get the FdEntity and trying to call ent->Open without hold FdManager::fd_manager_lock  
3. thread A call FdManager::Close and delete the FdEntity
4. thread B continue function FdEntity::Open execute and crashed happened due to "double free or corruption (out)"
> fix coredump caused by fd_manager_lock locking

- src/cache.cpp
- src/curl.cpp
- src/fdcache.cpp
- src/s3fs.cpp
This displays correct results on 32-bit platforms.
> Avoid narrowing time_t and off_t args in logging

- src/fdcache.cpp
#1081 
The Load method is called from the RowFluch method.
Since the Load method call has already locked the fdent_data_lock mutex, specify the parameter addition (which differs from the default value).
> Add Lock() func parameter in RowFlush()

- test/integration-test-main.sh
n/a
This PR corrected and revised the test test_concurrency.
Fixed the following part of test_concurrency test.
- Number of test files  
Initial 10 pieces, 100 pieces after writing. The new tests were initially set to 5 after writing.
- Number of parallel executions  
The number of parallel executions has been changed from 2 to 10.
- Number of single processing loops  
It has been changed from 100 to 5. This is the same as the number of test files.
- File created in loop  
We randomly created 1 to 100 files, but changed to 1 to 5 files.
- Specify file name clearly  
This is because FUSE may create a special temporary file (a file name such as .fuse_hidden0000005000000001), which may cause the test to fail.
If I misunderstood the nature of this test, I will not adapt this PR.
The new fix …
> Change test_concurrency test

- .travis.yml
- test/filter-suite-log.sh
n/a
If the test fails, TravisCI outputs the contents of the test-suite.log file.
At the time of test execution, loglevel = info is set to s3fs, and the operation log of s3fs is recorded in test-suite.log.
Recently, if a test fails, the test execution log file will grow and TravisCI will not be able to view everything.
In this case, TravisCI will display "This log is too long to be displayed. Please reduce the verbosity of your build or download the raw log."
This PR filters the log output so that TravisCI displays the log.
Failed tests display all logs, successful tests do not display logs of s3fs information level.
> Add log output filter script at test failure

- src/string_util.cpp
> Avoid race when using thread-unsafe gmtime

- src/s3fs.cpp
- src/s3fs_util.cpp
- src/s3fs_util.h
Previously s3fs had races updating these shared variables.  Found via
ThreadSanitizer.
> Eagerly initialize sysconf variables

- test/filter-suite-log.sh
#1099
It was corrected because it might not be possible to filter when there are not enough new lines in the message.
This converges the phenomenon that occurred in OSX.
> Fixed filter-suite-log.sh for on osx

- src/fdcache.cpp
- src/fdcache.h
Slightly reorder locks to avoid double locking.  Found via
ThreadSanitizer.
> Always hold lock when accessing free_disk_space

- test/integration-test-common.sh
This matches the number of retries on macOS and allows Valgrind to
work.
> Increase test startup retries on Linux

- .travis.yml
- test/integration-test-common.sh
- test/integration-test-main.sh
#1062 
In the osxfuse, when updating or reading a file, the update of stats information may be delayed.
To avoid this, specify the direct_io option.
This removes the useless test code pointed out in #1062 .
When using the direct_io option, osxfuse 3.8.0 or later is required. (There is a bug of redirect append in the previous version)
> Added direct_io option for test on osx

- test/integration-test-common.sh
#1062 #1119 
Since test_read_external_object test still fails in osx, add auto_cache option in addition to direct_io.
> Added auto_cache option for test on osx

- test/integration-test-common.sh
- test/integration-test-main.sh
#1062 #1110 #1111 #1119 #1120
In the test of enable_noobj_cache option, test_read_external_object fails in many cases.
This is probably due to caching and maintaining stats information for non-existent files.
Therefore, the expiry time of the stats cache is set to 1 second, and it is made to cache out before starting the test_read_external_object test.
> Added stats cache expire option for test

- src/curl.cpp
`EVP_MAX_MD_SIZE` can range up to 64.  Found by Coverity.
> Use length from s3fs_HMAC256 for consistency

- src/curl.cpp
- src/curl.h
Callers already manage lifetimes via `Clear()`.
> Do not heap allocate BodyData

- src/curl.cpp
- src/s3fs.cpp
The former propagates errors consistently.
> Prefer s3fs_strtoofft over atoi and strtol

- src/fdcache.cpp
- src/fdcache.h
- test/integration-test-main.sh
#1098 
On OSX, when the nocopyapi option was specified, the simple cp command failed.
It was detected by adding a simple cp command with a test case.
Unlike writing to a file with dd, when using the cp command, a callback such as chmod is called.
During the write callback process, the chmod callback was called and the file size was not updated, causing a problem.
This problem was caused by overwriting the size when opening an existing fd with FdManager::Open().
In addition to this modification, this PR also deletes FdEntity::is_modify flag.
This is_modify flag which indicates cache modification, should not be  managed by the FdEntity class(object), but by each element of FdEntity::pagelist.
In other words, add a modify flag to fdpage instead and manage modify status for individual …
> Fixed simple copy with nocpoyapi and modify flag in fdcache

- src/curl.cpp
- src/curl.h
- src/s3fs.cpp
#1102
The concurrent write test failed when multipart copy failed and retry is executed.
This function and retry handler was incorrect, those were a mistake in the processing, and those implementation was insufficient.
If you change the permissions of a file larger than 5GB, multipart copy processing will be performed, but these will fail in the retry processing.
> Fixed multipart copy and its retry handler

- src/curl.cpp
n/a
In multipart processing, when a part reaches the retry count limit due to get some error, an error(EIO) was returned at reaching limit.
However, this is wrong, and the S3fsMultiCurl::MultiRead() method must wait for receiving all part results before returning an error(EIO).
> Fixed MultiRead method to exit after waiting other parts at error

- test/integration-test-main.sh
n/a
Modified the test script a little.
- The part that calls rm command directly has been changed to use rm_test_file.
- The file used in the test_open_second_fd test has been changed to a dedicated file.  
The cause is not clear, but it seems to have been affected by the previous test, test_concurrent_writes.  
This modification was necessary to obtain stable test results.
> Modified the test script a little

- src/s3fs.cpp
`CheckBucket` only returns errno and HTTP status codes.
> Remove useless CURLE_OPERATION_TIMEDOUT check

- src/curl.cpp
- src/curl.h
#1130 
S3fsCurl::LastResponseCode has been changed so that the value is set when curl_easy_getinfo() is called and completes normally or reaches the maximum number of retries.
And, the code of the S3fsCurl::RequestPerform() method has been revised.
> Refixed strict processing of MultiRead method

- src/curl.cpp
- test/integration-test-main.sh
- test/test-utils.sh
When overwriting and copying a file, we need to use /etc/mime.types to decide the file Content-Type, rather than cached meta Content-Type。
When overwriting and copying files, s3fs use the original file Content-Type meta cache，the cached Content-Type may be not correct, for example the file upload by a machine doest not have file /etc/mine.types。So in order to allow user fixed the wrong Content-Type,  we need to use /etc/mime.types to decide the file Content-Type。
> use correct content-type when overwriting and copying files

- src/curl.cpp
- src/s3fs.cpp
- src/string_util.cpp
- src/string_util.h
- src/test_string_util.cpp
This fixes a regression from ccf3e7bfa201428e06e2d97a70f277de981102e4
which caused the misparsing of octal inputs for the `mp_umask` and `umask`
flags.  It also allows some callers to be more precise about their
decimal inputs.
> Expose base parameter in s3fs_strtoofft

- src/curl.cpp
https://github.com/s3fs-fuse/s3fs-fuse/pull/1098#issuecomment-526386233
When Multipart Upload/Copy was re-executed, the element copy of the s3fscurl object was incomplete.
The op/type member was not inherited and retry processing failed.
This has been fixed.
> Fixed a bug that type and op are not inherited

- src/curl.cpp
- src/gnutls_auth.cpp
- src/nss_auth.cpp
- src/openssl_auth.cpp
Previously s3fs could create a long list of pre-signed requests which
could take longer than the default S3 clock skew limit of 15 minutes.
This also changes SHA-256 computation from single- to multi-threaded
since this is now computed in the worker threads.  Regression from
88cd8feb053980c808d67771d63a84ca25f6db8a.  Fixes #1019.
> Sign request immediately before sending

- .travis.yml
n/a
Since caskroom/cask has been changed to homebrew/homebrew-cask, s3fs cannot be built on OSX.
Modified to use homebrew/homebrew-cask.
> Updated .travis.yml for tapping homebrew/cask-cask

- test/integration-test-main.sh
#1171 
The cause of #1171 is not clear yet.
However, from the travis log, it seems the file size was not 0 even the file was opened with truncating.
(Further inspection is required for file cache clearing errors or file cache size calculation errors.)
In order to avoid test_write_multiple_offsets test issue, I will use another file name for this test.
After merging this fix, investigation continues for #1171
> Fixed test_write_multiple_offsets error on osx

- src/fdcache.cpp
- src/fdcache.h
- src/s3fs.cpp
- test/integration-test-main.sh
#1171 #1173 
The bug #1171 is due to forgetting to close the file descriptor in s3fs_rename() function.
This caused errors in tests after the test_rename_before_close test.
By correcting this forgetting to close, I discovered a problem in the rename processing.
During the rename processing, s3fs did not rename the file cache and file status cache.
In addition, the target file objects(FdEntity) were not detected properly when the cache directory was not specified.
Therefore, these two problems are corrected by this PR.
Also, the test code that temporarily avoided the error in #1173 has been restored.
> Fixed a rename bug

- src/curl.cpp
https://github.com/s3fs-fuse/s3fs-fuse/issues/1184
Fixes when the bucket name and first part of endpoint match by skipping the first part, either `https://` or `http://`
> handle edge case when bucket name and first part of endpoint match

- .travis.yml
n/a
The build for OSX was very slow and I felt it needed to be improved.
The reason is that the following processes are long.
- brew tap homebrew / homebrew-cask
- brew install awscli cppcheck truncate
Thus I changed to cache homebrew using TravisCI cache.
If a cache exists, over 800 seconds required for the above two processes can be shortened to about 30 seconds.
The correct way to cache homebrew is to leave it to TravisCI, but I could not shorten by that way.
So that, I add manually setting cache in .travis.yml, and it works fine for now.
And, if you want to create a new TravisCI Cache, you can delete it from the WebUI and recreate it.
I hope that merging this PR will reduce the time stress on the developer.
> Use travis cache for brew on osx

- COMPILATION.md
- README.md
https://github.com/s3fs-fuse/s3fs-fuse/issues/723
I don't usually compile from source so having dependencies spelled out helps newbies like me. I have the comment `or your OS equivalent` because it was `pkgconf` on Manjaro.
> Specfiy pkg-config as a necessary dependency for compilation

- src/curl.cpp
- src/curl.h
- src/s3fs.cpp
This PR adds `requester_pays` option, false by default, to enable requests involving Requester Pays buckets.
Related issue:
https://github.com/s3fs-fuse/s3fs-fuse/issues/635
> Adds requester_pays option to enable requests involving Requester Pays buckets

- README.md
Since Debian 8 and Ubuntu 14.04 `apt` is available and can be used instead of `apt-get`.
For Fedora, `dnf` has been the default package manager since Fedora 22.
> Update install instructions for Debian and Fedora

- test/integration-test-main.sh
n/a
If the test_chown() of the test script causes an error (mainly related to file permission) for the chown command, the script is trapped at that point.
This seems to occur when the ensure_diskfree option is specified in Travis CI of MacOS.
Even if the chown command error is not trapped directly, it can be detected as an error in the immediately following judgment statement.
Therefore, it is patched to avoid trapping chown command errors directly.
> Not trap chown command errors directly

- src/fdcache.cpp
- src/fdcache.h
- test/integration-test-main.sh
- test/small-integration-test.sh
- test/test-utils.sh
@gaul ，the previous pull request is：https://github.com/s3fs-fuse/s3fs-fuse/pull/1146, still have some situations not fully considered, so I closed the previous pull request.
Deadlocks will appear in the following situations also：
thread A call s3fs_write, already get the fdent_data_lock and cache_cleanup_lock（for clean up cache dir）, after cleaning one file, and trying to get fd_manager_lock for Close the FdEntity.
thread B call s3fs_open for the same file，already get fd_manager_lock and fdent_lock, trying to get fdent_data_lock
the deadlock occured between thread A and thread B, because each thread wants to get the lock of another thread
so when cleanup a cache file, we should hold fd_manager_lock until it finished, if we cannot hold it, we can ignore it temporarily.
Another deadlock …
> fix deadlock in clean up cache

- src/fdcache.cpp
- test/integration-test-main.sh
n/a
Suppress debug messages when clearing the cache and starting and completing it.
Although the output is at the INFO level, the log may be too large in TravisCI and the build may fail.
Changed to DBG level and commented out.
In the test_clean_up_cache() test, I changed the test to 10MB * 25 files instead of 1MB * 256 files, and reduced the log output.
> Suppressed a lot of message output about cache cleanup

- src/curl.cpp
- src/s3fs.cpp
- test/integration-test-main.sh
Previously s3fs auto-detected the MIME type of directories like
"TOYOTA TRUCK 8.2.2" as application/x-troff-man.  This caused `get_mode`
to not set `S_IFDIR` which failed directory creation.  Instead force all
object names ending in / to application/x-directory.  Fixes #1183.
> Set directory MIME type to application/x-directory

- test/integration-test-main.sh
- test/small-integration-test.sh
#1151 #1237
Since a test error has occurred on MacOS, we have responded.
Testing the code merged in #1151 will fail on MacOS.  
Please refer to Issue #1241 for details.
In content-types test, Mime.type seemed to be different on MacOS, resulting in an error.  
See also #1237.
Ensure_diskfree test is bypassed because ensure_diskfree test takes too much time.
> Avoid test errors on MacOS

- src/curl.cpp
Content-Type means：‘The Media type of the body of the request (used with POST and PUT requests).', so we should change complete multipart  content-type to 'application/xml'.
> use correct content-type when complete multipart upload

- .travis.yml
n/a
Somtimes, in TravisCI the time for test execution may exceed 10 minutes, resulting in an error inadvertently.
The PR itself should be reviewed so that the test itself can be completed sooner, but as a temporary measure, this PR will extend the timeout.
> Avoid TravisCI timeouts in test execution

- COMPILATION.md
#1217
I would say having `/etc/mime.types` is a runtime requirement.
Without it s3fs-fuse does not fail but uploads all files as "application/octect-stream".
NOTE1: I don't know how this works at MacOS as I don't have a system to test it. Is it `/etc/mime.types` as well?
NOTE2: If this PR is accepted, we should probably check for `/etc/mime.types` at `configure.ac` and break the build if it's not available.
> Generic compilation instructions: explain that /etc/mime.type is needed

- COMPILATION.md
- doc/man/s3fs.1
- src/curl.cpp
- src/curl.h
- src/s3fs.cpp
- src/s3fs_util.cpp
- src/s3fs_util.h
- test/integration-test-main.sh
#1253 #1217 
The issue #1217 is that when s3fs cannot load the /etc/mime.types file, it uploads the Content-Type of all objects as application/octet-stream.
As pointed out in PR #1253, s3fs should not be able to build or start up.
This allows the user to notice that there is a problem with mime.types.
Added this option so that the user can specify the mime.types file path instead of /etc/mime.types(default).
I considered that the mime.types file path may be different depending on the environment by each user.
On non-macOS, the default mime.types path is /etc/mime.types. (this path is used when this option is not specified)
On macOS after Cataline, apache2.4 is pre-installed , so /etc/apache2/mime.types is the default for macOS.
This option gives user's environment flexibility.
s3fs exits …
> Added mime option for strict checking of mime types file

- src/cache.cpp
n/a
There was a bug in the stats cache compression process.
Due to this bug, stats that were not scheduled to be deleted may have been removed from the cache, which may have affected performance.
This bug has been fixed by this PR.
Thanks to 天空 for reporting this bug.
> Fixed a bug of stats cache compression

- src/fdcache.cpp
- src/fdcache.h
#1271 
This PR code was modified to strictly manage the file(cache file stats) that holds the state of the s3fs cache file.
If the user has caching turned on, s3fs will load the cache file status(information on the range where the file contents are cached) from this file when opening it.
And if user edits the file, the cache will change and the cache file stats will change as well.
This cache file stats is written out when the file is closed(and flushed).
That is, the cache file stats(file) is loaded when user opens the file and writes when user closes it.
Access to the cache file stats(file) is exclusively controlled within the s3fs process.
Therefore, input/output to this file is performed simultaneously with the cache file with exclusive control.
However, s3fs must ensure that the …
> Improved strictness of cache file stats(file)

- src/curl.cpp
This prevents retries when the server indicates an unsatisfiable MPU
copy part request.  References #1220.
> Add handler for HTTP 416

- src/fdcache.cpp
- src/fdcache.h
#1220 #1276
This PR is a fix for the cause of #1220.
The bug of #1220 is that the size of one part does not meet the required size of multipart when uploading as mix multipart upload.
If the size of one part does not satisfy the required size of multipart, s3fs will download the data around that part and try to satisfy the required size.
And s3fs will upload with a part size that is larger than the requested size.
However, the code contained a bug, and although s3fs downloaded it, s3fs uploaded it without including that downloaded area.
This PR fixes this bug.
Although not included in this PR, the 416 HTTP response code will be corrected in the PR of #1276.
This PR and #1276 will be the correction of the defect of #1220.
> Fixed insufficient upload size for mix multipart upload

- src/curl.cpp
- src/s3fs.cpp
s3fs uses the MIME types file to set Content-Type for uploaded
objects.  Most distribution packages should install this via
recommended (not required) dependencies.  Users compiling from source
may not have this installed and s3fs should not prevent launching
since most users do not care about Content-Type.  Instead warn about
MIME types absence.  Fixes #1270.
> Warn about missing MIME types instead of exiting

- src/curl.cpp
- src/fdcache.cpp
- src/s3fs.cpp
- src/s3fs_util.cpp
- src/string_util.cpp
- src/string_util.h
- src/test_string_util.cpp
#1256 #1191
Although the s3fs_strtoofft() function throws an exception, the process may abort because s3fs does not catch this exception.(ex. #1256 #1191 )
I prepared a wrap function that catches the exception and returns the result or the value(=default value 0).
The part that called each s3fs_strtoofft function is replaced with these wrap functions.
_The s3fs-fuse option analysis function may be left as it is. But it has been modified according to this change._
This fix also helps prevent unexpected aborts in exceptions, but rather to ease debugging difficulties when aborted.
> Not abort process by exception threw from s3fs_strtoofft

- src/s3fs.cpp
Retries actually means tries, e.g., if the user sets zero, s3fs will
never try an operation at all.
> Do not allow zero retries

- src/fdcache.cpp
The new file may already exist so link may fail.  Further `link`/`unlink`
is not atomic.  Addresses an error when renaming an open with with
`use_cache`.  References #1296.
> Relink cache stats file atomically via rename

- test/integration-test-main.sh
- test/ut_test.py
This turns up a failure in `test_rename_file` when calling `seek(0)` on a
renamed file.
> Import ossfs tests

- src/curl.cpp
This allows multipart upload to work with Alibaba OSS.
References #1297.
> Ignore case when comparing ETags

- src/curl.cpp
Amazon suggests retrying on both 500 and 503:
https://aws.amazon.com/premiumsupport/knowledge-center/http-5xx-errors-s3/
Fixes #1251.
> Retry with exponential backoff during 500 error

- src/fdcache.cpp
#1274 
There was a problem in the part that serialized from the stats information file of the cache file changed in PR of #1274.
It seems that the cache file was not functioning effectively from #1274 onwards to this PR.
This bug has been fixed by this PR.
In addition, I'm preparing the code corresponding to #1291, and it is planed to provide a function that can check the consistency of the cache file with that code.
> Fixed a bug about serializing from cache file

- src/curl.cpp
- src/curl.h
- src/fdcache.cpp
- src/fdcache.h
- test/integration-test-main.sh
n/a(or some issues) 
The following bugs were found in the processing of mixed multipart upload.
For example, there is a 500MB file and it doesn't exist in the s3fs cache file yet.
In this case, if user perform the following operations on the target file, the result will be different for each.
- Write a few bytes from the 400th MB and close the file.  
This is working correctly.
- Write from the 0th byte to within 5MB.  
It fails with a 400 HTTP error(EIO).
- Write data from 495MB to the end of the file.  
It fails with a 400 HTTP error(EIO).  
It also unnecessarily downloads before uploading, which reduces performance.
These fatal errors are `EntityTooSmall`.
In the processing of mixed multipart upload, there was a mistake in the calculation of the range of Copy and Upload.  
It may be …
> Fixed about ParallelMixMultipartUpload

- src/fdcache.cpp
- src/s3fs.cpp
- test/integration-test-main.sh
#1311 #1318
There were cases where an error occurred when uploading a mix of files.
It occurs when the file is directly created by truncate(size larger than one entity size(5MB or more) of multipart upload).
In addition to truncate, it could also occur if the existing file size was changed significantly.
These bug has been fixed by this PR.
The fix is ​​to set the modify flag to ON in the stretched area when performing an open(internal processing) that specifies the file size.
This bug is due to a missing fix when supporting the mix upload process.
And I also added test cases(I also changed some existing code comments).
> Fixed upload error about mixuploading sparse file and truncating file

- test/write_multiple_offsets.py
This aligns with `ut_test.py`.  Using an older Python also allows
compatibility with the older macOS 10.12 Travis CI.  References #1323.
> Use Python 2 for write_multiple_offsets

- .travis.yml
- test/integration-test-main.sh
#1268 
Travis macOS Build uses Travis cache to reduce build time.  
And I confirmed that the Travis macOS build was successful because the cache exists, but it failed when the cache was deleted.  
And I also found other issues, this PR is an interim fix for those.  
The build of macOS uses macOS 10.12 which is the image of Travis CI(xcode9.2).  
The reason for using this image is that it's a version that doesn't require an OS reboot after installing osxfuse.  
OS images of 10.13 or later require reboot, and we cannot be built and tested s3fs.  
So we need to continue to use 10.12.  
And Homebrew is not currently offering this version of the binary package as Apple has dropped 10.12 support.  
However, Homebrew offers build and install from source code instead of binary packages.  
The …
> Interim fix for Travis macOS Build

- src/s3fs.cpp
- src/sighandlers.cpp
- src/sighandlers.h
#1334 
Since a class summarizing the processing of the signal handlers has been added, the SIGUSR2 handler and its related processing have been moved to that class.
SIGUSR2 handler is set to bump up the debug log level.
Also, the debugging log level is set by a global variable(it is using a global variable because it is called from a macro in anywhere), but I also moved the operation function of this variable to that class.
Please note that the processing logic has not changed.
This will be a underplot as we will combine other signal handlers into S3fsSignals in the future.
> Moved the SIGUSR2 handler to S3fsSignals class

- README.md
This gives consistency with other providers:
https://github.com/s3fs-fuse/s3fs-fuse/wiki/Non-Amazon-S3
> Move IBM information to Non Amazon S3 wiki page

- README.md
There many s3-based storage object providers fork from s3fs, and some of this providers user can use s3fs to visit(no need to change code), so we can add a providers list for facilitate users, this commit add Tencent Cloud Object Storage  as a storage provider which provide s3-compatible storage service.
> add storage providers

- src/curl.cpp
- src/fdcache.cpp
- src/s3fs.cpp
This removes unnecessary casting.
> Prefer %zd and %zu for ssize_t and size_t

- src/fdcache.cpp
- src/fdcache.h
- src/s3fs_util.h
Found via ThreadSanitizer.  References #1353.  References #1362.
> Lock fdent_data_lock before accessing pagelist

- src/curl.cpp
- src/curl.h
This removes the confusing and unsafe `pthread_mutex_t` array.
> Prefer named locks in curl

- src/fdcache.cpp
- src/fdcache.h
- src/sighandlers.cpp
#1354 
This PR is a code to avoid that s3fs cannot be built when whence SEEK_HOLE/SEEK_DATA of the lseek function is undefined.
Also, in the runtime environment where lseek cannot recognize these whence, s3fs will not start up with an error if the set_check_cache_sigusr1 option is specified.
This fix will broaden the build and run environments.
However, I think that we do not want to change the target OS supported by s3fs by this fix does.
The environment that can be built/executed is increase to wide, but the OS environment that can be officially supported follows the contents discussed in #1354.
> Dynamically determine whether lseek extended options are supported

- src/curl.cpp
- src/curl.h
- src/s3fs.cpp
- src/types.h
This prevents some kinds of implicit conversions.  Also deduplicate
`str`/`from_str` logic.  References #1371.
> Use scoped enums for acl_t, sse_type_t, and storage_class_t

- src/s3fs.cpp
close FdEntity to avoid leakage
close opened FdEntity in s3fs_chmod、s3fs_chown、s3fs_utimens、s3fs_setxattr and s3fs_removexattr
> close FdEntity to avoid leakage

- src/s3fs.cpp
#651 
I hope this might fix #651.
There's clearly an open bug in #651 confirmed by several users related to the parsing of `-o use_session_token`. Looking for anomalies in the source code, I noticed that there was a return value everywhere except here, so I suspect this may be (at least partially) responsible.
> return 0 after parsing "use_session_token" arg

- src/s3fs.cpp
Previously flags like `-o nouafoobar` were parsed as `-o noua`.  Found
via:
```
grep STR2NCMP src/s3fs.cpp | grep -v '="'
```
> Remove incorrect string prefix comparisons

- src/common_auth.cpp
- src/gnutls_auth.cpp
- src/nss_auth.cpp
- src/openssl_auth.cpp
- src/s3fs_auth.h
This allows 32-bit platforms like Raspberry Pi to upload single-part
objects larger than 2 GB.
> Use 64-bit off_t when computing digests

- src/s3fs.cpp
n/a
After calling S3fsSignals :: Destroy () and S3fsSignals :: Initialize (), the return value was misjudged, then fixed this.
> Fixed incorrect Signal related message at s3fs init/terminate

- src/Makefile.am
- src/fdcache.cpp
- src/fdcache.h
- src/fdcache_auto.cpp
- src/fdcache_auto.h
- src/fdcache_entity.h
- src/s3fs.cpp
#1385 #1387 
Due to a bug in the number of references in the file descriptor of a cache file, I have added a class that allows the destructor to automatically decrement the number of references.
By using this class other than fdcache related class, we can prevent the leakage of the number of references.
Checking the number of references by test is difficult.
Therefore, this additional class AutoFdEntity prevents inconsistencies in the number of references.
Also, when the cache file is left open at the end of the s3fs process (when there is a high possibility of a problem), a warning is output.
> Added a class for automating fdentity reference counts

- src/curl.cpp
- src/curl.h
This fixes an issue with large `multipart_size` on 32-bit platforms like
Raspberry Pi.
> Use off_t for read sizes

- src/common_auth.cpp
- src/curl.cpp
- src/gnutls_auth.cpp
- src/nss_auth.cpp
- src/openssl_auth.cpp
- src/s3fs_auth.h
Previously they used hex to refer to binary data which is confusing
since other `std::string` return types are actually hex.  Also remove
unused `s3fs_md5sum`.
> Use more descriptive names for digest functions

- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/metaheader.h
- src/s3fs.cpp
Dead lock will occured in UploadPendingMeta which will call put_headers, the situation like follow:
1. RowFlush get fdent_data_lock, fdent_lock and call put_headers and try to lock fdmanager_lock
2. A another thread call s3fs_getattr， get fd_manager_lock and try get lock fdent_lock to increment refecnt
In step one and step two, the dead lock occured, the solution is not get fdmanager lock to update mtime. In adittion, the file x-cos-meta-xxx can directly update to orgmeta and only need to call put_headers once in UploadPendingMeta.
> fix dead lock in disk insufficient and optimize code

- src/s3fs.cpp
- src/string_util.h
This may prevent confusion seen in
39ec8e242e73ca19127c09b6c62a8c9fd7e1266d.
> Rename STR2NCMP to is_prefix for clarity

- test/integration-test-common.sh
- test/integration-test-main.sh
Previously `S3FS_PID` was not set in the correct shell and thus
`ps u $S3FS_PID` showed all programs.  This caused the flag detection to
fail when users ran other instances of s3fs with different flags.
References #1402.
> Rework s3fs pid handling

- src/curl.cpp
Previously s3fs crashed when `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`
was not set.  References #1162.
> Ensure environment variable is set when using ECS

- src/curl.cpp
- src/s3fs.cpp
The IBM IAM token API wants to introduced additional field `refresh_token_expiration` for token expiry 
> POST /oidc/token HTTP/1.1
> Host: iam.bluemix.net
```
"token_type":"Bearer","expires_in":3600,"expiration":1600889795,"refresh_token_expiration":1603478195,"scope":"ibm openid"}"
```
The `S3fsCurl::ParseIAMCredentialResponse()` is not able to differentiate between `expiration` and `refresh_token_expiration` and picking the last key value in the order, that is `refresh_token_expiration`.
Because of this the token is not getting refreshed by s3fs and application accessing bucket mount are hitting with `Error: EPERM: operation not permitted` 
The code change enforce the exact …
> enforce exact key match in IBM IAM response

- .travis.yml
This works around a travis-ci.com Java/S3Proxy incompatibility.  Also
fix vim formatting.  References #1415.
> Disable builder for linux-ppc64le

- src/fdcache_entity.cpp
- src/fdcache_entity.h
The repair code in [1404](https://github.com/s3fs-fuse/s3fs-fuse/pull/1404)  still have some problem, there is no need to call put_headers method if not exist pending meta，
> not call put headers if not exist pending meta

- src/curl.cpp
- src/curl_util.cpp
- src/s3fs.cpp
- src/string_util.cpp
`operator+`, `operator=`, and `operator[]` are more idiomatic and consistent
with the code base.
> Remove calls to append, assign, and at

- src/gnutls_auth.cpp
This matches the non-nettle definition of `s3fs_md5_fd`.
> Fix MD5 when using gnutls with nettle

- src/curl.cpp
This allows integration tests to pass with `use_sse`.
> Do not send SSE headers during bucket creation

- src/curl.cpp
Resetting this does not re-use the underlying buffer so creating a new
`ostringstream` has similar efficiency.
> Simplify use of ostringstream

- src/string_util.cpp
- src/string_util.h
#1433
The Travis-CI execution result at the time of PR of #1433 was good, but after merging to master, the following error(example) occurred and I could not pass through Travis-CI.
```
s3fs: [ERR] curl.cpp:RequestPerform(2246): HTTP response code 403, returning EPERM. Body Text: <?xml version='1.0' encoding='UTF-8'?><Error><Code>SignatureDoesNotMatch</Code><Message>Forbidden</Message><RequestId>4442587FB7D0A2F9</RequestId></Error>
```
This seems to be due to the difference in case in URL encoding, so I modified the code.
> Fixed signature error due to case of hex string

- src/fdcache_auto.cpp
n/a
The level of the message in the AutoFdEntity::GetFdEntity method was ERR, but I changed it to DBG level.
This message may occur even during normal processing, and the DBG level is appropriate.
> Changed the message level in the AutoFdEntity::GetFdEntity

- src/cache.cpp
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/metaheader.cpp
- src/metaheader.h
- src/s3fs.cpp
- test/integration-test-main.sh
- test/test-utils.sh
n/a
Added access time (a time) just like a normal file system.  
I also reviewed the atime/ctime/mtime update patterns and made them the same as regular filesystems.  
(Currently, those update patterns are not the same as normal file operations.)  
The test case has been modified and the update of atime/mtime/ctime is regulated as follows according to the command.
- create file or `touch`  
update ctime, atime and mtime with same time value.
- `touch -a`  
update ctime and atime with same time value, mtime is kept.
- write file (ex. `echo *** > file`)  
update ctime and mtime with same time value, atime is kept.
- update attributes (ex. `chmod`)  
update only ctime, atime and mtime are kept.
- copy file with attributes (ex. `cp -p **** ****`)  
update only ctime, atime and mtime are kept. …
> Added atime and Corrected atime/mtime/ctime operations

- configure.ac
- src/curl.cpp
- src/string_util.cpp
- src/string_util.h
- src/test_string_util.cpp
- src/test_util.h
Explicit return codes are simpler and safer.
> Remove exceptions from s3fs_strtoofft

- src/curl.cpp
- src/curl.h
This allows ThreadSanitizer to run without warnings.
> Protect curl_warnings_once with a mutex

- test/run_tests_using_sanitizers.sh
Remove Valgrind which duplicates the sanitizers and is much slower.
> Add memory and undefined behavior sanitizer

- src/s3fs.cpp
#1427 
When opening the symlink file, it was no longer necessary to load it into a temporary file or cache file.
This PR fixed it.
> Fixed a bug that symlink could not be read after restarting s3fs

- src/s3fs.cpp
Non-root user can't access mounted s3fs directory when parent directory have only executable bit and current directory have readable bit.
"ls" command failed with "Operation not permitted".
```
parent_dir(mode 0111)
read_only_dir(mode 0444)
txt(normal file)
```
First of all change current directory to parent_dir
```
[parent_dir]$ \ls                           
ls: cannot open directory .: Permission denied   
[parent_dir]$ \ls read_only_dir                   
txt                                                                
[parent_dir]$ \ls read_only_dir/txt               
ls: cannot access read_only_dir/txt: Permission denied                                                           
```
```
[parent_dir]$ \ls                                     
ls: cannot open directory .: Permission …
```
> Fix directory authority

- test/run_tests_using_sanitizers.sh
This removes some fortify source warnings.  Also disable failing
memory sanitizer.
> Disable preprocessor warnings w/o optimizations

- .gitignore
n/a
src/test_string_util.cpp should be excluded in .gitignore.
> Fixed .gitignore for src/test_string_util.cpp

- configure.ac
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/fdcache_page.cpp
- src/fdcache_page.h
- src/s3fs.cpp
#1448 
Regarding the process when the max_dirty_data option is specified(the process of uploading while writing a file), the following two have been modified.
Changed the buffer that stores the return value when uploading(Flush) during the processing of s3fs_write.  
The return value of the s3fs_write function must be the number of bytes written, so it returned the wrong value(error code).  
Due to this, there were cases where uploading could not be performed normally.  
In the process by max_dirty_data option, when uploading while writing the file, the contents of the cache file remained as it was.  
If it remains, it will take up disk space.  
After uploading, new code punches a HOLE in the cache file so that it clears blocks on the hard disk for cached data.  
This will minimize disk …
> Fixed flushing dirty data and compressed the cache size

- src/curl.cpp
- src/types.h
This works around lifetime warnings uncovered by cppcheck.
References #1478.
> Simplify handling of returned ETag

- src/curl_util.cpp
#1478 
Fixed an error detected by cppcheck 2.2.
Errors detected in curl_utils.cpp: nullPointerRedundantCheck is probably a false positive.
> Added comment for nullPointerRedundantCheck/cppcheck2.2

- test/integration-test-main.sh
#1477
The conditions added in #1477 were too strict.
Since the mount path may be a relative path, the grep parameters used in the condition have been separated.
@gaul This is a slight change to the condition modified in #1477.
> Changed a condition of the atime test(fixed #1477)

- .github/workflows/ci.yml
- .github/workflows/linux-ci-helper.sh
#1488 
This PR adds a Github Actions workflow for testing on 11 OS(version).
We have only 2 operating systems on TravisCI, but this PR(Github Actions) can build and test on the following operating systems.
- Ubuntu 20.04/18.04/16.04
- Debian 10(buster)/9(stretch)
- CentOS 8/9
- Fedora 32/31
- openSUSE Leap 15
- macos 10
- macos11 is not supported as it requires a reboot after installing osx fuse.
- Added Debian/CentOS/Fedora/OpenSUSE.
- All test use JDK1.8.
@juliogonzalez If you can, please give me comments about OpenSUSE.
@gaul Please check about JDK.
This PR is only tested on Travis CI, not on Github Actions. It will be tested after being merged.
(This PR source code has passed the test on my repository's Github Actions)
> Added Github Actions workflow

- README.md
Homebrew changed the arguments required to install casks. 
* Previously, `brew cask install <package>` was the correct syntax, 
* But now it's `brew install --cask <package>`. 
This small commit updates the README for installing `osxfuse` to reflect this change.
This is the output when following the README in the current master:
```
$ brew cask install osxfuse
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
```
> Update README for change in brew arguments

- .github/workflows/ci.yml
- .github/workflows/linux-ci-helper.sh
- .travis.yml
- test/integration-test-common.sh
- test/integration-test-main.sh
- test/test-utils.sh
#1488 #1489
There was an error in macos and centos8 of Github Actions added in #1489.
Also, since last week, there was an error in CentOS8, so I fixed these.
On macos, I found that the test code running s3fs via stdbuf was in a dead loop(blocked)-like state.
The only workaround I could find was to eliminate via stdbuf and start s3fs directly.
However, since the output of s3fs is processed by stdbuf again, I don't think it will be a problem.
If there is a problem, I used this workaround because it only obscures the log.
Also, macos stdbuf/sed/truncate is not compatible with linux, so I changed them to gnu(coreutils etc).
We've already changed truncate/stdbuf, but I've also added sed.
Instead of replacing this programs in ci.yml(for Github Actions), I've moved those to a test script. …
> Fixed about Github Actions failure(centos8 and macos)

- src/curl.cpp
May failed when retry(403、No range eg.).
Miss header when reset curl handle.
> fix: miss header when retry

- src/s3fs.cpp
* #1377
AWS can return an explicit 404 message that says that the key doesn't exist:
```
[INF]       curl.cpp:RequestPerform(2441): HTTP response code 404 was returned, returning ENOENT
[ERR] curl.cpp:CheckBucket(3439): Check bucket failed, S3 response: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>my-key/</Key><RequestId>F571C209C9ACA4FC</RequestId><HostId>SBKSxWs3ULB8R8ev....</HostId></Error>
[CRT] s3fs.cpp:s3fs_check_service(3901): bucket not found(host=https://s3.amazonaws.com) - result of checking service.
[
```
It would be great if the message provided by AWS could be printed to the user as well, but I've no idea about how to that in C++.
> fix 404 error message

- src/curl.cpp
- src/curl_util.cpp
- src/curl_util.h
This avoids including Authorization in `SignedHeaders`.  s3fs will
recreate the Authorization header before sending the request.
> Remove authorization header when remaking handle

- src/curl.cpp
- src/curl.h
- src/curl_multi.cpp
In MultRead, If Any retry failed. And curl return no OK(such like WRITE ERROR eg.), MultiRead may return 0 and fd may load this page.
But this page is bad. if request include 403、5xx、Partical File(Read Timeout?Connection loss), And next retry is not CURLE_OK, The 403 data may insert into part head and be set loaded(I think we need overwrite it but not loaded).
1. Multi retry may more large. default is 5(MultiRead) x 5(RequestPerfrom) = 25 count.
2. If offset and size is 0, may request all file without range.
> Retry failed may load bad page

- .gitignore
- test/chaos-http-proxy.conf
- test/integration-test-common.sh
- test/test-utils.sh
This can find errors in retry logic.  Chaos HTTP Proxy does not
support SSL bouncestorage/chaos-http-proxy#1 so users must set
`s3proxy.endpoint` and run via:
```
CHAOS_HTTP_PROXY=1 S3_URL=http://127.0.0.1:8080 make check -C test
```
It can also be helpful to increase retries and reduce sleep times.
References #1504.
> Add configuration for Chaos HTTP Proxy

- src/curl.cpp
- src/s3fs.cpp
Previously s3fs threw away some function return values and returned
`EIO` instead.  This was due to not trusting the mix of -1 and `errno`
return codes.  Correct the obviously incorrect ones via visual
inspection.  Stronger typing may find more occurrences.  Fixes #1519.
> Return more specific errno when available

- .github/workflows/ci.yml
n/a
When building Github Actions on macOS, the following error may be reported and it may fail.
```
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
Error: Process completed with exit code 1.
```
If it is reported as a warning, the build is successful.
Then fixed not to specify `cask`.
> Fixed brew install with cask in github actions workflow

- test/integration-test-common.sh
This logic has always been broken but happened to try one time due to
&& operator precedence.  7158e50ee2b2d48ee2e3724e2f299b4644321aeb
broke this further when quoting && since the command was not
evaluated.
> Re-fix retry logic

- src/curl.cpp
Follows on to 4d833a4fb9ffc70cf5ba399e08390417423901ae.
> Handle s3fs_get_content_md5 and s3fs_sha256_hex_fd errors

- src/s3fs.cpp
Metadata updates fail for large files if "-o nocopyapi" or "-o nomultipart" is set.
This change is related to #1528
```
-rw-r--r-- 1 tcpdump tcpdump 7486832640 Jan 27 11:20 bigfile
cp: failed to preserve ownership for "/grid/bigfile": Input/output error
```
```
unique: 114254, opcode: SETATTR (4), nodeid: 2, insize: 128, pid: 26341
chown /bigfile 72 72
[INF] s3fs.cpp:s3fs_chown(1741): [path=/bigfile][uid=72][gid=72]
[...]
[DBG] s3fs.cpp:get_object_attribute(362): [path=/bigfile]
[DBG] cache.cpp:GetStat(293): stat cache hit [path=/bigfile][time=1128915.515422614][hit count=3]
[DBG] fdcache.cpp:Close(592): [ent->file=/bigfile][ent->fd=7]
[DBG] fdcache_entity.cpp:Close(200): [path=/bigfile][fd=7][refcnt=1]
unique: 114254, error: -5 (Input/output error), outsize: 16
```
```
unique: 114249, …
```
> Add warning for failing metadata updates of large files

- src/s3fs.cpp
AWS enforces a 5 GB limit for single-part objects but other S3
implementations like GCS support larger objects.  Fixes #1542.
> Remove limit for single-part objects

- src/fdcache.cpp
- src/s3fs_logger.cpp
- src/s3fs_logger.h
This PR adds timestamps to the debug output as well as to the cache integrity check output.
The new function `S3fsLog::GetCurrentTime()` isn't thread safe.
Closes #1528
> Add timestamps to debug log and cache integrity check

- test/integration-test-main.sh
- test/test-utils.sh
Previously these failed due to `dd` only copying 32 MB from `/dev/urandom`
and exhausting the limited space in `/tmp`.  References #1543.
> Allow integration tests to use larger files

- src/s3fs.cpp
s3fs periodically flushes data to S3 and hole-punches the written
data, marking it as clean.  Without multipart copy, s3fs would write
the now-zeroed data along with any new data.  s3fs should not attempt
to periodically flush dirty data at all without multipart copy
support.  Fixes #1542.
> Do not periodically flush with nomultipartupload

- src/cache.cpp
fixes #1563
#1563
Sets the stat cache `IsExpireTime` to `true` by default, so that the default `ExpireTime` actually takes effect.
Tested using:
1. Run s3fs: `s3fs -f bucket /mountpoint ...` *without* the `-o stat_cache_expire` option
2. Create a file in S3: `echo | aws cp - s3://bucket/test-file`
3. Run: `ls -l /mountpoint/test-file`
4. Remove the file from S3: `aws rm s3://bucket/test-file`
5. Wait for more than 15min. (During this time, s3fs will still report the file as existing)
6. Run: `ls -l /mountpoint/test-file` . This should print `No such file or directory`
> set IsExpireTime to true by default

- src/curl_util.h
- src/s3fs_logger.h
n/a
There was a part where `sse_type_t` was incorrectly declared in the struct.
Also, the `tv_usec` member of `struct timeval` is different between OSX and Linux, so I fixed it.
> Fixed osx mistype declaration and typo warnings

- src/curl.cpp
- src/s3fs.cpp
#1569 #1567
(But this PR merge does not have to wait for #1567 merge.)
The HEAD request returns a 400 error if access to an object such as SSE is denied.(See also #1567)
If s3fs received this error, it was not registered in the Stats cache.
Therefore, when everytime listing the directories containing the SSE objects that generate the error, a HEAD request was generated for each object that causes the error.
Also, the object that resulted in EPREM with a 403 error also degraded performance as same as it.
For HEAD requests, It was changed the 400 error to EPERM instead of EIO.
And when s3fs receives the result of EPERM, s3fs registers the file in the Stats cache.
This will list the files in the list of objects in the directory without any error message.
However, if s3fs leaves the meta …
> Improved processing when HEAD response is 400

- src/s3fs.cpp
- test/integration-test-main.sh
- test/test-utils.sh
#1453 
The rename logic internally copies the file and deletes the original file.
The cause of the #1453 was that s3fs was updating mtime immediately after this copy, at which time a new cache file was created and the contents of the file were null.
In this PR, updates such as mtime are added to the cache file before copying.
And leave the cache file open and copy (put_header).
After copying, rename the cache file and delete the original file.
Keeping the cache file open is necessary because fdcache cannot be renamed unless it is open and new cache files are not created.
And, although it was also the cause of the problem, I accidentally deleted the cache of the destination file.
This is also fixed. (Prevents unnecessary downloads and improves efficiency)
> Fixed a bug that filling NULL bytes when changing the attribute after renaming

- src/fdcache_entity.cpp
- src/s3fs.cpp
- test/integration-test-main.sh
#1579
In addition to the bug fix of #1579, the same bug was found in the `set`/`remove` operation of `xattr`, so it was fixed.
And I also added and modified the test case.
And, with #1579 and this PR change, the fourth argument(`update_mtime`) of the `put_header()` function is no longer needed, so I deleted it.
> Fixed a bug that padded null bytes when changing xattr

- .github/workflows/linux-ci-helper.sh
n/a
Since last night, the aws command has been errored in the rsa related package in the Github Actions build of Ubuntu 16.04.
Changed to upgrade rsa after installing the awscli package.
(Because the release schedule is near)
```
Traceback (most recent call last):
File "/usr/local/bin/aws", line 27, in <module>
sys.exit(main())
File "/usr/local/bin/aws", line 23, in main
return awscli.clidriver.main()
File "/usr/local/lib/python3.5/dist-packages/awscli/clidriver.py", line 68, in main
driver = create_clidriver()
File "/usr/local/lib/python3.5/dist-packages/awscli/clidriver.py", line 78, in create_clidriver
event_hooks=session.get_component('event_emitter'))
File "/usr/local/lib/python3.5/dist-packages/awscli/plugin.py", line 44, in load_plugins
modules = _import_plugins(plugin_mapping) …
```
> Fixed aws command error by rsa on ubuntu16.04

- src/s3fs.cpp
- src/s3fs_help.cpp
- src/s3fs_help.h
- src/s3fs_logger.h
- src/s3fs_util.cpp
- src/s3fs_util.h
#1596 
The version and command parameters are always output at startup, and the output message is prefixed with [INF].
Below is a sample output.
```
2021-03-06T03:02:13.195Z [INF] s3fs version 1.89(8c58ba8) : s3fs -o allow_other,nonempty,enable_noobj_cache,multireq_max=50 <bucket> /mnt/s3
```
> Output version and command parameters at startup

- README.md
removed duplicated line in the README.md:
from: 
You can also mount on boot by entering the following line to `/etc/fstab`:
```
mybucket /path/to/mountpoint fuse.s3fs _netdev,allow_other 0 0
```
or
```
mybucket /path/to/mountpoint fuse.s3fs _netdev,allow_other 0 0
```
to:
You can also mount on boot by entering the following line to `/etc/fstab`:
```
mybucket /path/to/mountpoint fuse.s3fs _netdev,allow_other 0 0
```
> remove duplicate line from README.md

- src/fdcache_entity.cpp
> Return EFBIG when file exceeds multipart limit

- src/curl.cpp
AWS does not support keys longer than 1024 characters.  Add special
handling for HeadObject which does not have a response body.
> Translate KeyTooLongError to ENAMETOOLONG

- src/s3fs.cpp
> Do not allow renaming to a non-empty directory

- src/s3fs.cpp
This makes the check consistent with read and write.  Found via
pjdfstests.  References #1551.  References #1589.
> Return EACESS when lacking required executable bit

- src/s3fs.cpp
> Do not allow open with O_RDONLY and O_TRUNC

- src/fdcache_entity.cpp
#1590 
Added and modified to define FALLOC_FL_PUNCH_HOLE and FALLOC_FL_KEEP_SIZE symbols prior to Linux 2.6.38.
> Declare undefined symbols for fallocate function

- src/fdcache_entity.cpp
- src/s3fs.cpp
This improves error fidelity.  Follows on to
b70f8db037415821822d7ab2644978086d3df303.  References #1523.
> Propagate errno instead of EIO

- src/fdcache_entity.h
- src/s3fs.cpp
- test/integration-test-main.sh
Previously s3fs created this object to store metadata and overwrote it
when flushing.  This prevented use with object stores which do not
allow overwrites like HDS.  Instead only create an in-memory
representation which reduces the time to create small files.
Fixes #1013.
> Do not create zero-byte object when creating file

- src/bodydata.cpp
- src/common.h
- src/curl.cpp
- src/curl_multi.cpp
- src/s3fs_global.cpp
- src/s3fs_logger.cpp
- src/s3fs_logger.h
- src/s3fs_xml.cpp
- src/string_util.cpp
Make some strings more const, initialize members, and abort if lock
initialization fails.  Partially found via clang-tidy.
> Fix a few nits

- src/curl.cpp
Previously s3fs limited these to 123 characters.  Fixes #1626.
> Allow arbitrary size AWS secret keys

- src/curl.cpp
- src/fdcache.cpp
- src/s3fs_logger.cpp
- src/s3fs_logger.h
- src/string_util.cpp
These uses are probably safe from a buffer overflow perspective but
can cause data race issues in logging due to static buffers.
> Replace snprintf with string and ostringstream

- test/integration-test-main.sh
- test/test-utils.sh
#1586
I noticed that the make_random_string function in my test code is very slow on macos.
When I executed `cat / dev / urandom | base64.....`, it used a lot of CPU and memory, and it took a lot of execution time.
This was also the reason why #1586 bypassed the test_update_metadata_external_large_object test.
With this fix, even if you re-add the bypassed test, the test time will be shorter.
> Fixed make_random_string test code being slow on macos

- src/s3fs.cpp
This avoids mismatched times and is slightly faster.
> Use same time when creating directory objects

- src/fdcache_page.cpp
> Fix off_t to int narrowing in PageList::GetSparseFilePages

- src/cache.cpp
- src/cache.h
- src/s3fs.cpp
#1640
Current s3fs_create function no longer creates(does not upload) a 0-byte initial file, only adds StatCache for it.
However, there was a problem because the response to the situation that this file object on the s3 does not exist yet was insufficient.
First, StatCache has an expiration date, and if the expiration date has expired, StatCache will be deleted.
Even if it has not expired, it may be deleted by renewal or deleted directly.
When s3fs gets the information of the file, if StatCache does not exist, it tries to get the information from the real file(object on S3).
In other words, the current s3fs has a problem because the initial file(0 bytes) does not exist(is not uploaded).
Thus this PR changed the code to use the `no_truncate` flag to prevent automatic StatCache deletion. …
> Additional bug fixing for not creating zero-byte object

- test/test-utils.sh
Use C locale, because some tests check for English expressions
Fixes #1658
> Increase test robustness by adding LC_ALL=C

- src/fdcache_entity.cpp
When the temporary storage filled up, the old implementation starts a multipart upload with the current data even if the minimum multipart size is not reached. This can cause errors depending on the S3 implementation.
There is no real solution for a shortage of temporary storage. The change will implement 2 mitigations. They may help or may not. This depends on the speed of the incoming data vs. the speed of writing data to S3.
The new implementation handles two different scenarios:
1. minimum part not reached: emits a warning and returns -ENOSPC
2. temporary storage is between minimum part size and set multipart size: permanently reduce multipart size to the current size
This scenario may cause the multipart size to be repeatedly, incrementally, and permanently reduced to the minimum …
> Don't do a multipart upload with first part smaller than 5MB

- src/curl.cpp
Previously this looped one more time than necessary due to the `eof`
check:
https://isocpp.org/wiki/faq/input-output#istream-and-eof
Remove now redundant `empty` check.
> Correct usage of istringstream

- src/Makefile.am
- src/curl.cpp
- src/curl.h
- src/fdcache.cpp
- src/fdcache.h
- src/fdcache_auto.cpp
- src/fdcache_auto.h
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
- src/fdcache_pseudofd.cpp
- src/fdcache_pseudofd.h
- src/s3fs.cpp
- src/types.h
n/a
This PR is a fix for managing file descriptors that will be needed for future fixes in s3fs.
_I'm improving the performance of s3fs and want to update the correction part in small pieces, so first I will post the code without upload logic change._
This PR has a lot of modified code, but it is separated into the following two commits and put together as one PR.
The reason for posting them together is that if these are posted two separately, we may not understand the purpose of the PR.
Please do not squash when merging.
When a file(S3 object) is opened, the file descriptor(issued by the system(os)) to the local file of the cache file(or temporary file) managed by s3fs is returned to FUSE.
s3fs always returns the same file descriptor, even if the file is opened at the same time. …
> Make pseudo fd for each file opening and each pseudo fd has own upload info

- src/curl.cpp
- src/curl.h
- src/curl_util.cpp
- src/fdcache_fdinfo.cpp
- src/fdcache_page.cpp
- src/fdcache_page.h
- src/gnutls_auth.cpp
- src/metaheader.cpp
- src/nss_auth.cpp
- src/openssl_auth.cpp
- src/s3fs.cpp
- src/s3fs_auth.h
- src/s3fs_xml.cpp
These do not appear to be problematic but rather just clean up warnings.
Found via clang `-Wshorten-64-to-32`.
> Fix implicit narrowing conversions

- src/cache.cpp
- src/curl_util.cpp
- src/s3fs.cpp
- src/s3fs_xml.cpp
- src/s3objlist.cpp
This is more concise and safer due to not repeating the variable name.
We cannot use `std::string::back` since it is not available in C++03.
> Prefer std::string::rbegin over operator[]

- src/fdcache_entity.cpp
Fixes a crash seen with the CentOS 7 builder and when running with
AddressSanitizer.  Regression introduced by
ac578d188e811ed6bdc7a29fa3b0c810fc29d739.  Fixes #1677.
> Protect orgmeta with fdent_lock

- src/metaheader.cpp
The leading 0 triggers an automatic conversion as an octal value. This fails because it is a decimal value.
Setting the base to 10 prevents this automatism and treats the value as a decimal value.
Fixes: 
```
[WAN] string_util.cpp:cvt_strtoofft(96): something error is occurred in convert std::string(017080564) to off_t, thus return 0 as default.
```
Related to #1676
> Set decimal base for converting subseconds to int

- src/curl_multi.cpp
I struggled a little with the meaning of the previous warning. So I have improved the wording a little to be more precise.
> Improve warning for terminated threads with non-zero return code

- src/curl.cpp
If Content-MD5 header is enabled set it even for empty objects. The Content-MD5 header is required for any request to upload an object with a retention period configured using Amazon S3 Object Lock.
> Set Content-MD5 header even for empty objects

- src/metaheader.cpp
- src/s3fs.cpp
- src/string_util.h
Also convert most callers of `cvt_strtoofft` to base 10 which avoid the
magical behavior of interpreting a leading 0 as octal.
References #1682.
> Require explicit base parameter in cvt_strtoofft

- src/s3fs.cpp
n/a
Fixed comparison warning for size_t variable in s3fs.cpp.
> Fixed comparison warning for size_t variable

- src/s3fs.cpp
#1675 
AutoFdEntity::GetExistFdEntity() is a method that does not set the internal pseudo_fd.
However, in s3fs_write(), there was a part that used AutoFdEntity::GetPseudoFd() after calling the above method.
Originally, it should have used `fuse_file_info* fi-> fh` instead of calling GetPseudoFd().
> Fixed a bug in s3fs_write

- src/s3fs.cpp
Long symlinks may cause that the result buffer is filled and not proper terminated with a null byte.
> Ensure NUL-terminated result after strncpy

- src/fdcache_entity.cpp
- test/integration-test-main.sh
#1685
In the case where utimens was called before flush after updating the file was called, it was wrong to determine that it was being updated.
(It seems to have existed for a long time, but it may have become apparent with the modification of #1666.)
There was a file fix that required the meta data to be updated, and I was getting an error because I was doing an upload with utimens before uploading that meta information.
> Fixed a bug utimens is calling before flush

- src/curl.cpp
This works around a GCS quirk that incorrectly requires this header.
Fixes #1661.
> Set explicit Content-Length: 0 when initiating MPU

- src/fdcache.cpp
- src/fdcache_auto.cpp
- src/fdcache_entity.cpp
- src/fdcache_page.cpp
- src/s3fs.cpp
#1666 
With the fix of #1666, the file descriptor returned from s3fs to FUSE has been changed from physical fd to pseudo fd.
Changed to clearly output the type of file descriptor included in the (debug)message output of s3fs.
This is more useful when debugging and when investigating bugs.
This is a message-only update, not a logic change.
> Updated to clearly output message about the file descriptor type(pseudo/physical)

- src/fdcache_entity.cpp
- src/s3fs.cpp
- test/integration-test-main.sh
#1695 
In the move(rename) logic of the file, there was a problem that it failed when the destination file existed and the size was different.
When moving(renaming) file, it made a mistake the file size of the source file and the destination file.
This happened for files of a size that would be subject to multipart upload(copy).
And added a simple test case, too.
> Fixed a bug about rename existing file of different sizes by mpcopy

- src/fdcache.cpp
- src/fdcache.h
- src/fdcache_auto.cpp
- src/fdcache_auto.h
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/s3fs.cpp
This makes it more clear and type-safe if the caller already has the
lock.  Follows on to 84174c560d7542436067dfbfe1f697368ad7d4a1.
> Explicitly specify lock type

- src/curl.h
- src/fdcache_entity.cpp
- src/fdcache_entity.h
We should use proper locking instead.  Specifically for
`is_meta_pending` this does not do what was intended due to the
read-modify-write of the member.
> Remove unneeded volatile qualifiers

- src/curl.cpp
AWS requires uppercase values.  Fixes a regression from
bbcccd6e9816ebb16ca33d2003d563b24625a053.  References #1613.
> Convert storage class values to uppercase

- src/curl.cpp
Previously s3fs returned `EIO` which was not helpful to the caller.
Returning a more specific error code allows automatically restoring
the object via `RestoreObject` in a subsequent commit.  
References #1466.
> Return EREMOTE when reading Glacier objects

- src/s3fs.cpp
256 TB probably seemed large in 2007 but in 2021 it is small enough to
confuse some users.
> Report s3fs space as 18.4 EB

- .github/workflows/ci.yml
#1710 
The ALL_TESTS flag was missing from Linux tests.
> Fixed 1710 - Added a flag for check in Linux

- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
- src/types.h
n/a
There was a potential bug in the etag string saving process in parallel  multipart uploads.
Currently, it has not been realized, but it may be a problem in future function addition(planned now), so it has been fixed.
This bug is the part that saves etag string when CURL processing is completed in parallel multipart upload.
The object has an etag as a pointer, but it is possible that the entity does not exist in the future.
Therefore, I added an `etag_entities` member to the `PseudoFdInfo` class and modified it so that the etag entity always exists for the period when the `PseudoFdInfo` object exists.
And the `MPPART_INFO` structure has almost the same purpose and member variables as the `filepart` structure, so it is unified as `filepart`.
The `MPPART_INFO` changes are useless after …
> Prevents the etag string buffer from being destroyed during use

- src/s3fs.cpp
I've discovered a lot of requests to my Minio installation from one of servers with s3fs installed.
After changing the log level to debug I saw a lot of log items that some process is recursively fetching file attributes. But I was not able to find any information about the process which made these requests - `lsof` could return only the information about opened files, but it does not handle `get_attr` kernel calls.
So I've added a debug info in the s3fs process itself. This is a really useful feature.
> Add initiator pid, uid and gid to a debug log

- src/fdcache_entity.cpp
- src/fdcache_entity.h
n/a 
This is not a bug or a fix for a logic change.
The `FdEntity::RowFlush` and `FdEntity::Write` methods are common method for all uploading options(`nomultipart`, `multipart`, `mixmaultipart`).
Depending on the upload mode, the processing of these methods is roughly similar logic, but slightly different.
For this reason, we should be aware of the impact on other modes when modifying or changing methods.
I've split these methods in consideration of adding more modes in the future.
The processing of `multipart` and `mixmultipart` is very similar and seems verbose, but I focused on mode specific independence.
@gaul Please give me your opinion.
I thought it would be better to split it when adding a new mode(ex.  adding new mode which is uploading file as a stream).
> Splited some methods of FdEntity class by uploading mode

- src/Makefile.am
- src/fdcache_entity.cpp
- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
- src/fdcache_untreated.cpp
- src/fdcache_untreated.h
- src/types.h
#1666
This PR is an ongoing fix since #1666.
The `PseudoFdInfo` class has member variables(`untreated_start`, `untreated_size`) that are not currently used(values are set but not used effectively).
This variable was added in #1666 to indicate an unprocessed area that has been written to a file but has not yet been uploaded.
The information that this variable should have is more complex and cannot be represented by a simple variable.
So add the `UntreatedParts` class and use `untreated_list` instead of `untreated_start` and `untreated_size`.
Please note that this `untreated_list` variable has not yet been enabled.(I plan to use it effectively in future implementations of stream upload.)
Note that this fix should not affect existing behavior.
> Added UntreatedParts class instead of untreated upload info members in PseudoFdInfo

- src/fdcache_entity.cpp
- src/fdcache_page.cpp
- src/fdcache_page.h
n/a
There were two problems with the calculation of free disk space.
The `PageList::GetTotalUnloadedPageSize` method should check the entire area when `size=0`, but It wasn't able to do this.
Fixed this bug by doing the same process as the `PageList::GetUnloadedPages` method.
Before #1714, I didn't notice it because I used the same method in all upload modes.
The calculation of free space in the case of Mix MultipartUpload is different from normal Multipart and No Multipart, and it has the feature that the object is not needed to download.
Therefore, the calculation of free space is different, but it was not able to distinguish in same function.
Thus, added an argument to the `GetTotalUnloadedPageSize` method and modified it so that it does not accumulate if it is larger than the minimum …
> Fixed a bug in disk free space calculation

- src/curl.cpp
Previously it checked if there was an object present, assuming that
this was a directory object normally created for s3fs directories.
However most S3 clients do not create this object for virtual folders.
Fixes #1460.  Fixes #1687.
> Loosen CheckBucket to check only the bucket

- doc/man/s3fs.1
- src/s3fs.cpp
Support AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN
in addition to the AWSACCESSKEYID, AWSSECRETACCESSKEY and
AWSSESSIONTOKEN.
The old environment variables are still supported, but they are deprecated and no longer documented.
I would add a deprecation warning for the original environment variables if suggested. Users would 
Close #1708
> Add support for AWS-style environment variables

- src/fdcache.cpp
- src/fdcache.h
- src/s3fs.cpp
- test/small-integration-test.sh
#1722 
The `ensure_diskfree` option is an option to protect the free disk space.
The reason for not checking the disk usage of s3fs is that it causes performance degradation. (like the `du` command)
So that s3fs is using disk stat information will improve performance.
That's why we provide the `ensure_diskfree` option.
However, there are some issues that are very difficult to test, such as Github Actions.
This is because the Runner(VM, HOST, etc) have different capacities, so the same value cannot be used for the `ensure_diskfree` option.
To avoid this situation, we have added the option `fake_diskfree` to deceive free disk space.
The value of this option is stored as free disk space when s3fs is started, and after that, this value(difference from the actual free disk space) will be used.
> Added fake_diskfree option to deceive free disk space for test

- src/common_auth.cpp
- src/curl.cpp
- src/string_util.cpp
- src/string_util.h
- src/test_util.h
This makes the call sites more readable than a boolean parameter.
> Add dedicated upper- and lower-case hex functions

- src/curl.cpp
- src/curl.h
- src/fdcache_entity.cpp
- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
- src/types.h
n/a
Changed the etaglist_t element that stores a list of `ETag` values for multipart uploads.
The etaglist_t was a list of `std::string`, but I changed it to a list of newly added structure `etagpair`.
For multipart uploads, the `ETag` and `part number` must be a pair.
Currently, these are managed separately, but that has no problem.
That's because each part of the multipart is a sequential number and matches the position of the string `list etaglist_t`.
In this PR, we have added a new structure `etagpair` with `ETag` and `part number` as members.
And I changed `etaglist_t` to a list of structs `etagpair`.
This PR is a related modification.
> Changed etaglist_t from string list to new structure etagpairs list

- src/fdcache_fdinfo.cpp
When disk cache space is not enough, write file will failed with EIO.
IsUploading() return false when upload_id is assigned, I think here we misused it.
> fix misuse of IsUploading

- src/curl.cpp
- src/s3fs.cpp
- src/string_util.cpp
- src/string_util.h
- src/test_string_util.cpp
This is available from `std::string::size` in callers.
> Require explicit length in s3fs_decode64

- src/fdcache.cpp
This is the same thing but confuses Coverity.
> fclose(FILE*) instead of close(fileno(FILE*))

- test/integration-test-main.sh
- test/test-utils.sh
Reduces per-flag test run-time by 5 seconds.
> Remove sleep 1 from test_update_directory_time

- src/curl.cpp
None
When I test append file, I found append 1 byte after a 513MB file while always reulsting in EIO.
The reason is mixupload will use copy API for previous 513MB.This will be splited into 512MB and 1MB. The data appeded will be uploaded as part 3. So we have 512M, 1M and 1 Byte part, this will cause EntityTooSmall when completing the MultipartUpload.
> fix  mixupload return EntityTooSmall while a copypart is less than 5MB after split

- README.md
Fixed install error
[_If there are Issues related to this PullRequest, please list it._](https://github.com/s3fs-fuse/s3fs-fuse/issues/1618#issuecomment-952174574)
There is an error on Mac while install s3fs like it suggested in README. 
Found a solution, share with you
> Fixed Mac install Error

- .github/workflows/linux-ci-helper.sh
This reduces the dependencies installed.  It does not appear that
Fedora-based distros support this.
> Use JRE instead of JDK for Debian-based distros

- .github/workflows/ci.yml
- .github/workflows/linux-ci-helper.sh
Stretch is supported until June 2022:
https://wiki.debian.org/LTS
> Add Debian Bullseye to CI

- test/integration-test-common.sh
- test/integration-test-main.sh
- test/test-utils.sh
This prevents collisions with other globals.  Fixes #1843.
> Annotate local variables

- .github/workflows/ci.yml
GitHub runners provide 2 Linux CPUs or 3 macOS CPUs:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
> Build s3fs in parallel

- src/curl.cpp
This works around the missing `strcasestr` on win32.  References #728.
> Use XML parsing with PUT HTTP 200 responses

- .github/workflows/ci.yml
- .github/workflows/linux-ci-helper.sh
- Makefile.am
- autogen.sh
- test/filter-suite-log.sh
- test/integration-test-common.sh
- test/integration-test-main.sh
- test/junk_data.c
- test/mergedir.sh
- test/sample_delcache.sh
- test/small-integration-test.sh
- test/test-utils.sh
s3fs uses Bourne shell(`sh`) and `bash` for build and test.
However, these codes have not been tested except visually and directly at run time.
In the future, we will add new test and scripts for it, thus these test script codes should be checked/linted.
So I added it to my code to use [ShellChek](https://github.com/koalaman/shellcheck).
I think `ShellCheck` is popular and has a proven track record.
We can run `ShellCheck` with `make shellcheck`, just like `cppcheck`.
In this PR, the all script codes were corrected the errors and warnings detected by `ShellCheck`.
These code changes did not change the original logic.
Some errors and warnings cannot(should not) be fixed, then they have not done.
For that purpose, I use inline comment(`# shellcheck disable=SCxxx`) to suppress the output of …
> Added test by a shell script static analysis tool(ShellCheck)

- .github/workflows/ci.yml
- src/s3fs_logger.cpp
- src/s3fs_logger.h
This shrinks the binary size from 770 to 540 KB and reduces compile
times.
> Convert S3FS_LOW_LOGPRN from a macro to a function

- README.md
- src/cache.cpp
e01ded9e27f41af45e8614860b29164d13c0101e introduced this compatibility
shim but macOS 10.12 (2016) added this:
https://stackoverflow.com/a/39801564 .  Also remove fallback to
`time(3)` which loses precision.
> Always call clock_gettime(2)

- test/small-integration-test.sh
This makes it easier to run tests against S3 other than S3Proxy.
> Check bucket before trying to create it

- src/cache.cpp
- test/integration-test-main.sh
#1872
Fixed a problem in processing when get_atime(ctime/mtime) failed to get the time.
In convert_header_to_stat, reset 0 if the above function returns -1.
> Fixed the fault tolerance when time stamp getting fails

- src/s3fs.cpp
Found via pjdfstest.  References #1589.
> Preserve sub-second precision with utimens

- src/fdcache_entity.cpp
Previously s3fs only created files that had dirty data and not those
with zero-bytes.  Regression from
771bbfeac5e93da96ee39cb32d59e0b5dfe96377.  References #1013.  Found
via pjdfstest.  References #1589.
> Always flush open files with O_CREAT flag

- src/s3fs.cpp
Previously `s3fs_utimens` used `CLOCK_MONOTONIC_COARSE` which was not
1970-based.  Found via pjdfstest.  References #1589.
> Use CLOCK_REALTIME for UTIME_NOW

- test/test-utils.sh
Previously this did not propagate test failures.  A bad rebase
introduced this logic in 495d51113cbe4da63493a51d47dc94145481455a.
> Propagate return code properly

- src/Makefile.am
- src/common.h
- src/curl.cpp
- src/curl.h
- src/curl_util.cpp
- src/fdcache.cpp
- src/fdcache_entity.cpp
- src/fdcache_stat.cpp
- src/s3fs.cpp
- src/s3fs_cred.cpp
- src/s3fs_cred.h
- src/s3fs_global.cpp
- src/test_curl_util.cpp
n/a
In current s3fs, Management of Credential(or AccessKey, Token, etc) processing and options(variables) for server is scattered in s3fs.cpp and S3fsCurl classes, etc.  
These variables, functions, etc. should be grouped in new S3fsCred class so that information related to Credentials can be centrally managed.  
With this PR code, I didn't change about the logic, I just aggregated those into new S3fsCred class.  
I think this is necessary in the feture because the code become complicated for the support for aws-sdk-cpp and other providers different from AWS S3.  
If necessary, it is possible to modify this class, such as separating it into a base class and a derived class.
> Added S3fsCred class and moved Credential related processing in it

- src/fdcache.cpp
`PATH_MAX` constant is not visible from any of currently included header files in system with musl libc, where compilation fails with an error below. The constant is defined in `limits.h` which is directly include via `climits` header file.
```
fdcache.cpp: In static member function 'static FILE* FdManager::MakeTempFile()':
fdcache.cpp:381:14: error: 'PATH_MAX' was not declared in this scope
381 |     char cfn[PATH_MAX];
|              ^~~~~~~~
```
> Include climits to support musl libc

- src/fdcache.cpp
- src/fdcache_entity.cpp
- src/s3fs.cpp
#1875 
Changed s3fs_truncate function.
This change reduces the number of file uploads if the file size is changed.
On macos, I have found that the truncate call when "size=0" cannot reflect the file size.(This reason is not understood...)
To avoid this, only when "size=0", the flush method is called as before.
Other than that, I found a bug in FdEntity::Open() and fixed it.
> Fixed not to call Flush even if the file size is increased

- configure.ac
n/a 
The first typo has been around since it was written (751c868). It happened that the git command existed, and it seems that it worked fine in terms of operation.
Second, there was a problem with the `vim mode line`.
> Fixed two typos in configure.ac

- src/s3fs.cpp
- src/s3fs_cred.cpp
- src/s3fs_cred.h
#1878 
Moved the parsing, setting and checking process of s3fs startup parameter(for credentials) to S3fsCred class.
This reduces unnecessary public methods and aggregates credential operations into that class.
> Moved parameter analysis processing to S3fsCred class

- src/s3fs_cred.cpp
#1894 
This is a fix for the bug( in `S3fsCred::CheckAllParams` ) pointed out in #1894.
And there was a difference in the code( for analizing `AWS_CREDENTIAL_FILE` environment ) before migration, so it has been added and corrected.
_The typo in the crappy end-of-line colon has also been fixed_
This fix is related to #1878 #1891 #1896 .
> Fixed a bug about checking credential

- .github/workflows/ci.yml
- .github/workflows/linux-ci-helper.sh
#1899 
We merged the changes about GithubActions for `CentOS 8` in #1886 to avoid the error, but we are getting the error again. (it seems in relating java packages)
`CentOS 8` is no longer supported and we have the option of migrating to `CentOS Stream` or migrating to `LockyLinux`.
I think that migrating to `LockyLinux 8` is easy and I post this PR for it.
It is a continuation of PR of #1899. (#1899 was accidentally closed)
> Changed Rocky Linux 8 instead of CentOS 8

- test/integration-test-main.sh
This ensures that a pid follows.
> Pass explicit -p option to ps

- src/s3fs.cpp
Previously s3fs always returned zero when the bucket did not mount.
Fixes #1911.
> Propagate deferred exit status from main

- test/test-utils.sh
Previously the integration tests were exiting after the first failed
test instead of running all of them an reporting their statuses.
Follows on to dbf93c01528f97933c291de9fbba5fb26b60ac03.
> Re-re-fix propagating the return code

- .gitignore
- configure.ac
- doc/man/s3fs.1.in
#1907
The date of the man file is now generated when configure is executed.
The old `s3fs.1` file is renamed to `s3fs.1.in` and then `s3fs.1` is dynamically created.
> Dynamically generate dates for man page file

- test/test-utils.sh
This makes the tests more robust.  Also fix filename to end in .txt.
> Use more new file names for every test

- test/integration-test-main.sh
This test demonstrates the behavior before and after the stat cache
timeout when using `noobj_cache`.
> Add test for external object creation

- src/fdcache.cpp
- src/fdcache.h
- src/fdcache_auto.cpp
- src/fdcache_auto.h
- src/fdcache_page.cpp
- src/fdcache_page.h
- src/s3fs.cpp
- test/integration-test-main.sh
#1631 #1875 #1887
Due to the bug(#1875) fix(#1887), there was a bug in truncate that shrinks the file.
(A bug occurred by fixing #1887 after fixing #1631.)
#1631 bypasses the resize-process if it shrinks the file being edited.
This assumes the case where the file are multiple open(multiple fd).
And with the fix of #1887, flush to the file is delayed when truncate is called.
Before these fixes, it was always flushed after truncation, so this hidden potential bug was not materialized.
The modification of #1631(in `FdManager::Open`) should be bypassed only if there is an open fd other than the fd opened by the truncate process.
Therefore, `FdManager::Open` should only be bypassed if there are more than one file descriptor already open.
_(`FUSE` always preopens a file when truncate it, if it …
> Fixed a bug about truncation for shrinking file

- test/test-utils.sh
#1933
With the fix in #1933, I left the aws command with the unnecessary `--debug` option.
It's an option I don't need except when debugging test cases and I forgot to remove it.
> Removed unnecessary debug options for aws command

- src/fdcache.cpp
#1935 
Change the level of the message to be output in the event of a conflict that occurs during cache cleanup from ERR to INFO.
This part is not an error(processing interruption etc.), and I think that there is no problem at the INFO level(skips the target file due to a conflict).
> Changed the message level(ERR to INFO) of skip cleanup cache

- src/bodydata.cpp
- src/curl.cpp
- src/curl_multi.cpp
- src/s3fs.cpp
- src/s3fs_util.cpp
- src/s3fs_xml.cpp
- src/sighandlers.cpp
n/a
It seems that the version of cppcheck has been upgraded from 2.7 to 2.8 on some macos runners.
Along with that, some errors were reported, so we took corrective action.
_(Still, it doesn't seem to be all macos runners)_
> Fixed errors reported by cppcheck 2.8

- src/cache.cpp
- test/integration-test-main.sh
#1947 
When using the `--in-place(-c)` option of the sed command, sed seems to behave as follows:
- Create a new temporary file(create the file mode as a `0000`)
- Read the original file and write the replacement result to the temporary file
- Changed temporary file mode to `0644`
- Close file, and replace file
In s3fs, the stat information of a file is internally cached until flush is executed, during the file is opened.
In sed `--in-place` mode, a `Permission denied(EACCESS)` error occurred because s3fs forgot to update the open file mode to the stat cache.
So this PR fixed this bug.
This PR added a test case.
Added test case was implemented with the sed command.
I made a shell script and a simple C test code and tried bug reproduction, but I couldn't reproduce the same error.
So the …
> Fixed a bug could not change the mode while the file was opened

- .gitignore
- src/fdcache_auto.cpp
- src/fdcache_auto.h
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/s3fs.cpp
- test/Makefile.am
- test/integration-test-main.sh
- test/mknod_test.c
#1934
The touch command fails when the directory on which s3fs is mounted is mounted with NFS, by #1934.
As a result of investigating this, it turned out to be a bug.
FUSE calls the `create`(`s3fs_sreate`) hook when creating a regular file with mknod.
After that, `flush`(`s3fs_flush`) is not called because mknod is the trigger, and `release`(`s3fs_release`) closes the file handle.
After this, file attribute changes such as `utimens` are called.
Also, when creating a file such as a `touch` command, NFS does not call `open`/`close`, but calls `mknod`.
Due to the above operation of FUSE and NFS, to create a new file with zero file size by the `touch` command, `create`(`s3fs_create`) is called, and `release`(`s3fs_release`) is called without `flush`(`s3fs_flush`).
s3fs delays the creation of …
> Fixed a bug that regular files could not be created by mknod

- src/curl_handlerpool.cpp
#1576 
When removing the curl handler from the pool(when over max count), the upper limit was handled incorrectly.
> Fixed a bug when the pool of curl handler exceeds the upper limit

- test/integration-test-main.sh
This could prevent the test runner from reporting failures.
> Do not call exit in individual test functions

- src/s3fs.cpp
This fixes an issue when using `-o notsup_compat_dir flag`, dating back
to its introduction 3ac39d61f84134bb4dbc60b203be154cf56eae1b.  The new
default exposed this in my local testing but a test runner bug masked
a test failure in test_external_directory_creation.  References #927.
References #1984.
> Allow listing implicit directories

- test/test-utils.sh
This shell incantation is necessary to have errexit take effect for
test bodies.  Previous only the _last_ command's exit code was
propagated to the test runner, masking real failures.  Reverts
ea3c21f270db3c3298ba9b7d04e61146c712e9bb.
> Re-re-re-fix propagating the return code

- src/Makefile.am
- src/curl.cpp
- src/curl.h
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
- src/fdcache_untreated.cpp
- src/fdcache_untreated.h
- src/psemaphore.h
- src/s3fs.cpp
- src/threadpoolman.cpp
- src/threadpoolman.h
- src/types.h
- test/small-integration-test.sh
n/a
In multi-part upload (mix, non-mix upload), the function to upload the file part sequentially before the file is flushed has been added.
The current s3fs will only start uploading a file when a flush is called for the file.  
This PR code has added an option called `streamupload` to allow s3fs to upload the file part before the file is flushed.  
The `streamupload` option is only effective when multipart upload (mixupload and nomixupload) is enabled.  
The individual explanations are as follows:  
This is an option to enable the Stream upload function.  
This option is a tentative option.  
I will remove this option once this PR has been merged and fully tested.  
This function should be as the default behavior of s3fs, I plan to enable this feature like multipart upload.  
At that …
> Add the stream upload which starts uploading parts before Flush

- test/integration-test-main.sh
#1984
Fixed a test error that occurred in #1984.
The error with test_external_creation is because the file stat(the file is not existed)  is not cached when noobj_cache is enabled.
> Fixed a bug in the test_external_creation test

- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
- src/types.h
#1802
There was a bug in the code merged in #1802, so this PR fixed it.
(The tests for `test_truncate_upload` and `test_upload_sparsefile` are failed.)
Perhaps the inconvenience was manifested in this `stream upload` logic after merged #1887.
The range areas which were untreated area was managed by `UntreatedParts untreated_list` value, which was implemented in the `PseudoFdInfo` class.
This has been fixed by moving it to the `FdEntity` class.
Along with this fix, I found that there was a possibility of SEGV error, so it was fixed.
It was a problem with pointer management of `etagpair structure` (which had etag and upload number).
I fixed this by adding and using the `petagpool structure`.
> Fixed bugs about stream upload

- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/s3fs.cpp
This requires avoiding double-locking in `RowFlush`.  References #1991.
> Protect pending_status in UploadPending

- src/s3fs.cpp
- src/s3fs_util.cpp
- src/s3fs_util.h
#1987
#1994
The cause of `test_truncate_cache` test error was a race between threads in the `dirname` call.(Only confirmed with macos10)
This happened because in `test_truncate_cache` test, `s3fs_getattr` was called by another thread while calling `list_bucket`.
Specifically, another `dirname` call was made shortly during receiving a static pointer from `dirname` and setting it to `std::string` buffer.
Therefore, the value set in `std::string` was replaced with the result called by another thread.
To fix this, we introduced `mutex` for exclusive control of `dirname` and `basename`(which return pointers to static variables).
> Fixed race condition in dirname and basename call

- src/metaheader.h
GCC 12 warns that C++17 removes this.
> Remove unneedd binary_function inheritance

- test/integration-test-main.sh
- test/test-utils.sh
n/a
Current test scripts check the timestamp of files and directories, but this timestamp is `unixtime`(seconds).
In future tests, there is a possibility of timestamp(`atime`/`ctime`/`mtime`) change  within 1 second.
So I changed the stat option to get and compare as a string containing nanoseconds.
_I plan to add test cases that require this change later._
> Changed the time(a/c/m) acquisition of stat to nanosecond string

- src/cache.h
- src/curl.cpp
- src/curl.h
- src/curl_multi.cpp
- src/curl_multi.h
- src/s3fs.cpp
n/a
Fixed the `readdir_multi_head` function called from `s3fs_readdir` because it is inefficient.
This fixes an inefficiency if the stat cache was cached out during the processing of `readdir_multi_head`.
`readdir_multi_head` uses a `filler`(FUSE param) to return a list of files and directories stat returned by `list_bucket`.
At this time, even though the files and directories returned by `list_bucket` existed in the stat cache, s3fs was always sending a HEAD request.
Also, HEAD requests are processed in parallel, and those results are stored in the stat cache.
And `readdir_multi_head` reads the value from the stat cache after all request finished.
When the number of stat caches is small and stat cache of those result is out, s3fs requests HEADs which are unnecessary processing.
So …
> Improved to avoid unnecessary head request

- src/cache.cpp
- src/fdcache.cpp
- src/fdcache.h
- src/fdcache_auto.cpp
- src/fdcache_auto.h
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/s3fs.cpp
- src/s3fs_util.cpp
- src/s3fs_util.h
- src/string_util.cpp
- test/integration-test-main.sh
#2000 
Changed the stat time of the object for testing in #2000 to nanosecond units.
However, there was a part where the time of some objects(directories) created/modified by s3fs remained time_t/timeval unit.
Some tests could fail instability because of using time as second/usec units.
This PR code changed them to nanosecond units.
As a result, `mtime`/`ctime`/`atime` of all objects created and modified by s3fs are set in nanosecond units.
With the fix, I prepared some common utility functions and decided to use them.
On macos10, we have detected that `test_mtime_file` fails.
The reason is that when copying a file with `cp -p`, the `mtime` argument of the `s3fs_utimens` call should pass the `mtime` of the original file if it is in the correct state, but this value was different.
In …
> Set mtime/ctime/atime of all objects as nanosecond

- src/curl.cpp
- src/curl.h
n/a
In the case where `S3fsCurl::DestroyCurlHandle` is called from `S3fsCurl::CreateCurlHandle`, there was a flow that caused a deadlock.
Now, the build of macos10 for Github Actions is blocked for 24H.
I'll try again later.
> Fixed deadlock in S3fsCurl::DestroyCurlHandle

- src/s3fs_util.cpp
`basename` and `dirname` mutate their inputs but `const_cast` hid this
behavior.  Also shuffle helpers to avoid unnecessary `std::string`.
Follows on to 404c284440fcbf52671ff703396bd5c22f2f31e3.
> Avoid mutating `mybasename` and `mydirname` parameters

- src/threadpoolman.cpp
- src/threadpoolman.h
n/a
I got the following report with `-fsanitize=thread` in `run_tests_using_sanitizers.sh`, so It was fixed.
```
WARNING: ThreadSanitizer: data race (pid=17275)
Write of size 1 at 0x7b2400000090 by main thread:
#0 ThreadPoolMan::StopThreads() /home/ggtakec/work/s3fs-fuse/src/threadpoolman.cpp:176:13 (s3fs+0x58a3e2)
#1 ThreadPoolMan::~ThreadPoolMan() /home/ggtakec/work/s3fs-fuse/src/threadpoolman.cpp:156:5 (s3fs+0x58a26f)
#2 ThreadPoolMan::Destroy() /home/ggtakec/work/s3fs-fuse/src/threadpoolman.cpp:52:9 (s3fs+0x589902)
#3 main /home/ggtakec/work/s3fs-fuse/src/s3fs.cpp:4802:5 (s3fs+0x4bc632)
Previous read of size 1 at 0x7b2400000090 by thread T5:
#0 ThreadPoolMan::Worker(void*) /home/ggtakec/work/s3fs-fuse/src/threadpoolman.cpp:79:24 (s3fs+0x589bc8)
Location is heap block of size 144 at …
```
> Fixed data race in ThreadPoolMan

- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
#2008 
In addition to #2008 `run_tests_using_sanitizers.sh` detected following, so I fixed it.
```
WARNING: ThreadSanitizer: data race (pid=2385)
Write of size 4 at 0x7b3400006cd0 by thread T30 (mutexes: write M85703959268558400, write M85985434245269344):
#0 PseudoFdInfo::ParallelMultipartUpload(char const*, std::__cxx11::list<mp_part, std::allocator<mp_part> > const&, bool) /home/ggtakec/work/s3fs-fuse/src/fdcache_fdinfo.cpp:433:9 (s3fs+0x5762cf)
#1 PseudoFdInfo::ParallelMultipartUploadAll(char const*, std::__cxx11::list<mp_part, std::allocator<mp_part> > const&, std::__cxx11::list<mp_part, std::allocator<mp_part> > const&, int&) /home/ggtakec/work/s3fs-fuse/src/fdcache_fdinfo.cpp:448:9 (s3fs+0x57649c)
#2 FdEntity::RowFlushStreamMultipart(PseudoFdInfo*, char const*) …
```
> Fixed data race and memory leaks in PseudoFdInfo

- src/s3fs.cpp
#2006
Do not use const_cast for `const char *`, but duplicate it by `strdup`.
> Removed const_cast in set_bucket

- src/cache.cpp
- src/cache.h
- src/curl.cpp
- src/curl.h
- src/fdcache.cpp
- src/fdcache.h
- src/fdcache_entity.cpp
- src/fdcache_entity.h
#2009
Replaced all `lock_already_held` flags with `AutoLock::Type`.
> Replace uses of lock_already_held flag with AutoLock::Type

- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
#1991
Although https://github.com/s3fs-fuse/s3fs-fuse/issues/1991#issuecomment-1202447455 could not be reproduced, the potential issue of `PseudoFdInfo::WaitAllThreadsExit()` was fixed.
In addition, the exclusive control of the `PseudoFdInfo` class was reviewed in connection with this.
> Strictly reviewed the exclusive control of PseudoFdInfo class

- configure.ac
Use man-page date instead of build date
to allow for reproducible builds of `s3fs.1`
This PR was done while working on [reproducible builds for openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).
> Use man-page date instead of build date

- src/fdcache_fdinfo.h
- src/fdcache_page.h
- src/types.h
n/a
On macOS and other Linux, cppcheck 2.9 has been released and reported errors.
This PR fixed those errors.
> Fixed errors reported by cppcheck 2.9

- src/s3fs.cpp
#1982 
On macOS, the value of the statfs member was too large and overflowed.
Also this PR added inode related values for macOS.
This will change the value of df as below.
```
$ df -k
Filesystem    1024-blocks Used Available Capacity iused ifree %iused  Mounted on
s3fs@macfuse0        1020    0      1020       0%     0     0   100%  /Users/users/mnt/s3fsmountpoint
```
```
$ df -k
Filesystem    1024-blocks Used   Available Capacity iused      ifree %iused Mounted on
s3fs@macfuse0 17179869180    0 17179869180       0%     0 4294967295     0% /Users/users/mnt/s3fsmountpoint
```
_(Sorry, I rewrote the PR comment multiple times.)_
> Fixed statfs(free inodes) for macos

- src/s3fs.cpp
- test/integration-test-main.sh
#1961 #1962
**NOTE: This fix is a preliminary fix needed to resolve #1961 and #1962.**
This PR allows user to retain the mount point's stat information.
The mount point that s3fs mounts does not have stat information.
Therefore, the situation is as follows now:
```
$ stat <mount point>
File: ‘<mount point>’
Size: 0               Blocks: 1          IO Block: 4096   directory
Device: 2bh/43d Inode: 1           Links: 1
Access: (0777/drwxrwxrwx)  Uid: ( 9999/<user name>)   Gid: (  100/   users)
Access: 1970-01-01 00:00:00.000000000 +0000
Modify: 1970-01-01 00:00:00.000000000 +0000
Change: 1970-01-01 00:00:00.000000000 +0000
Birth: -
```
The mount point is unixtime(0) for `mtime` / `ctime` / `atime`, and in `0777` as mode, and the `user` / `group` is as same as s3fs process's `uid` / `gid`. …
> Added stat information to the mount point

- src/curl_multi.cpp
- src/curl_multi.h
- src/s3fs.cpp
- test/integration-test-main.sh
#2022 
About #2022
If user uploads a file that includes a non-existent directory path from the aws command, etc., the stat information(`dir/` object) of the intermediate directory does not exist.
So s3fs can not list those directories.
However, user can access files by specifying a file path that includes a directory.
Specifying `compat_dir` does not change this phenomenon.
This fixes:
Fixed so that when `compat_dir` is specified, the directory can be listed even if the stat information(`dir/` object) of the intermediate directory does not exist.
I have added the test code, but a part of test has not been run because `compat_dir` is not included in the s3fs boot options(on the test).
However, my manual testing has been performed and it was succeed.
> Support the object under no directory object path by compat_dir

- src/s3fs.cpp
- test/integration-test-main.sh
- test/small-integration-test.sh
#775 #2033
s3fs' xattr support only worked as Extended attributes.(such as setxattr)
We did not implement the function as `POSIX ACL` pointed out in the issues, so I implemented this.(such as setfacl)
I have also created a test script and it is passing the test without any issues.
> Added support for xattr as POSIX ACL

- .github/workflows/ci.yml
n/a
Github Actions has the following warning, so I upgraded the version of `actions/checkout.`
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout
```
> Updated actions/checkout for gha from v2 to v3

- src/s3fs.cpp
#2016
s3fs expects that the last character of the path is not `/` when the mount point is specified by `<bucket name> + <path(ex. /path)>`.
If a charactor `/` terminated path(ex. '/path/') will be specified, it will be excluded during option parsing.
But  there was a bug that multiple `/` terminated path(ex. `/path//`).
This PR fixed this bug.
- Impact of this bug
If `/path//` and a mount point were specified, the files under the mount point were invisible.  
(Because it searches the path `<bucket>/path//`)  
Also, although files can be manipulated, a file with a path that s3fs cannot recognize has been created.  
For example, creating a file named `sample` with this mount point created a file named /path//sample`.  
In addition, I think that there were very few cases where the mount …
> Fixed a bug when end of path for mount point is multi slash

- .github/workflows/ci.yml
- .github/workflows/linux-ci-helper.sh
n/a
Added `Fedora:37` and `RockyLinux:9` to Github Actions runner OS.
Also, since ShellCheck was not implemented(unused) in `RockyLinux:8`, I made it possible to run it on both RockyLinux 8 and 9.
> Added Fedora:37 and RockyLinux:9 to Github Actions target OS

- test/integration-test-main.sh
n/a
For some reason the `test_posix_acl` test was failing.
At that time, it seemed that the environment variable `USER` was not set, so I fixed the user name to `root` and fixed it.
Also, I fixed it so that the directory used in this test function was deleted in advance.
> Fixed test_posix_acl test

- configure.ac
- src/Makefile.am
- src/openssl_auth.cpp
#2061
Fixed the warning that appeared when building OpenSSL 3.0.
MD5_*** and etc has been deprecated and cased to use EVP.
> Compatible with OpenSSL 3.0

- README.md
https://github.com/s3fs-fuse/s3fs-fuse/issues/1618
https://github.com/s3fs-fuse/s3fs-fuse/issues/1632
Fixing the command to install fuse on mac M1, removing notes line.
> Update readme, mac instructions, on M1

- .github/workflows/linux-ci-helper.sh
n/a
`Gihutb Actions` on `Rocky Linux 9` had the following error.
```
Error: 
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Problem: problem with installed package curl-minimal-7.76.1-19.el9.x86_64
- package curl-minimal-7.76.1-19.el9.x86_64 conflicts with curl provided by curl-7.76.1-19.el9.x86_64
- conflicting requests
```
The `Rocky Linux 9` image includes `curl-minimal`, which conflicts with installing the `curl` package.
(the conflict may not have occurred before `7.76.1-19`)
For `Rocky Linux 9` only, this PR adds the `--allowerasing` option when installing `curl` to avoid this.
In the `linux-ci-helper.sh` file, I defined …
> Fixed a conflict between curl and curl-minimal on RockyLinux 9

- src/curl.cpp
- src/curl.h
- src/s3fs.cpp
#2089 #2088
There was a bug that failed to rename files using SSE due to omission of #2088 fix. (for #2089)
In the SSE compatible specifications, some specifications were unclear and they were bugs, so I fixed them.
There are no basic specification changes, but we have clarified the parts that were not clear so far, fixed them, and tested all of them.
Also, there was a cache problem in rename(if the cache file did not exist when renaming), so it has been fixed.
Please allow me to submit this fix in this PR as it was required for testing.(s3fs.cpp)
For reference, the clear specifications around SSE are summarized below.
Depending on the s3fs boot options, the encryption shown below will be used.
| s3fs option                        | Encryption type |
| ---------------------------------- | …
> Fixed renaming bug with SSE

- src/curl.cpp
- src/curl.h
- src/s3fs.cpp
#2063 #1728 #1687 #1460
Fixed a bug where a bucket has no permissions and a directory has permissions, and a mount with that directory fails.
This PR is related to #1728 which was previously fixed.
Here's a bucket check on s3fs startup and a description of how it works in this PR.
The following patterns for mount point are supported by s3fs:
1. Mount the bucket top
2. Mount the directory(folder) under the bucket. In this case, there are the following cases:
(   2A) Directories created by clients other than s3fs
(   2B) Directory created by s3fs
At first, if user has access to the bucket, the checking access to the bucket succeeds and this function returns success.
However, if user does not have access to the bucket and has permissions to the directory, this first check will fail.
But if …
> Retry BucketCheck containing directory paths

- src/curl.cpp
#2098 
When IAM role was specified(IAMv2), there was a deadlock in token acquisition.
This logic is communicating with the HTTP PUT method, but since `Content-Length=0` was not specified (`Transfer-Encoding: chunked` is specified), it was deadlocked while waiting for a response.
- Before fixing(deadlocked)  
```
PUT /latest/api/token HTTP/1.1
Host: 169.254.169.254
User-Agent: s3fs/1.91 (commit hash 16bc449; OpenSSL)
Accept: */*
Transfer-Encoding: chunked
X-aws-ec2-metadata-token-ttl-seconds: 21600
```
- After fixing  
```
PUT /latest/api/token HTTP/1.1
Host: 169.254.169.254
User-Agent: s3fs/1.91 (commit hash b5ffcac; OpenSSL)
Accept: */*
X-aws-ec2-metadata-token-ttl-seconds: 21600
Content-Length: 0
```
> Fixed a deadlock bug when specifying iam role(IAMv2)

- src/curl.cpp
- src/curl_util.cpp
- src/fdcache_entity.cpp
- src/s3fs.cpp
- src/string_util.cpp
- src/string_util.h
#2095 
Until reported in #2095, there was no example of using characters that require URL encoding in the upload id specified in a multipart upload.
The upload id is passed as a query parameter in the URL, so it should be URL encoded accordingly.
So I changed the process to URL encode the upload id and pass it as a query parameter.
In this amendment, since the functions related to URL encoding become complicated, I have also changed the function names as follows.
| before changing | after changing   |
| --------------- | ---------------- |
| urlEncode       | urlEncodePath    |
| urlEncode2      | urlEncodeQuery   |
| -               | (new) urlEncodeGeneral |
> multipart upload id is converted by url encode

- .github/workflows/ci.yml
- .github/workflows/linux-ci-helper.sh
- autogen.sh
- src/curl.cpp
- test/integration-test-main.sh
#2046 #2110
Enabled to execute Github Actions(CI) for ALPINE(v3.17).
This change includes the following changes:
Changed from `bash` to `sh`. (because the initial image of ALPINE does not include `bash`)
Created a condition for ALPINE and made modifications accordingly.
ALPINE's `autoconf` is new and needs to be updated in `configure.ac`.
However, some supported older OS's don't support the new KEYWORDS in configure.ac, so I've added `autoupdated` for it.
Changed `CURLOPT_PUT` to `CURLOPT_UPLOAD`.
`CURLOPT_PROGRESSFUNCTION` should be changed to `CURLOPT_XFERINFOFUNCTION`, but it was not changed because we have an OS that uses old curl.
Compiling on ALPINE will output a warning, which can be ignored.
In ALPINE, the `ENOTSUP` error is output as `Not supported` instead of `Operation not …
> Updated files for support ALPINE v3.17

- src/cache.cpp
- src/metaheader.cpp
- src/metaheader.h
I am currently using  s3fs with minio. When I try to write a file with a name greater than 255 in s3fs, s3fs exit with segmentation fault. Because minio uses an xfs file system that limits filename length to 255.
```
#0  0x00007f3ee1fbff4f in __strlen_sse42 () from /lib64/libc.so.6
Python Exception <type 'exceptions.ValueError'> Cannot find type const headers_t::_Rep_type:
#1  0x00000000004218a7 in get_mode (meta=std::map with 5 elements, path=path@entry=0x0, checkdir=checkdir@entry=false,
forcedir=forcedir@entry=false) at metaheader.cpp:144
#2  0x000000000043ec11 in StatCache::UpdateMetaStats (this=<optimized out>,
key="/host_e8b47009f661-host_diskio_used_percent_az_id_6fcabee9_f323_4904_9799_073ad3e552a3_cloud_id_6398743040_cluster_id_6398730244_device_sda1_instance_7009f65e_e8b4_b14f_eb …
```
> Fixed segmentation fault caused by file write failure

- src/fdcache_entity.cpp
#2120
After an error occurred on the server side during file upload(Flush) processing, there are reports(#2120) that the contents of the file cannot be read correctly.
If the upload fails in an environment that uses cache, the local cache may have been updated even though the object on the server side has not been updated.
Even in this state, subsequent reading may be performed normally (maybe reloading due to inconsistency in stat information), but Issue #2120 seems to cause inconsistency.
If the upload fails, the local cache is in a correct state (not matching the server side) and cannot be repaired.
Therefore, I modified it to clear the cache if it fails.
@gaul 
Since this PR only clears the cache, I think it won't impact anything else.
So, if the tests pass, I think I'll merge this PR …
> Added cache clearing on upload error

- src/s3fs.cpp
#2128 #2130
Always deleted cache files when renaming large files(these files use multipart uploading).
The cache file for these files should have been renamed in the same way as for non-large files, so this PR changed it to rename the cache file.
This was revealed by the bug reported by #2128.
FUSE temporarily changes the file name to `/.fuse_hiddenXXXYYY` if the opened file is deleted by another process etc.
When the opened file is closed, this temporarily file is also deleted.
In #2128, the cache file was deleted without being renamed after renaming, so the cache filewhich under the mirror directory remained.
(Files under the mirror directory are for file descriptors used when opening files.)
> Changed to rename cache files when renaming large files

- configure.ac
#2116 
We added `autoupdate` command to `autogen.sh` by #2116.
`autoupdate` will update `configure.ac` at build time if needed, but currently it always updates.
Therefore, this PR updates `configure.ac` as same as updating it by `autoupdate`.
> Fixed configure.ac by autoupdate

- .gitignore
- src/fdcache_page.cpp
- src/metaheader.cpp
- src/s3fs.cpp
- test/Makefile.am
- test/integration-test-main.sh
- test/truncate_read_file.c
#2107 #2131
_This PR changed the fix method because #2131 was not enough fix._
There was a bug in trauncate, which shrinks files.
This bug occurs under the following conditions:
- Open the file and shrink the file.
- After shrinking, do read before flushing(do not close or sync).
At this time, it got the old size before shrinking from the server(Content-Length) and set old size again.
So that the read data from the reduced size to the original size padded as 0x00, and read it.
When read all of file, the read size is old length before reduction.
Changed so that when opening a file that has already been opened and resized(without flushing), it is opened as the modified file size instead of the file size on the server side.
When reading(loading) a file, there was a problem that the …
> Fixed a bug when reading a reduced file without flushing

- .gitignore
- src/s3fs.cpp
- src/s3fs_xml.cpp
- src/string_util.cpp
- src/string_util.h
- src/test_string_util.cpp
- test/Makefile.am
- test/cr_filename.c
- test/integration-test-main.sh
#2067 
libxml2 converts `CR` code(`'\r'`=`0x0D`) to `LF`(`'\n'`=`0x0A`) according to the XML specification.
Therefore, if the object name(file name) contains `CR`, `ListBucket` will try to process the object name converted to `LF`.
And as a result, there was a problem that the user could not get the file list.
The fix is to escape(`%0D`) the `CR` code from `ListBucket` results before libxml2's XML parsing and restore it after parsing.
_The encoding uses the same technique as URL encoding._
Within XML content, HTML encoding(`&#13;`) is appropriate, but in this case escaped and unescaped strings are indistinguishable, so it was not possible.
In this fix, we added a unit test(in `test_string_util.cpp`) for the string manipulation function(`test_cr_encoding`).
Also added `cr_filename.c` for …
> Fixed a bug in handling file names containing CR(0x0D)

- src/s3fs.cpp
A bug discovered by report #2138
In some cases, stats settings including `mp_umask`(`uid`, `gid`) for mountpoints could not be set.
This is due to the missing fix for #1964.
This problem cannot be inspected in the current test, so I checked it manually. (It is an option specified when starting s3fs, and this inspection is currently difficult.)
> Fixed a bug about attributes of mount point

- doc/man/s3fs.1.in
- src/curl.cpp
- src/curl.h
- src/s3fs.cpp
#2151
(Related: #2063 #1728 #1687 #1460 )
Checking mount point still had issue #2151 after a series of fixes.
(It's almost identical to the issue mentioned in #1460.)
I would like to support the following cases:
User specifies a directory created by a client other than s3fs as the mount point.
(It means there is no object as this directory, and there is a file object etc under that path.)
And if user has no permission to the bucket and has permission to this mount point directory, s3fs does not start with an error.
This PR is code to support the above case.
There is already a `compat_dir` option to support directories created by clients other than s3fs and directories with no existing objects.
In the above case(no directory object for mount point), this PR code make s3fs start without an …
> Allow mount points without directory objects by compat_dir

- configure.ac
This can find more kinds of buffer overflows:
https://developers.redhat.com/articles/2022/09/17/gccs-new-fortification-level
> Specify `_FORTIFY_SOURCE=3`

- src/curl.cpp
flush the file and clean the page cache when filepart download done
add a fdatasync when curl download the filepart finish this to make memory cache of this file to flush to disk.
if not add fdatasync , when copy the large files  this will take many active file cache .
> Update curl.cpp:  reduce memory cache use when copy the big file from s3fs mount path

- src/curl.cpp
Reverts s3fs-fuse/s3fs-fuse#2157
> Revert "Update curl.cpp:  reduce memory cache use when copy the big file from s3fs mount path"

- src/fdcache_entity.cpp
Mark pagelist as unloaded if cache file has been truncated
If cache file size doesn't match object size, the cache file might be
corrupted, so invalidate it and save new cache stat file.
---
Fix inconsistency between stat cache file and cache file
We unlock stat cache file too early in FdEntity::Open(), and would
truncate cache file and update stat cache file, so there's a window that
stat cache doesn't reflect cache file status.
> Fix two inconsistency issues between stat cache and cache file

- test/test-utils.sh
This makes Linux and macOS more consistent.
> Always return nanoseconds from get_time helpers

- test/test-utils.sh
This appears to be some kind of eventual consistency check.  This should have no effect given S3Proxy and recent AWS strong consistency. Also it is likely ineffective given the other test object creation operations.
> Remove wait and check loop from mk_test_file

- src/s3fs_cred.cpp
n/a
Found unnecessary and the wrong level of debug output, then it is removed because unnecessary.
> Removed unnecessary debug output

- .github/workflows/ci.yml
#2172
I added some memory checking to CI process as same as `run_tests_using_sanitizers.sh`.
Each test in `run_tests_using_sanitizers.sh` seem best to be a CI Job because all of test several patterns require execution from the build.
The testing base container is Ubuntu:22.04.
This PR is first submitted as a Draft.
> Added several memory checks to CI

- configure.ac
Add support for user space fuse (FUSE-T) on macos. 
FUSE-T doesn't require installation of kernel extensions (KEXT) as opposed to osxfuse.
Details of the project can be found here: https://github.com/macos-fuse-t/fuse-t
To install FUSE-T use brew:
brew tap macos-fuse-t/homebrew-cask 
brew install fuse-t
Change autoconf to discover and use FUSE-T if present, otherwise fallback to osxfuse
> Add support for FUSE-T on macos

- .github/workflows/ci.yml
- .github/workflows/linux-ci-helper.sh
18.04 is EOL:
https://ubuntu.com/blog/ubuntu-18-04-eol-for-devices
This removes a FUSE 3 blocker.  References #1159.
> Add Ubuntu 23.04 and remove 18.04

- configure.ac
- src/s3fs.cpp
This PR fixes extended attribute support when using FUSE-T. 
When libfuse receives an attribute size of 0, the pointer is not defined and should not be assumed to be NULL.
Relevant libfuse code:
struct fuse_setxattr_in *arg = (struct fuse_setxattr_in *) inarg;
char *name = PARAM(arg);
char *value = name + strlen(name) + 1;
...
req->f->op.setxattr(req, nodeid, name, value, arg->size, arg->flags, arg->position);
> Fix extended attribute support when using FUSE-T

- src/fdcache.cpp
FdEntity::Open() returns -errno on error, but FdManager::Open() only checks if its ret is -1. This may lead to use '-errno' as pseudo fd in next read or write, which would fail due to '-errno' is not in fent map.
> Check FdEntity::Open() status correctly

- src/curl.cpp
- src/fdcache_entity.cpp
- src/s3fs.cpp
n/a
The following error in the ThreadSinitizer test was detected, so it was fixed.
```
WARNING: ThreadSanitizer: data race (pid=22052)
Read of size 4 at 0x7b4c000119a8 by thread T9 (mutexes: write M0):
#0 FdEntity::IsDirtyNewFile() const /__w/s3fs-fuse/s3fs-fuse/src/fdcache_entity.cpp:2546 (s3fs+0x5dc836) (BuildId: ab83e9890914b4c6d66a0fd5ea48fdf43707afe7)
#1 s3fs_release(char const*, fuse_file_info*) /__w/s3fs-fuse/s3fs-fuse/src/s3fs.cpp:3023 (s3fs+0x54aae9) (BuildId: ab83e9890914b4c6d66a0fd5ea48fdf43707afe7)
#2 fuse_fs_release ??:? (libfuse.so.2+0xd345) (BuildId: 4db3553f25db655fdcad5600bb328da5dc18736b)
Previous write of size 4 at 0x7b4c000119a8 by thread T44 (mutexes: write M1):
#0 FdEntity::UploadPending(int, AutoLock::Type) /__w/s3fs-fuse/s3fs-fuse/src/fdcache_entity.cpp:2450 …
```
> Fixed data race in threads found thread sanitizer

- src/curl.cpp
- src/curl_handlerpool.cpp
- src/curl_handlerpool.h
#2209
Fixed the following data races that were not fixed in #2209.
```
WARNING: ThreadSanitizer: data race (pid=11216)
Write of size 8 at 0x7b080002f920 by thread T170 (mutexes: write M0, write M1):
#0 free ??:? (s3fs+0x4ad379) (BuildId: 227310a5f6a82ab3f004ee942adca3592e8d83e1)
#1 OPENSSL_sk_free ??:? (libcrypto.so.3+0x205cfa) (BuildId: 3273586fcac67f861ec301429787310dc38b9e7e)
#2 S3fsCurl::HeadRequest(char const*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, header_nocase_cmp, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> …
```
> Fixed data race at OPENSSL_sk_dup/free in libcurl

- src/s3fs.cpp
- src/s3fs_xml.cpp
- src/s3fs_xml.h
- src/s3objlist.h
- test/integration-test-main.sh
Previously the test missed listing implicit directories and another test was incorrect.  This fixes a regression from 1.91.
> Explicitly handle CommonPrefixes with nocompat_dir

- src/s3fs.cpp
#2213 #2212
In the thread callback handler for `HeadRequest` called by FUSE readdir, `void* buf` and `fuse_fill_dir_t filler` seem not suitable for asynchronous writes.
I checked the FUSE source code, but it seems that exclusive control for `buf` is not implemented by `filler`.
s3fs `HeadRequests` are processed in parallel by multithreading, so it seems that this `filler` call needs to be synchronized.
_However, `ThreadSanitizer` never detected this part yet._
(Even if exclusive control is performed in the `filler`, I have decided that exclusive control on the s3fs side is not a particular problem, so I am submitting this PR.)
This fix obsoletes `multi_head_callback_param` uses in threading functions and uses `SyncFiller` objects instead.
All data related to `filler` and `buf` are …
> Fixed data race about fuse_fill_dir_t function and data pointer

- src/fdcache_entity.cpp
Previously pcfstat points to a raw pointer, and it may be leaked if
function returned before deleting it.
So use smart pointer to automatically release the object.
Note that currently s3fs only uses c++03, so we use auto_ptr here, not
unique_ptr, which requires c++11.
Fixes: https://github.com/s3fs-fuse/s3fs-fuse/commit/6ca5a24a7f29718967de1b8cc78dfe68c839729a ("Fix two inconsistency issues between stat cache and cache file (https://github.com/s3fs-fuse/s3fs-fuse/pull/2152)")
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>
> Use smart pointer to manage pcfstat object

- src/curl.cpp
References #2218.  References #2227.
> Insert SSE headers when appropriate

- .github/workflows/ci.yml
n/a
Tighter version number checking in cppcheck.
The current decision statement bypasses the check for cases like "2.9".
This statement provides some protection against future version number format changes.(cppcheck on macOS is 3 digits)
And the same conditions were set for the CI part when supporting macOS fuse-t.
> Fixed checking cppcheck version in ci.yml

- .github/workflows/ci.yml
- Makefile.am
- configure.ac
- src/curl.cpp
- src/fdcache.cpp
- src/fdcache_page.cpp
#2163
#2162 
#2179
Fixed errors detected by `cppcheck v2.10 (SUSE leap:15)`.
This reverts the setting that was temporarily disabled(`v2.10` and `useStlAlgorithm`) in #2163.
With this fix, cppcheck checks can be done on all OSs.
Support for `CentOS7`(which was discussed in #2195) is resolved by adding the `-std=c++11` CXXFLAGS.
> Supported cppcheck 2.10(and changed std from c++03 to c++11 for RHEL7)

- .github/workflows/ci.yml
- Makefile.am
- src/cache.cpp
- src/curl.cpp
- src/fdcache.cpp
- src/fdcache.h
- src/fdcache_auto.cpp
- src/fdcache_auto.h
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/fdcache_fdinfo.cpp
- src/fdcache_page.cpp
- src/openssl_auth.cpp
- src/s3fs.cpp
- src/s3fs_cred.cpp
- src/string_util.cpp
- src/threadpoolman.cpp
- test/cr_filename.c
- test/junk_data.c
- test/mknod_test.c
#2197 
Fixed a description error in ci.yml in #2197.
(Due to this description error, current code cannot be executed cppcheck.)
Also, #2197 was in the process of supporting cppcheck 2.1x, so I fixed it to support it correctly.
(verified with cppcheck 2.11.1)
The following parts have not been modified. (avoided by `suppress` inline comment)
- Make arguments of Callback function to const
- Judgment statements for functions that return only true
> Refixed for cppcheck 2.1x

- src/addhead.cpp
- src/addhead.h
- src/curl.cpp
- src/curl.h
- src/curl_multi.cpp
- src/curl_multi.h
- src/fdcache_entity.cpp
- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
- src/fdcache_page.cpp
- src/s3fs.cpp
- src/s3fs_logger.cpp
- src/s3fs_util.cpp
- src/string_util.h
- src/types.h
This simplifies code paths and makes memory leaks less likely.  It also makes memory ownership more explicit by requiring `std::move`. This commit requires C++11.  References #2179.
> Replace some raw pointers with `std::unique_ptr`

- src/common_auth.cpp
- src/curl.cpp
- src/gnutls_auth.cpp
- src/nss_auth.cpp
- src/openssl_auth.cpp
- src/s3fs_auth.h
This is safer and more efficient.
> Convert fixed-size allocations to C++11 std::array

- test/junk_data.cc
Previously this had a mismatch between `size_t` and `unsigned long long`.
> Fix junk_data for 32-bit platforms

- src/addhead.h
- src/curl.h
- src/curl_handlerpool.h
- src/curl_multi.h
- src/fdcache_fdinfo.cpp
- src/fdcache_page.h
- src/fdcache_pseudofd.h
- src/mpu_util.h
- src/s3fs.cpp
- src/s3objlist.h
- src/threadpoolman.h
- src/types.h
- test/write_multiblock.cc
This tends to be more efficient due to fewer allocations.  Also fix `std::sort` comparator which should be strictly less than.
> Convert most `std::list` to `std::vector`

- src/common_auth.cpp
- src/curl.cpp
- src/s3fs.cpp
- src/string_util.cpp
- src/string_util.h
- src/test_string_util.cpp
This is avoids manual memory allocations.
> Return `std::string` from base64 encoding function

- src/autolock.h
- src/fdcache_auto.cpp
- src/fdcache_auto.h
- src/fdcache_page.cpp
- src/fdcache_page.h
One of these was buggy and others had the wrong parameters and return types.
> Delete copy constructors and assignment operators

- src/test_string_util.cpp
#2248
Enabled to check with empty string instead of nullptr in string test.
(This causes an error on macos, so we have fixed it.)
> Fixed string test for s3fs_base64

- src/s3fs_cred.cpp
This may help users debug situations like:
https://stackoverflow.com/questions/76359564/why-does-mounting-s3fs-bucket-on-centos-7-using-fstab-fail-but-mount-a-works
> Improve illegal bucket name error message

- test/run_tests_using_sanitizers.sh
Otherwise errors can be ignored for successful tests with memory errors.
> Set exit code for Valgrind

- .github/workflows/ci.yml
n/a
`make check -C src` (test of src directory) was missing in the Linux OS test, so I added it.
I'm not sure why this test is missing, but I added it because it's necessary.
> Added make check for src directory for Linux OS

- src/curl.cpp
#2276
Since the CI addition of clang-tidy was merged first, there was an error, so I fixed it.
> Additional fix for #2276(Convert BodyData to std::string)

- src/s3fs.cpp
- test/integration-test-main.sh
#2280
`std::map emplace` will not replace the value if that key exists.
Fixed xattrs handling to call `erase` if there is a target key.
I also added a test case for the missing xattrs inspection related to this.
Check where emplace is used in the current source code, and there is no problem except for xattrs.
(In the `stat cache` process, the keys are deleted in advance, so I don't think there will be any problems.)
> Added std::map erase before calling emplace in xattrs operations

- src/cache.cpp
- src/cache.h
This removes an unnecessary use of `unique_ptr`.
> Own values in `stat_cache` and `symlink_cache`

- src/cache.cpp
#2284
Fixed an error in cppcheck 2.11.1 on macos
(Other than macos, the version of cppcheck is low, and these errors are not displayed.)
> Fixed errors in cache.cpp from cppcheck 2.11.1

- src/cache.cpp
`emplace` does not overwrite the value if the key already exists.  C++17 has `insert_or_assign` but C++11 only has `operator=` which invokes the default constructor.  Follows on to 6781ef5bd1a86b39469366307b582f342c945c71.
> Replace uses of `emplace` with `operator=(&&)`

- src/addhead.h
This is identical to the explicit one.
> Use default move constructor

- src/s3fs.cpp
- src/s3fs_logger.h
Print fuse context like pid in fuse operations, so we know which process is triggering this operation.
> s3fs: print fuse context in s3fs fuse operations

- src/s3fs.cpp
This can avoid an expensive computation which is 20% of test runtime.
> Skip `is_uid_include_group` when GID available

- .github/workflows/ci.yml
- test/run_tests_using_sanitizers.sh
- test/s3proxy.conf
Using HTTP instead of HTTPS and
82107f4b6c4cf455c2f3dd63e0ade29f042c1b0f improve test run-time so that this is now feasible.
> Enable Valgrind in CI

- src/fdcache_entity.cpp
clang-analyzer found a path where this could be used without initialization.
> Initialize variable before use

- test/filter-suite-log.sh
This addresses warnings of the form:
```
grep: warning: stray \ before %
```
> Do not escape percent

- test/integration-test-main.sh
Other call sites need the call to `readdir`/`getdents64`.
> Remove unnecessary uses of `ls`

- test/integration-test-main.sh
echo does not split the words on newlines.
> Revert ls change

- README.md
Documents support for the `AWS_SESSION_TOKEN` variable. The variable is one way to support temporary credentials.
Without the documentation, the only way to know about the support is to read [s3fs_cred.cpp](https://github.com/s3fs-fuse/s3fs-fuse/blob/a83f4a48d0286062fc6837e913a523c3286974fd/src/s3fs_cred.cpp#L956-L972). 
Extends https://github.com/s3fs-fuse/s3fs-fuse/pull/2281 .
> Document support for temporary credentials

- src/cache.cpp
- src/cache.h
- src/curl_multi.cpp
- src/mpu_util.cpp
n/a
`cppcheck` on `Fedora 38` (and `macos 12`) had been upgraded to `2.12.0` and was therefore detecting errors.
I have fixed this error.
> Fixed errors of cppcheck 2.12.0

- test/test-utils.sh
#2319 
Change the judgment statement for whether the `stat` command has the `--cached` option.
This is determined based on the `OS` and `version`, but this method may require further modifications in the future.
Therefore, I changed it to simply check the result of `stat --cached=never`.
(My comment in #2319 was not simplified, so this is a correction)
> Simplify the determination of the --cached option of the stat

- test/integration-test-main.sh
#2319 
Fixed the execution condition of the `test_not_existed_dir_obj` test added in #2319.
It was correct that the conditions to run on `not Alpine` were correct, but wrong to run on `Alpine only`.
Also, since the `/etc/os-release` file does not exist on `macos` (although it is currently unnecessary), I added that condition as well.
> Fixed test_not_existed_dir_obj test condition

- src/fdcache_fdinfo.cpp
- test/integration-test-main.sh
#2299 
Fixed the bug detected in #2299.
There was a problem in calculating the start position of the upload part during Streamupload, and it has been fixed.
We have also added a test case(`test_not_boundary_writes`) to detect this defect.
_Although it is possible to include it in the `test_write_data_with_skip` test, I made it independent as a test case._
Currently, Github Action CI is failing for this PR due to a stat(cached) issue.
> Fixed a bug upload boundary calculation in StreamUpload

- configure.ac
This allows overriding flags like `-std=c++11`.
> Reorder `$CXXFLAGS` to the end

- src/fdcache_fdinfo.h
These are protected by `upload_list_lock`.  Addresses warnings of the form:
```
warning: ‘++’ expression of ‘volatile’-qualified type is deprecated
```
> Remove `volatile` qualifiers deprecated in C++23

- src/s3fs_cred.cpp
n/a
When the password file does not exist, now only the error "s3fs: unexpected error from stat" will be reported, which is not convenient for locating the problem.
In order to fix this problem, this patch adds detailed error message printing.
> s3fs_cred: print detailed error message when stat file fails

- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
n/a
The name of the argument (`upload_list`) of the `PseudoFdInfo::ParallelMultipartUploadAll` method was changed to `to_upload_list`.
The `PseudoFdInfo` class has a `upload_list` member variable, so it is confusing to use the same name, so you should change it.
> Changed argument name in ParallelMultipartUploadAll

- src/string_util.cpp
- src/string_util.h
These already force a copy so passing by value has the same performance but is simpler.  But this allows the compiler to perform copy elision on temporaries and the caller to explicitly `std::move` in others.
> Pass by value to trim functions

- src/curl.cpp
- src/curl_util.cpp
- src/curl_util.h
- src/string_util.cpp
- src/string_util.h
- src/test_string_util.cpp
n/a
When completing a multipart upload(in the `UploadMultipartPostComplete` method) it was not possible to remove double quotes from the response ETag string.
But it was deleted in the similar `CopyMultipartPostComplete`, then mixed Etags(with/without double quotes) for Mix Multipart Upload.
So far, this doesn't cause uploads to fail, but I'd like to keep the specs the same.
> Fixed  ETag parsing at completing the Multipart upload part

- test/compile_all_targets.sh
This is useful to compile different SSL libraries and 32-bit targets.
> Add a helper script to compile all targets

- src/curl.cpp
Without this, the check fails when mounting a subdirectory in the bucket (for example `AWSSSECKEYS=vgXEublG7JJkhfRSZT1Ze3lefY2d7j3i s3fs -f -d -o bucket=my-bucket:/my-subdir/,complement_stat,allow_other,uid=0,gid=100,use_cache=/tmp/s3fs-cache,del_cache,ensure_diskfree=10000,curldbg,use_sse=custom /mnt/s3` when using SSE.
Before this PR, this would fail with:
```
2023-10-18T11:43:57.132Z [ERR] curl.cpp:RequestPerform(2561): HTTP response code 400, returning EIO. Body Text: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The object was stored using a form of Server Side Encryption. The correct parameters must be provided to retrieve the object.</Message><RequestId>T0X9HXZ34AMSCGB9</RequestId><HostId>dVaEyuY7JaiD3b3tqmtfPUeLfCFi0qwewT2JXRTIniJjGobA0VLiuZJbC1f …
```
> Set SSE headers when checking bucket

- src/s3fs.cpp
#2198 
I'm working on making it compatible with macos 12, but in CI testing I will specify `noattrcache` when starting `macos fuse-t`.
_This is an option to avoid attars caching._
As a result, CI tests can run, but there are a lot of getting `attrs` related calls.
And they will output a lot of `INFO` level messages.
Changed log message output for function calls of `s3fs_getattr` and `s3fs_setxattr` from `INFO` to `DBG` level because more messages were output than permissible.
This is only for macos.
> Suppress some message levels on macos

- src/s3fs.cpp
#2332
Fixed a cause for the `test_mtime_file` and `test_update_time_cp_p` tests to fail on Alpine 3.18.
The problem is that the stat information is read before updating a/c/mtime due to a change in the calling order (timing) of the fuse handler when creating a new file.
First, some background:
In previous versions of current s3fs, the process of creating a new file would first create an empty file.
In the current version, this unnecessary process has been simplified and the file is created for the first time when the file content is uploaded.
This simplification causes problems when file stat information is read between the time a new file is created and the time the file is uploaded.
To avoid this, the stat information is retained as a cache even though the file does not yet exist(before …
> Improved updating of temporary stat cache while creating a file

- src/fdcache_entity.cpp
- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
n/a
The CI test was failing in rare cases in the `test_multipart_mix` test of StreamUpload.
(It seemed to happen more often on `macos` than on `linux`)
In StreamUpload, if the part range of each multipart is filled with updates, that part will be uploaded first without waiting for `flush`.
This StreamUpload logic allows for re-uploads of the same part if there are updates(written) to the same part range after the first upload for the same part.
In this case, when flushed the file, this part will be re-uploaded and the previous upload will be overwritten(cancelled).
This is the usual expected StreamUpload's logic.
The error detected this time occurred in a case where Flush was called and a re-upload was started when the previously uploaded part had not yet finished uploading.
It means that …
> Fixed a bug in the re-upload part of Streamupload

- src/s3fs.cpp
#2361
#2332
There were other parts that needed to be fixed in #2361, so we made additional corrections.
The possibility of updating `c/a/mtime` immediately after creating a new file also exists in `chmod`/`chown`/`setxattr`.
Therefore, we added processing similar to `utimens` to these functions.
> Re-improved updating of temporary stat cache when new file

- .github/workflows/linux-ci-helper.sh
n/a
I noticed a meaningless process in `linux-ci-helper.sh` and fixed it.
I believe this was done before the `GHTHUB_ENV` file was provided, but it is currently not working.
What isn't working are the option flags pass to `configure` and the `CXXFLAG` environment variable.
For fixing the option flag, it is written to  `GITHUB_ENV`.
The `CXXFLAG` environment variable is currently set in `Makefile.am`. (especially `-std=c++XX`)
However, there is also a flag(`S3FS_PTHREAD_ERRORCHECK=1`) that is only used by Github Actions (CI), so I also write this to `GITHUB_ENV`.
I don't think it will affect the current build, but I have modified this file so that it fulfills the required functions.
@gaul
Please let me know if you have any problems.
> Fixed a script of not functioning environment in Github Actions

- src/cache.cpp
- src/s3fs.cpp
Directory has size 0, which looks weired and may confuse users. So fake dir size as 4k.
> s3fs: make dir size not zero

- .github/workflows/ci.yml
- configure.ac
- src/curl_multi.cpp
- src/curl_multi.h
- src/s3fs.cpp
- test/integration-test-common.sh
- test/integration-test-main.sh
- test/test-utils.sh
#2154
#2191
By using `macos-fuse-t`, CI process can support macos11 or later.
(Thanks to @macos-fuse-t.)
CI processing(until just before the test) has been confirmed on both macos11/12. 
But the macos CI processing is macos12 only.
_(If necessary, macos11 can also be added.)_
Part of the patch #2197 is applied to pass the cppcheck2.10 test.
_(I will rebase after merged #2197.)_
This PR has not passed some parts of tests yet, so it is marked as a `Draft`.
> Reverted the macos CI process(using macos-fuse-t)

- src/metaheader.cpp
- src/s3fs_logger.cpp
- src/string_util.cpp
- src/string_util.h
This removes workarounds and fixed-length buffers.
> Call C++11 `get_time` and `put_time`

- src/curl_multi.cpp
- src/curl_multi.h
This ensures that the parameter is moved.
> Pass `std::unique_ptr` by value

- src/metaheader.cpp
- src/s3fs_logger.cpp
- src/string_util.cpp
- src/string_util.h
This reverts commit 10a72bfd0f52bc70ad7f1dd6fbb92dbea376614c.  These commit is incompatible with older CentOS 7 libstdc++.
> Revert "Call C++11 get_time and put_time (#2375)"

- src/cache.cpp
- src/cache.h
- src/s3fs.cpp
#2372 
#2198
#2198 supported `macos fuse-t`, but the bug in #2372 remained, so fixed it.
When creating a new file, s3fs does not create a `0-byte` file and delays the upload until the file is flushed.
During this delayed period, s3fs creates a temporary cache in the Stat cache to avoid `file not found` errors in case s3fs receives an instruction to get the file's stat information.
The problem in #2372 is similar to this, but the `readdir` was received during a delayed period.
Because this `readdir` (`list bucket`) is not supported, some `macos12` tests are failing as a bug.
When registering temporary cache information in the Stat cache for a new file, use the file's parent directory as a key and retain the cache information that maps the file name list.
This mapping information exists …
> Corrected list_bucket to search in stat cache during creating new file

- src/s3fs.cpp
This pull request resolves an edge case when the XML fails to add objects to the ListBucket response, and correctly identifies that there are still objects under the `path` provided. This can be caused by slightly restricted (but still correct) IAM permissions, where you add a condition on the s3:prefix to the s3:ListBucket permissions. Specifically, this issue only occurs in special cases where there are special characters in the prefix/object path.
https://github.com/s3fs-fuse/s3fs-fuse/issues/2129#issuecomment-1889763779
There are two changes in this pull request. 
1. We apply a prefix to the `reiter` string before checking if `reiter` is an empty directory. This resolves an `Access Denied` response from S3, because for some reason the [full path did not include the `/` separator …
> fix: List Bucket/IAM Edge Cases

- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/s3fs.cpp
- test/integration-test-main.sh
#2376
#2198
After merging #2376, `test_update_time_append` started to fail in the case of `macos fuse-t`, so it was fixed.
The test failure is due to a different calling sequence from FUSE in using `macos fuse-t`.
In the case of `macos fuse-t`, `s3fs_fsync`(a case of `datasync`) is called before calling `s3fs_flush` when closing a file after updating or creating.
In other words, a calling sequence is `open(create)`->`write`->`fdatasync`->`flush`->`release`.
Until now, there were no cases where `s3fs_fsync` was called, causing problems with updating file metadata.
Fixed so that when `s3fs_fsync`(`datasync`) is called, the file content is not updated at `flush`, but only metadata can be updated.
With this fix, most of required `sleep` in test for macos, such as #2198, are no longer …
> Fixed a bug in fdatasync(fsync)

- .github/workflows/ci.yml
n/a
In CI `actions/checkout` needs to be changed from `v3` to `v4` due to the end of support for `NodeJS v16`.(Still available for use at this time)
Therefore, I changed it to use `actions/checkout@v4`.
However, `actions/checkout@v4` does not work on `CentOS 7`(depending on glibc version), so we should continue to use `@v3` for `CentOS 7`.(see. [actions/checkout issue](https://github.com/actions/checkout/issues/1487))
_At some point, we will no longer be able to support `CentOS 7`, so we will leave it as is until then._
> Updated actions/checkout from v3 to v4

- src/s3fs_xml.cpp
#2394
`s3fs_xml.cpp: get_base_exp()` outputs the following message whose level is `ERR`, causing confusion:
```
marker_xp->nodesetval is empty.
```
Therefore, change this from `ERR` to `INFO` level.
> Changed the level of messages by the get_base_exp function

- src/s3fs.cpp
#2398
When an error occurred during a bucket check, only the message corresponding to the error response code was output, in addition to this, the message included in the response(`Message` field) has been changed to be output.
It's also useful as an easy way to find out details in cases such as 400 errors.
(This is useful in cases where the error content cannot be associated with the response code, as shown in report #2398.)
> Improved to output error details when bucket check fails

- src/s3fs.cpp
#2354 
There was a problem in the parameters when calling `PreHeadRequest` from `readdir_multi_head` and `multi_head_retry_callback`.
(This is a bug detected by @jstastny and this has been supplemented with a fix.)
> Fixed a bug in multi head request parameter

- src/curl.cpp
- src/curl.h
- src/s3fs.cpp
#2401
If the bucket(or directory under the bucket) user attempt to mount is not created as SSE, a GET request(with the `x-amz-server-side-encryption` header) to check the mount point will return an error(InvalidArgument: `x-amz-server-side-encryption` header is not supported for this operation).
Thus, if the bucket did not have SSE settings(get error response), I changed that s3fs retried to send the GET request without `x-amz-server-side-encryption` header to check the mount point.
@gaul
If there are multiple causes for an error when making a GET request to check a mount point, the error details will be returned in order on each attempt, so the trial processing has been changed to a loop and refactored.
(I have added this recovering code, but the basic logic has not changed.)
This is a …
> Fixed a bug that mounting with ksmid specified to fail

- src/s3fs_xml.h
#2405 
An issue was detected in Gentoo + libxml2-2.12.0(<2.12.3) where the libxml/parser.h header could not be included.
Therefore, I added the libxml/parser.h header to be included explicitly.
_Note that the environment other than these conditions is not affected._
> Gentoo + libxml2-2.12 requires inclusion of parser.h

- src/test_util.h
This can give useful core dumps.
> Call `abort` instead of `exit` in tests

- doc/man/s3fs.1.in
- src/curl.cpp
- src/s3fs_help.cpp
#526 ([comment](https://github.com/s3fs-fuse/s3fs-fuse/issues/526#issuecomment-279768645))
For SSE KMS, SSL/TLS communication (https) is required, but it was not checked.
If this combination of options, PUT requests, etc. will fail, but it was difficult to confirm the error details from the user's perspective.
Thus, changed so that s3fs startup fails for this combination of options.
Along with this, a man page and help option have also been added.
(Wiki page will be changed in advance)
> Abort for SSE-KMS encryption type and not SSL/TLS specified

- .github/workflows/ci.yml
n/a
For the past few days, an error has been occurring when running GithubActions (CI) for `MemoryTest (sanitize thread)`.
The error is an error when running `configure`, and the details are as follows:
```
FATAL: ThreadSanitizer: unexpected memory mapping 0x7d6327672000-0x7d6327b00000
```
To avoid this error, set `vm.mmap_rnd_bits` to `28` only in `MemoryTest(sanitize thread)`. (The value before change is `32`. I also set it to `30`, but the error still occurs)
- Reference  
https://stackoverflow.com/questions/77850769/fatal-threadsanitizer-unexpected-memory-mapping-when-running-on-linux-kernels
> Fixed configure error for GHA:sanitize_thread

- src/curl.cpp
Hi,
Some non-Amazon S3 implementation have a stricter quota / rate-limiting than AWS (for example Scaleway). It means that it's quiet easy to be rate limited in case of large buckets for example. In this case, an HTTP error 429 is returned and the request fails.
This PR makes s3fs retry when an HTTP error 429 is returned, as it's already doing for 500 and 503 errors.
Thanks!
> retry request on HTTP 429 error

- README.md
n/a
The Github Actions(CI) Badge URL written in `README.md` was incorrect, so I fixed it.
_(It is unknown when this changed, but I have corrected it to the current correct URL)_
> Fixed README.md for Github Action Badge URL

- src/fdcache.cpp
- src/fdcache.h
> Fix DeadLock in FdManager::ChangeEntityToTempPath

- Makefile.am
- src/curl.h
- src/test_curl_util.cpp
- src/test_page_list.cpp
- src/test_string_util.cpp
- test/truncate_read_file.cc
n/a
In the MacOS CI test, cppcheck now uses 2.14.0 and an error was output, so this PR fixed it.
> Fixed error reports of failure in cppcheck 2.14.0

- src/cache.cpp
- src/cache.h
- src/s3fs.cpp
While some of these originate as `char *`, eventually they convert to `std::string` in the `std::map` lookup.
> Keep cache path parameters as `std::string`

- src/autolock.h
- src/cache.cpp
- src/cache.h
- src/curl.cpp
- src/curl.h
- src/fdcache.cpp
- src/fdcache.h
- src/fdcache_auto.cpp
- src/fdcache_auto.h
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
- src/s3fs.cpp
- src/s3fs_cred.cpp
- src/s3fs_cred.h
Instead annotate the methods with `REQUIRES` so that the caller knows if they should lock.  For public interfaces, introduce `HasLock` wrappers.  This simplifies control flow, allows migration to `std::mutex`, and eventually will enable use of static lock checking.
> Remove uses of `AutoLock::ALREADY_LOCKED`

- autogen.sh
- configure.ac
- src/s3fs.cpp
- src/s3fs_help.cpp
#2457
Currently, the s3fs version display includes the git commit hash(short sha1).
However, in the s3fs distributed from the package repository, the commit hash value is `unknown`.
Because this `unknown` can be misleading, the version notation will be changed to the following depending on the environment in which s3fs was built.
The commit hash will not be displayed.
```
Amazon Simple Storage Service File System V1.94 with OpenSSL
```
- If there is no untracked file:  
```
Amazon Simple Storage Service File System V1.94(commit:254d717) with OpenSSL
```
- If there is an untracked file:  
```
Amazon Simple Storage Service File System V1.94(commit:254d717 +untracked files) with OpenSSL
```
This case applies when extracting a distribution archive of source code created by `make dist`.
``` …
```
> Changed the display format of the Git commit hash in the version display

- src/cache.cpp
- src/cache.h
- src/fdcache_entity.cpp
- src/fdcache_page.cpp
- src/metaheader.cpp
- src/s3fs.cpp
- src/sighandlers.cpp
This generates the same code but is safer due to using an implicit length and allowing member initialization.
> Replace `memset` with C++11 value initialization

- .clang-tidy
- src/addhead.h
- src/cache.h
- src/fdcache_auto.h
- src/fdcache_pseudofd.h
- src/sighandlers.h
- src/threadpoolman.h
Deleting them better conveys the intent.
> Make deleted constructors and operators public

- src/common.h
- src/fdcache_pseudofd.cpp
- src/metaheader.cpp
- src/mpu_util.cpp
- src/openssl_auth.cpp
- src/s3fs_cred.cpp
- src/s3fs_logger.cpp
- src/s3fs_xml.cpp
- src/threadpoolman.cpp
Found via misc-include-cleaner but this requires more work.
> Remove unused headers found by clang-tidy

- src/fdcache.cpp
- src/fdcache.h
- src/fdcache_entity.h
#2438 #2463
Fixed a bug that caused a deadlock during simultaneous processing such as file uploads from multiple threads when there was not enough cache space.
The FdManager class manages object paths and FdEntity in a map, but when there is not enough cache space, there is a process that changes the object path of that entry.
For this process, the FdManager object is operated from the FdEntity method.
At this time, a deadlock occurred.
As a currently solution, we delayed the operation rather than directly operating the map object when calling the process to change the object path.
@gaul
I think this is the best solution at the moment.
We are also considering adding test cases, but it may be difficult.
(Due to the issue of whether we can reliably create a timing that causes the bug to …
> Fixed a deadlock in the FdManager::ChangeEntityToTempPath method call

- src/curl.cpp
- src/curl.h
Use a struct with named fields instead of a `pair` for clarity and use a single `map` to store the structs for efficiency.
> Simplify curl progress tracking

- .github/workflows/ci.yml
- .github/workflows/linux-ci-helper.sh
#2469 #2485 #2496
In order to make release 1.95 the last supported package for CentOS 7, we are temporarily restoring CI execution(Github Actions) for CentOS 7.
This PR makes the following modifications (restorations):
- Using the Vault repository for CentOS 7
- Setting an environment variable to use nodejs16 when executing actions/checkout on CentOS 7
> Continued Github Actions(CI) execution after CentOS 7 EOL

- src/curl.cpp
- src/curl.h
- src/curl_handlerpool.cpp
- src/curl_handlerpool.h
This is safer and clarifies the ownership of pointers.
> Wrap `CURL*` in a `std::unique_ptr`

- src/common.h
- src/curl.h
- src/openssl_auth.cpp
Clang does not support this:
https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#conditional-locks
> Disable thread safety analysis on conditional locks

- src/s3fs.cpp
- src/s3fs_util.cpp
- src/s3fs_util.h
- src/s3fs_xml.cpp
- src/s3fs_xml.h
`std::mutex` RAII removes the need for these.
> Remove unneeded lock utility functions

- src/fdcache_entity.cpp
This is not safe -- another caller could modify a `std::string` field while logging which could read an invalid pointer.  References #2490.
> Acquire lock before logging

- src/curl.cpp
- src/curl.h
When trying to connect to a compatible S3 server that is serving the S3 API under a URI prefix, ex: 
```
https://storage.example/s3
```
`s3fs` fails to compute the SignV4; specifically on capturing the URI of the s3host.
This PR will instead use the prefix (if any) when calculating the SignV4 uri; enabling support for custom S3 providers served on a URI.
If no prefix is given in the custom `url`, the current behaviour of using "/" is maintained.
> s3 signv4 support pefixed s3 hosts

- src/s3fs_util.cpp
FreeBSD returns -1 since it has no limits for `_SC_GETPW_R_SIZE_MAX` and `_SC_GETGR_R_SIZE_MAX` but is not required to reset `errno`.  Also fix up logging.  Fixes #2514.
> Set `errno` to zero before calling `sysconf`

- .github/workflows/linux-ci-helper.sh
n/a
The `ps` command required for testing could not be found.(I have not investigated the reason in detail.)
I changed the environment of `opensuse/leap:15` to install the `procps` package, and this problem was solved.
> Fixed opensuse/leap:15 test

- test/integration-test-main.sh
#2418
Until recently, hardlink on macos-fuse-t was not implemented by s3fs and resulted in an error, but the error output was empty.
When I noticed currently, it was outputting `"Input/output error"`.
This caused `test_hardlink` execution(which had a special branch for macos-fuse-t) to fail, so I fixed it.
Note, this error output may change in the future, but I will check again if it does.
(s3fs is returning an ENOTSUP error, and "Input/output error" seems inappropriate as the message.)
Although the `test_hardlink` test was fixed, other tests still fail, so the macos tests do not pass overall.
> Fixed hardlink test for macos

- src/curl.cpp
Previously `-o curldbg=body` would read uninitialized memory.
> Log entire line when curldbg lacks a newline

- .github/workflows/ci.yml
Previously this ignored use-after-frees and other errors.
> Return non-zero exit code on Valgrind errors

- src/curl.cpp
n/a
A simple coding mistake inside S3fsCurl::RequestPerform has been fixed.
_(It's a mystery why such a simple mistake still exists, but we'll be more careful in the future. I think it probably wasn't detected because this error didn't occur.)_
> Fixed miss-return code in S3fsCurl::RequestPerform

- src/s3fs.cpp
This avoids a use-after-free in the destructor.
> Call Rename outside AutoFdEntity scope

- .clang-tidy
- src/curl.cpp
- src/s3fs.cpp
- src/s3fs_cred.cpp
This fixes one real error, one misreported `EPERM`, and some false positives.  References #2529.
> Enable readability-implicit-bool-conversion

- test/integration-test-main.sh
#2531 
This is a follow-up fix to #2531.
In MacOS testing, the `test_multipart_mix` test fails when the `nocopyapi` option is specified.
The error occurs in the `list`/`remove` operation to `xattr`, as shown below(one example), and the test fails:
```
s3fs: [INF] s3fs.cpp:s3fs_listxattr(3988): [path=/testrun-12125/big-file-s3fs-14543.txt][list=0x7fda31008200][size=16384]
s3fs: [INF] s3fs.cpp:s3fs_listxattr(3988): [path=/testrun-12125/big-file-s3fs-14543.txt-mix][list=0x7fda31008200][size=16384]
s3fs: [INF] s3fs.cpp:s3fs_removexattr(4054): [path=/testrun-12125/big-file-s3fs-14543.txt-mix][name=com.apple.FinderInfo][pid=0,uid=501,gid=20]
s3fs: [INF] s3fs.cpp:s3fs_listxattr(3988): [path=/testrun-12125/big-file-s3fs-14543.txt][list=0x7fda28868200][size=16384]
s3fs: [INF] …
```
> Modified and bypassed test_multipart_mix on MacOS with nocopyapi

- src/fdcache.h
- src/fdcache_entity.h
- src/fdcache_fdinfo.cpp
This allows clang's thread safety checks to pass.
> Fix locking annotations and add one missing lock

- test/test-utils.sh
`wc` has an optimization that can use metadata when stdin is set to a file.  Also fix up logging.
> Ensure that test checks data length

- src/openssl_auth.cpp
#2544
Fixed `comparison between signed and unsigned integer expressions` warning.
> Fixed warnings on integer comparisons in openssl_auth.cpp

- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/s3fs.cpp
#2490
There were too many requests for fixes in PR #2490, so I created a PR based on #2490.
The biggest difference is that the RowFlushHasLock() (and FlushHasLock()) methods are reentrant, so in order to maintain a strict locking state, it is necessary to separate the functions.
For other details, please see the comments in PR #2490.
> [Improvement #2490] Add GUARDED_BY to FdEntity and fix locking

- src/curl.cpp
- src/curl.h
- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
Add `const` where possible and avoid unnecessary reference parameters.
> Simplify some method parameters

- src/curl.cpp
- src/curl.h
This is simpler and lighter-weight.
> Replace `curl_warnings_lock` with `std::atomic`

- src/common.h
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/fdcache_fdinfo.h
- src/sighandlers.cpp
This requires a fake `GetMutex` for the lock checker to understand the control flow.  Also remove unneeded locking comments that annotation supersede.  Follows on to #2491.
> Add missing `GUARDED_BY` to `fdcache_entity`

- .clang-tidy
- src/addhead.cpp
- src/cache.cpp
- src/curl.cpp
- src/curl_multi.cpp
- src/fdcache.cpp
- src/fdcache_entity.cpp
- src/fdcache_fdinfo.cpp
- src/fdcache_page.cpp
- src/fdcache_pseudofd.cpp
- src/fdcache_untreated.cpp
- src/metaheader.cpp
- src/mpu_util.cpp
- src/openssl_auth.cpp
- src/s3fs.cpp
- src/s3fs_cred.cpp
- src/s3objlist.cpp
- src/s3objlist.h
- src/string_util.cpp
- src/types.h
- test/truncate_read_file.cc
- test/write_multiblock.cc
Applied via `clang-tidy -fix`.
> Use `auto` for iterator variable types

- src/fdcache.cpp
- src/fdcache.h
- src/fdcache_entity.cpp
- src/fdcache_entity.h
`FdEntity` may have multiple references due to `ChangeEntityToTempPath`.  This relies on the `std::enable_shared_from_this` helper to create a `std::shared_ptr` from `this`.  Fixes #2532.
> Use `std::shared_ptr` to refer to `FdEntity`

- src/curl.cpp
- src/curl.h
- src/openssl_auth.cpp
- src/threadpoolman.cpp
- src/threadpoolman.h
Make destructor public so `std::unique_ptr` can call it.    Also restrict singleton creation to satisfy cppcheck.
> Remove more raw pointers

- src/gnutls_auth.cpp
- src/nss_auth.cpp
- src/openssl_auth.cpp
Follows on to 2d1409a67222d9e9050a352d71474498f34a38fd.
> Fixed warnings on integer comparisons

- test/write_multiblock.cc
> Use `std::max` instead of conditional

- src/openssl_auth.cpp
> Expand use of `auto`

- .github/workflows/ci.yml
clang-tidy takes 4 minutes on my laptop compared to ALL_TESTS=1 which takes 8 minutes.  Using a separate tasks avoids duplicating clang-tidy and unnecessarily slowing CI run-time.
> Separate clang-tidy into its own CI task

- src/sighandlers.cpp
https://github.com/s3fs-fuse/s3fs-fuse/pull/2569/files#r1815840691
In SignalUSR1 processing, a bug has been fixed in the process of disabling request queuing caused by multiple interrupts.
> Fixed a bug in clearing the queue accumulated during USR1 processing

- src/addhead.cpp
- src/addhead.h
- src/cache.cpp
- src/curl.cpp
- src/curl_handlerpool.cpp
- src/curl_multi.cpp
- src/fdcache.cpp
- src/fdcache_entity.cpp
- src/s3fs.cpp
- src/s3objlist.h
- src/sighandlers.cpp
- src/string_util.cpp
- src/threadpoolman.cpp
- src/types.h
> Add missing utility header for `std::move`

- src/cache.cpp
- src/curl.cpp
- src/curl_handlerpool.cpp
- src/curl_multi.cpp
- src/fdcache.cpp
- src/fdcache_entity.cpp
- src/fdcache_fdinfo.cpp
- src/fdcache_pseudofd.cpp
- src/fdcache_untreated.cpp
- src/s3fs_cred.cpp
- src/threadpoolman.cpp
> Add missing mutex header

- src/curl.cpp
- src/string_util.cpp
- src/string_util.h
This avoids copies when used with `std::move`.
> Use pass-by-value for peeloff

- test/integration-test-main.sh
#2585
There are some unknown aspects of FUSE-T behavior, so we shuold bypass this `test_extended_attributes` test.
I plan to revert it to the original setting once we understand the cause and workaround.
For more information, see #2585.
> Bypassed test_extended_attributes test on MacOS

- src/cache.cpp
`stat_cache_entry::meta` uses a case-insensitive comparator so there is no need to loop over each entry to compare each key with lowercase.
> Look up header values directly

- .github/workflows/ci.yml
- test/integration-test-main.sh
- test/test-utils.sh
#2552 
This has already started, and Github Action executions for `macos-12` have begun to be automatically canceled.
_(November 4, 14:00 UTC - November 5, 00:00 UTC in [this page](https://github.com/actions/runner-images/issues/10721))_
With this PR, we can migrate to macos-13.
_I tried to migrate directly to `macos-14`, but received a build error, so I will stick with upgrading to `macos-13`._
> Changed the macOS Github Actions runner image to macos-13

- src/metaheader.cpp
- src/string_util.cpp
- src/string_util.h
This reduces the Windows-specific code.
> Call `std::get_time` instead of `strptime`

- src/Makefile.am
- src/curl.cpp
- src/curl.h
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
- src/mpu_util.cpp
- src/s3fs.cpp
- src/s3fs_cred.cpp
- src/s3fs_cred.h
- src/s3fs_help.cpp
- src/s3fs_threadreqs.cpp
- src/s3fs_threadreqs.h
- src/threadpoolman.cpp
- src/threadpoolman.h
#2600
This is the split PR Phase 2 (2/8) for #2600.
Single requests(synchronous requests) are changed to process by a worker thread managed by `ThreadPoolMan`.
The implementation of each request process has been moved to the handler(Callback) function of the worker thread.
As a result, the `S3fsCurl` object held by each request process function has been moved to a worker thread managed by `ThreadPoolMan`.
(In a future PR, the construction location of the `S3fsCurl` object will be moved again.)
All worker thread processing is concentrated in new `s3fs_threadreqs.cpp`  file.
(From now on, I will continue to concentrate in this file.)
Asynchronous and multi-request processing is not yet modified in this PR.
This PR will be rebased and removed from draft status once the previous PR(#2601) is …
> Refactored single type requests to use through ThreadPoolMan

- src/Makefile.am
- src/curl.cpp
- src/curl.h
- src/fdcache_entity.cpp
- src/fdcache_fdinfo.cpp
- src/mpu_util.cpp
- src/s3fs.cpp
- src/s3fs_threadreqs.cpp
- src/s3fs_threadreqs.h
- src/syncfiller.cpp
- src/syncfiller.h
#2600 
This is the split PR Phase 3 (3/8) for #2600.
Multi-Head request processing has been changed to no longer use `S3fsMultiCurl`.
Instead, it has been moved to a worker thread managed by `ThreadPoolMan`.
This PR will be rebased and removed from draft status once the previous PR(#2602) is merged into master.
> Changed multiple Head requests from S3fsMultiCurl to ThreadPoolMan

- src/curl.cpp
- src/curl.h
- src/curl_util.h
- src/fdcache_entity.cpp
- src/s3fs.cpp
- src/s3fs_threadreqs.cpp
- src/s3fs_threadreqs.h
#2600
This is the split PR Phase 4 (4/8) for #2600.
The processing of Multi-PutHead requests(including `Rename` processing) has been changed so that they do not use `S3fsMultiCurl`.
Instead, they have been moved to a worker thread managed by `ThreadPoolMan`.
This PR will be rebased and removed from draft status once the previous PR(#2603) is merged into master.
> Refactored multipart put head request

- src/curl.cpp
- src/curl.h
- src/fdcache_entity.cpp
- src/fdcache_entity.h
- src/fdcache_fdinfo.cpp
- src/fdcache_fdinfo.h
- src/s3fs_threadreqs.cpp
- src/s3fs_threadreqs.h
#2600
This is the split PR Phase 6 (6/8) for #2600.
The Multipart Upload (Contents / Copy) process has been changed so that it no longer uses `S3fsMultiCurl`.
Instead, it has been moved to a worker thread managed by `ThreadPoolMan`.
The Contents and Copy processes for Multipart Upload have also been reorganized, and common parts that can be commonized have been made common.
This PR will be rebased and removed from draft status once the previous PR(#2605) is merged into master.
> Refactored for standardizing content and copy handling for Multipart Upload

- .github/workflows/ci.yml
- src/Makefile.am
- src/curl.cpp
- src/curl.h
- src/curl_share.cpp
- src/curl_share.h
- src/s3fs.cpp
- src/s3fs_threadreqs.cpp
- src/s3fs_threadreqs.h
- src/threadpoolman.cpp
- src/threadpoolman.h
- test/run_tests_using_sanitizers.sh
- test/threadsanitizer_suppressions.txt
#2600
This is the split PR Phase 8 (8/8) for #2600.
Added the `S3fsCurlShare` class which manages Curl Share handles.
This class manages Curl Share Handle for each Thread.
The retention(creation and management) of `S3fsCurl` objects has been moved to `ThreadPoolMan`'s worker thread management function.
As a result, the Handler(Callback) for each request does not retain the `S3fsCurl` object, but receives it as a parameter.
As a result, the Data Race issue has been resolved by managing the Curl Share Handle on a per-thread basis.
This re-enables `CURL_LOCK_DATA_SSL_SESSION`, which was disabled in #2601.
Last, I removed the threadsanitizer_suppressions.txt file that ignores DataRace, which was added in #2559, and reverted it.
This PR will be rebased and removed from draft status once the …
> Added new class for curl share handle

- src/psemaphore.h
This matches the macOS implementation.
> Delete Semaphore copy and move methods

- .clang-tidy
- src/curl.cpp
- src/s3fs.cpp
- test/truncate_read_file.cc
The former are easier to identify.  Found via clang-tidy.
> Prefer C++-style casts over C-style casts

- src/s3fs_threadreqs.cpp
n/a
There was a problem with the processing of the bucket check (service check) at startup, so we have fixed it.
This was caused by a mistake in the recent refactoring.
> Fixed a bug in check_service_req_threadworker

- src/fdcache_entity.cpp
- src/mpu_util.cpp
- src/s3fs.cpp
- src/s3fs_cred.cpp
`char *` automatically convert via the implicit `std::string` constructor.
> Remove explicit `std::string` constructors

- src/curl_share.cpp
- src/curl_share.h
`ShareHandles.erase` implicitly calls this via the `unique_ptr` destructor.
> Remove double free in `DestroyCurlShareHandle`

- .github/workflows/ci.yml
- .github/workflows/linux-ci-helper.sh
Relocate cppcheck and Shellcheck into a single CI target instead of running them as part of all distributions.  While this modestly reduces run-time by about 20 seconds, more importantly it avoids workarounds for older checker versions and simplifies the code.
> Expand clang-tidy CI target to all static-checks

- src/s3fs_cred.cpp
- src/s3fs_cred.h
#2602
#2612
There was a mistake in the refactoring of #2602, so I fixed it.
The problem in issue #2612 is another reason in only v1.95, so it is different from this fix.
(The #2602 refactoring cleared the problem in v1.95, but it introduced this problem instead.)
> Fixed refactoring mistakes about loading IAM credentials

- .github/workflows/linux-ci-helper.sh
- .gitignore
- test/integration-test-common.sh
- test/integration-test-main.sh
This downloads a tarball by hash instead of using a submodule.
References #1589.
> Run passing tests from pjdfstest

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/support_request.md
n/a
Github no longer supports the old issue template, so I'm migrating to a new one.
In the new template, issues are divided into `support requests`(including bug reports) and `feature requests`.
For `feature request` templates, I added a `feature request` label. (Note: remove it if you don't need it.)
> Updated to the new issue template workflow

- src/fdcache_entity.cpp
- src/fdcache_entity.h
#2623
This PR adds variables and methods for #2623.
To solve the problem of point out by #2623, the `FdEntity::path` variable needs to be available without locking for performance.
The `FdEntity::path` variable is protected by a lock(`FdEntity::fdent_lock`), but this lock is wide-ranging.
#2623 code should avoid this lock, but I propose this PR method instead of not locking.
I prepared a copy(backup for read only) variable of the `FdEntity::path` variable and prepared a lock(`FdEntity::ro_path_lock`) for only the `FdEntity::ro_path` variable.
This lock variable provides exclusive control only when the `FdEntity::path` variable is updated, so it provides the same functionality as not locking `FdEntity::fdent_lock`.
And I think the variable can be safely held.
@gaul
This process seems …
> Added backup variable for fdcache entity path

- src/fdcache.cpp
- src/fdcache_entity.cpp
- src/fdcache_entity.h
https://github.com/s3fs-fuse/s3fs-fuse/issues/2617
Change the way to get existing fdentity to better conccurent IO's performance.
Instead of traversing the fent map and only compare the pseudo fd, which needs to hold every fdentity 's lock, I look for the fdentity with path at first and then verify the pseudo fd, which only needs to hold the right fdentity's lock.
I started 20 processes to read/write 500 files of 1MB in total concurrently. For ver 1.91, the RW performance is twice of that of the old code. And for ver 1.95, the performance is 20% better after this fix.
P.S. v1.95 performs worse than v1.91 (just half) according to my test (without this fix). This is another topic though. I will try to figure out the reason too and maybe you can also have a look into it.
> change the way to get existing fdentity to optimize concurrent IO performance

- test/integration-test-main.sh
#2654
Previously, when it updated xattr, only the ctime was updated.
However, only on macos13(we are using macos-fuse-t), the atime is also updated.
_(https://github.com/macos-fuse-t/fuse-t/issues/87)_
Therefore, I have revised the test to make this the normal expected value.
> Updated CI test result for macos about updating xattr

- src/curl.cpp
- src/curl_util.cpp
- src/s3fs.cpp
n/a
Some message output levels have been changed from `INFO` to `DBG`.
The changed messages previously required the `INFO` level, but I have now determined that it is no longer necessary to have it at that level.
Also, by changing these message output levels, the execution time of Github Actions(`CI`) can be slightly reduced.
- s3fs_getxattr  
On MacOS, there are a large number of calls, so it is already at the `DBG` level.
On Linux systems, there are also a large number of calls, so we can change it to the `DBG` level.
- prepare_url  
This function rewrites the request URL, but this function is stable and does not need to be `INFO`, so we can change it.
- S3fsCurl::insertV4Headers  
Although this function makes a signature, we decided that there is always no need to check the contents …
> Changed some INFO level log messages to DBG level

- .github/workflows/ci.yml
- .github/workflows/linux-ci-helper.sh
This is EOL:
https://ubuntu.com/blog/ubuntu-20-04-lts-end-of-life-standard-support-is-coming-to-an-end-heres-how-to-prepare
> Remove Ubuntu 20.04 from CI

- test/integration-test-main.sh
- test/test-utils.sh
Previously this used `/dev/urandom` does not guarantee uniqueness and sometimes blocked on macOS.  References #2690.
> Simplify temporary file creation via `mktemp`

- src/addhead.cpp
- src/curl.cpp
- src/s3fs.cpp
- src/s3fs.h
42b74c9d2ed67da4cf1f6586d179b1d3c34fcb10 introduced this flag but it is not clear that this behavior is required with recent libxml2 versions.
> Remove S3FS_MALLOC_TRIM

- test/filter-suite-log.sh
- test/mergedir.sh
- test/sample_delcache.sh
Found via shellcheck.  Reference:
https://www.shellcheck.net/wiki/SC2268
> Remove unneeded x-prefix in comparisons

- src/fdcache_page.cpp
- src/fdcache_page.h
- src/fdcache_stat.cpp
- src/fdcache_stat.h
- src/test_page_list.cpp
#2709
Changed `PageList::Serialize()` to use `flock` to exclusively handle `ftruncate`->`pwrite` operations.
This fixes a bug reported in https://github.com/s3fs-fuse/s3fs-fuse/issues/2709#issuecomment-3226548346.
> Changed to use rename when serializing to FileCacheStat

- src/common.h
- src/curl.cpp
- src/s3fs.cpp
- src/s3fs_global.cpp
These can be used to evaluate changes like #2707.  Ideally tests could assert how many operations they expect although this will require a localhost HTTP server.
> Add S3 operation performance counters

- test/integration-test-main.sh
n/a
In a recent CI(GHA) run, the `test_external_modification` test on macOS often failed.
I investigated the cause and have now found it, so I posted this PR.
The cause was a difference in the way `getattr` calls are made from FUSE on macOS and other Linuxs.
In the `test_external_modification` test, after uploading a file, it waits one second(while the file contents are modified by external process) and then reads it.
On other Linuxs, there is no `getattr` call after uploading, but on macOS, the `getattr` call is made.
The `stat_cache_interval_expire=1` option was set for s3fs when the test was run, so if the cache is accessed via a `getattr` call within the cache expiration period, the expiration period is extended.
For this reason, the `getattr` call is made on macOS, and waiting 1 …
> Fixed test_external_modification test for MacOS

- src/cache_node.cpp
- src/cache_node.h
#2707
There was problem in the process of checking whether stat cache was available for cash out, which has been fixed.
(There were cases where cash out was not possible when negative cache was present.)
_This PR is one in a series of enhancements using Stat Cache following #2707. (The PRs have been separated into smaller PRs.)_
> Fixed Stat cache expire check processing
